// OrchestratorService — operator-facing APIs for reconciling run
// lifecycle directly from Castle (CRI-133). Design note:
// docs/adrs/ADR-0005-orchestrator-event-subscription.md (polling was chosen
// over a server stream).
//
// The read RPCs are observation-only. CancelRun (CRI-142) is the single
// operator-facing write: it stamps a run terminal in Castle when the operator
// deliberately deletes the CriteriaRun, without requiring the owning agent
// to act. It is never anonymously reachable and is not covered by dev-mode
// anonymous reads.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: criteria/v1/orchestrator.proto

package criteriav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRunEventsRequest anchors a single poll of a run's event stream.
type SubscribeRunEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id is the run to poll. Required.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// since_seq is the exclusive lower bound; 0 replays from the beginning.
	// Pass the previously persisted cursor to resume after an operator restart.
	SinceSeq uint64 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	// limit caps the page size; 0 selects the server default. When the page is
	// full the response carries next_since_seq for immediate continuation.
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRunEventsRequest) Reset() {
	*x = SubscribeRunEventsRequest{}
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRunEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRunEventsRequest) ProtoMessage() {}

func (x *SubscribeRunEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRunEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRunEventsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRunEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SubscribeRunEventsRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *SubscribeRunEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SubscribeRunEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events are the persisted envelopes with seq > since_seq, ascending by seq.
	Events []*Envelope `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// last_seq is the highest seq returned in this page; 0 when the page is
	// empty. Persist it as the per-run cursor ONLY after a non-empty page —
	// on an empty page, keep the previously persisted cursor unchanged.
	LastSeq uint64 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// next_since_seq is set only when the page is full; pass it as since_seq to
	// continue paging without waiting for the next reconcile interval.
	NextSinceSeq  uint64 `protobuf:"varint,3,opt,name=next_since_seq,json=nextSinceSeq,proto3" json:"next_since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRunEventsResponse) Reset() {
	*x = SubscribeRunEventsResponse{}
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRunEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRunEventsResponse) ProtoMessage() {}

func (x *SubscribeRunEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRunEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeRunEventsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRunEventsResponse) GetEvents() []*Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubscribeRunEventsResponse) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SubscribeRunEventsResponse) GetNextSinceSeq() uint64 {
	if x != nil {
		return x.NextSinceSeq
	}
	return 0
}

type ListActiveRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveRunsRequest) Reset() {
	*x = ListActiveRunsRequest{}
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveRunsRequest) ProtoMessage() {}

func (x *ListActiveRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveRunsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveRunsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_orchestrator_proto_rawDescGZIP(), []int{2}
}

type ListActiveRunsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// runs are the non-terminal runs (pending | running | paused).
	Runs          []*Run `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveRunsResponse) Reset() {
	*x = ListActiveRunsResponse{}
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveRunsResponse) ProtoMessage() {}

func (x *ListActiveRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveRunsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveRunsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ListActiveRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

type CancelRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id is the run to cancel. Required.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// reason is audit metadata describing why the operator cancelled the run
	// (e.g. "criteriarun deleted"). Empty selects "cancelled by operator".
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run is the cancelled run record as persisted.
	Run           *Run `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

var File_criteria_v1_orchestrator_proto protoreflect.FileDescriptor

const file_criteria_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1ecriteria/v1/orchestrator.proto\x12\vcriteria.v1\x1a\x18criteria/v1/events.proto\x1a\x1acriteria/v1/criteria.proto\"e\n" +
	"\x19SubscribeRunEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8c\x01\n" +
	"\x1aSubscribeRunEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.criteria.v1.EnvelopeR\x06events\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x12$\n" +
	"\x0enext_since_seq\x18\x03 \x01(\x04R\fnextSinceSeq\"\x17\n" +
	"\x15ListActiveRunsRequest\">\n" +
	"\x16ListActiveRunsResponse\x12$\n" +
	"\x04runs\x18\x01 \x03(\v2\x10.criteria.v1.RunR\x04runs\"A\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\x11CancelRunResponse\x12\"\n" +
	"\x03run\x18\x01 \x01(\v2\x10.criteria.v1.RunR\x03run2\xa3\x02\n" +
	"\x13OrchestratorService\x12e\n" +
	"\x12SubscribeRunEvents\x12&.criteria.v1.SubscribeRunEventsRequest\x1a'.criteria.v1.SubscribeRunEventsResponse\x12Y\n" +
	"\x0eListActiveRuns\x12\".criteria.v1.ListActiveRunsRequest\x1a#.criteria.v1.ListActiveRunsResponse\x12J\n" +
	"\tCancelRun\x12\x1d.criteria.v1.CancelRunRequest\x1a\x1e.criteria.v1.CancelRunResponseB>Z<github.com/brokenbots/criteria/sdk/pb/criteria/v1;criteriav1b\x06proto3"

var (
	file_criteria_v1_orchestrator_proto_rawDescOnce sync.Once
	file_criteria_v1_orchestrator_proto_rawDescData []byte
)

func file_criteria_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_criteria_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_criteria_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteria_v1_orchestrator_proto_rawDesc), len(file_criteria_v1_orchestrator_proto_rawDesc)))
	})
	return file_criteria_v1_orchestrator_proto_rawDescData
}

var file_criteria_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_criteria_v1_orchestrator_proto_goTypes = []any{
	(*SubscribeRunEventsRequest)(nil),  // 0: criteria.v1.SubscribeRunEventsRequest
	(*SubscribeRunEventsResponse)(nil), // 1: criteria.v1.SubscribeRunEventsResponse
	(*ListActiveRunsRequest)(nil),      // 2: criteria.v1.ListActiveRunsRequest
	(*ListActiveRunsResponse)(nil),     // 3: criteria.v1.ListActiveRunsResponse
	(*CancelRunRequest)(nil),           // 4: criteria.v1.CancelRunRequest
	(*CancelRunResponse)(nil),          // 5: criteria.v1.CancelRunResponse
	(*Envelope)(nil),                   // 6: criteria.v1.Envelope
	(*Run)(nil),                        // 7: criteria.v1.Run
}
var file_criteria_v1_orchestrator_proto_depIdxs = []int32{
	6, // 0: criteria.v1.SubscribeRunEventsResponse.events:type_name -> criteria.v1.Envelope
	7, // 1: criteria.v1.ListActiveRunsResponse.runs:type_name -> criteria.v1.Run
	7, // 2: criteria.v1.CancelRunResponse.run:type_name -> criteria.v1.Run
	0, // 3: criteria.v1.OrchestratorService.SubscribeRunEvents:input_type -> criteria.v1.SubscribeRunEventsRequest
	2, // 4: criteria.v1.OrchestratorService.ListActiveRuns:input_type -> criteria.v1.ListActiveRunsRequest
	4, // 5: criteria.v1.OrchestratorService.CancelRun:input_type -> criteria.v1.CancelRunRequest
	1, // 6: criteria.v1.OrchestratorService.SubscribeRunEvents:output_type -> criteria.v1.SubscribeRunEventsResponse
	3, // 7: criteria.v1.OrchestratorService.ListActiveRuns:output_type -> criteria.v1.ListActiveRunsResponse
	5, // 8: criteria.v1.OrchestratorService.CancelRun:output_type -> criteria.v1.CancelRunResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_criteria_v1_orchestrator_proto_init() }
func file_criteria_v1_orchestrator_proto_init() {
	if File_criteria_v1_orchestrator_proto != nil {
		return
	}
	file_criteria_v1_events_proto_init()
	file_criteria_v1_criteria_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v1_orchestrator_proto_rawDesc), len(file_criteria_v1_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteria_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_criteria_v1_orchestrator_proto_depIdxs,
		MessageInfos:      file_criteria_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_criteria_v1_orchestrator_proto = out.File
	file_criteria_v1_orchestrator_proto_goTypes = nil
	file_criteria_v1_orchestrator_proto_depIdxs = nil
}
