// PeerService — host->peer supervision journal (ADR-0007 Stage A).
//
// Stage A supervision truth: process-lifecycle facts cross the wire as
// first-class typed events instead of being inferred from gRPC transport
// errors. The peer (a remote Criteria or adapter host process) is the gRPC
// server on the phone-home connection; the host opens Supervise and reads
// the lifecycle journal.
//
// Evolution discipline (additive-only):
//   - Field numbers in this file are permanent once assigned. Never reuse,
//     renumber, or re-type an existing field; only ever append.
//   - The next free `kind` oneof arm in SupervisionEvent is field 11. Do NOT
//     `reserved` forward numbers — reserve only genuinely abandoned ones.
//   - Stage B run-graph events ride THIS journal: extend SupervisionEvent
//     with new arms; do not fork a second supervision stream or file.
//   - Supervision protocol evolution is negotiated via capabilities strings,
//     not proto package churn: `criteria.v1` stays.
//
// Delivery semantics:
//   - At-least-once delivery. Consumers dedup on (peer conn identity,
//     event_seq).
//   - event_seq is global monotonic per peer process and gapless.
//   - Replay: a host (re-)opening Supervise passes since_event_seq; the peer
//     streams lifecycle truth strictly after that value (exclusive).
//   - Terminal events (ProcessExited, CrashClassified) persist to a bounded
//     in-peer journal (default 4096 events, env-tunable) and are replayed
//     FIRST on reconnect, so crash evidence survives the RPC stream that
//     died.
//
// Ordering:
//   - Journal append order == emission order.
//   - StreamFlushed.up_to_seq is monotonic per channel.
//
// Heartbeat:
//   - Supervise emits SupervisionHeartbeat every 30s while idle. It
//     complements, and does not replace, the CRI-276 transport keepalive.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: criteria/v1/peer.proto

package criteriav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupervisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream journal entries strictly after this sequence number (exclusive);
	// 0 replays the journal from the beginning.
	SinceEventSeq uint64 `protobuf:"varint,1,opt,name=since_event_seq,json=sinceEventSeq,proto3" json:"since_event_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisionRequest) Reset() {
	*x = SupervisionRequest{}
	mi := &file_criteria_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisionRequest) ProtoMessage() {}

func (x *SupervisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisionRequest.ProtoReflect.Descriptor instead.
func (*SupervisionRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *SupervisionRequest) GetSinceEventSeq() uint64 {
	if x != nil {
		return x.SinceEventSeq
	}
	return 0
}

// SupervisionEvent is one entry of the peer's supervision journal: a typed
// process-lifecycle fact with a gapless per-peer sequence number.
type SupervisionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global monotonic per peer process, gapless.
	EventSeq uint64 `protobuf:"varint,1,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	// When the fact was recorded (UTC).
	At *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	// Process-level subject: the adapter type the peer supervises.
	AdapterType string `protobuf:"bytes,3,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
	// "scopeName/scopeInstanceID" or "" (legacy mode).
	Scope string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// Session-scoped events carry the session id; "" for process-level.
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Typed lifecycle payload. Field numbers here are permanent; next arm =
	// field 11 (additive-only; see file header).
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*SupervisionEvent_Spawned
	//	*SupervisionEvent_Exited
	//	*SupervisionEvent_Crash
	//	*SupervisionEvent_Flushed
	//	*SupervisionEvent_Heartbeat
	Kind          isSupervisionEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisionEvent) Reset() {
	*x = SupervisionEvent{}
	mi := &file_criteria_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisionEvent) ProtoMessage() {}

func (x *SupervisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisionEvent.ProtoReflect.Descriptor instead.
func (*SupervisionEvent) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *SupervisionEvent) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *SupervisionEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *SupervisionEvent) GetAdapterType() string {
	if x != nil {
		return x.AdapterType
	}
	return ""
}

func (x *SupervisionEvent) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SupervisionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SupervisionEvent) GetKind() isSupervisionEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SupervisionEvent) GetSpawned() *ProcessSpawned {
	if x != nil {
		if x, ok := x.Kind.(*SupervisionEvent_Spawned); ok {
			return x.Spawned
		}
	}
	return nil
}

func (x *SupervisionEvent) GetExited() *ProcessExited {
	if x != nil {
		if x, ok := x.Kind.(*SupervisionEvent_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *SupervisionEvent) GetCrash() *CrashClassified {
	if x != nil {
		if x, ok := x.Kind.(*SupervisionEvent_Crash); ok {
			return x.Crash
		}
	}
	return nil
}

func (x *SupervisionEvent) GetFlushed() *StreamFlushed {
	if x != nil {
		if x, ok := x.Kind.(*SupervisionEvent_Flushed); ok {
			return x.Flushed
		}
	}
	return nil
}

func (x *SupervisionEvent) GetHeartbeat() *SupervisionHeartbeat {
	if x != nil {
		if x, ok := x.Kind.(*SupervisionEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isSupervisionEvent_Kind interface {
	isSupervisionEvent_Kind()
}

type SupervisionEvent_Spawned struct {
	Spawned *ProcessSpawned `protobuf:"bytes,6,opt,name=spawned,proto3,oneof"` // pid, binary, digest, version
}

type SupervisionEvent_Exited struct {
	Exited *ProcessExited `protobuf:"bytes,7,opt,name=exited,proto3,oneof"` // exit_code, signal, idle_ms, graceful
}

type SupervisionEvent_Crash struct {
	Crash *CrashClassified `protobuf:"bytes,8,opt,name=crash,proto3,oneof"` // reason (shared const set), detail
}

type SupervisionEvent_Flushed struct {
	Flushed *StreamFlushed `protobuf:"bytes,9,opt,name=flushed,proto3,oneof"` // channel ("log"), up_to_seq
}

type SupervisionEvent_Heartbeat struct {
	Heartbeat *SupervisionHeartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"` // last_event_seq (journal lag)
}

func (*SupervisionEvent_Spawned) isSupervisionEvent_Kind() {}

func (*SupervisionEvent_Exited) isSupervisionEvent_Kind() {}

func (*SupervisionEvent_Crash) isSupervisionEvent_Kind() {}

func (*SupervisionEvent_Flushed) isSupervisionEvent_Kind() {}

func (*SupervisionEvent_Heartbeat) isSupervisionEvent_Kind() {}

type ProcessSpawned struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Adapter binary path or image reference the peer spawned.
	Binary string `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	// Digest of the adapter artifact (OCI digest or content hash).
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// Adapter-reported version string.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// OS process id of the spawned adapter.
	Pid           int32 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSpawned) Reset() {
	*x = ProcessSpawned{}
	mi := &file_criteria_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSpawned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSpawned) ProtoMessage() {}

func (x *ProcessSpawned) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSpawned.ProtoReflect.Descriptor instead.
func (*ProcessSpawned) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessSpawned) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *ProcessSpawned) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ProcessSpawned) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProcessSpawned) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessExited struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OS exit code, or -1 when the process was killed by a signal.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Terminating signal number, or 0 for a normal exit.
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// Idle window (ms) between the peer's last streamed event and the exit.
	IdleMs uint64 `protobuf:"varint,3,opt,name=idle_ms,json=idleMs,proto3" json:"idle_ms,omitempty"`
	// True when the exit was graceful (clean shutdown or explicit kill).
	Graceful      bool `protobuf:"varint,4,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessExited) Reset() {
	*x = ProcessExited{}
	mi := &file_criteria_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExited) ProtoMessage() {}

func (x *ProcessExited) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExited.ProtoReflect.Descriptor instead.
func (*ProcessExited) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ProcessExited) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *ProcessExited) GetIdleMs() uint64 {
	if x != nil {
		return x.IdleMs
	}
	return 0
}

func (x *ProcessExited) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

// CrashClassified carries the peer's classification of a crash. `reason` is
// one of the shared crash-reason strings (single source of truth: the
// exported const set in the host's internal/adapterhost crash taxonomy);
// both host crash mapping and peer emission consume that same set.
type CrashClassified struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// Human-readable detail (underlying error text, diagnostics).
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashClassified) Reset() {
	*x = CrashClassified{}
	mi := &file_criteria_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashClassified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashClassified) ProtoMessage() {}

func (x *CrashClassified) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashClassified.ProtoReflect.Descriptor instead.
func (*CrashClassified) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{4}
}

func (x *CrashClassified) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CrashClassified) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type StreamFlushed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream channel that flushed; "log" for the log stream.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Sequence up to which the channel was flushed; monotonic per channel.
	UpToSeq       uint64 `protobuf:"varint,2,opt,name=up_to_seq,json=upToSeq,proto3" json:"up_to_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlushed) Reset() {
	*x = StreamFlushed{}
	mi := &file_criteria_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlushed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlushed) ProtoMessage() {}

func (x *StreamFlushed) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlushed.ProtoReflect.Descriptor instead.
func (*StreamFlushed) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{5}
}

func (x *StreamFlushed) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *StreamFlushed) GetUpToSeq() uint64 {
	if x != nil {
		return x.UpToSeq
	}
	return 0
}

type SupervisionHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest event_seq the peer has journaled (journal lag probe).
	LastEventSeq  uint64 `protobuf:"varint,1,opt,name=last_event_seq,json=lastEventSeq,proto3" json:"last_event_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisionHeartbeat) Reset() {
	*x = SupervisionHeartbeat{}
	mi := &file_criteria_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisionHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisionHeartbeat) ProtoMessage() {}

func (x *SupervisionHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisionHeartbeat.ProtoReflect.Descriptor instead.
func (*SupervisionHeartbeat) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *SupervisionHeartbeat) GetLastEventSeq() uint64 {
	if x != nil {
		return x.LastEventSeq
	}
	return 0
}

type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ControlRequest_KillChild
	Kind isControlRequest_Kind `protobuf_oneof:"kind"`
	// Process-level subject the control applies to.
	AdapterType string `protobuf:"bytes,2,opt,name=adapter_type,json=adapterType,proto3" json:"adapter_type,omitempty"`
	// "scopeName/scopeInstanceID" or "" (legacy mode).
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// Grace period before the child is force-terminated.
	GraceMs       uint32 `protobuf:"varint,4,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_criteria_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{7}
}

func (x *ControlRequest) GetKind() isControlRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ControlRequest) GetKillChild() *KillChild {
	if x != nil {
		if x, ok := x.Kind.(*ControlRequest_KillChild); ok {
			return x.KillChild
		}
	}
	return nil
}

func (x *ControlRequest) GetAdapterType() string {
	if x != nil {
		return x.AdapterType
	}
	return ""
}

func (x *ControlRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ControlRequest) GetGraceMs() uint32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type isControlRequest_Kind interface {
	isControlRequest_Kind()
}

type ControlRequest_KillChild struct {
	KillChild *KillChild `protobuf:"bytes,1,opt,name=kill_child,json=killChild,proto3,oneof"`
}

func (*ControlRequest_KillChild) isControlRequest_Kind() {}

type ControlResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Acceptance detail or the typed rejection reason.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_criteria_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{8}
}

func (x *ControlResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ControlResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type KillChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillChild) Reset() {
	*x = KillChild{}
	mi := &file_criteria_v1_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillChild) ProtoMessage() {}

func (x *KillChild) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillChild.ProtoReflect.Descriptor instead.
func (*KillChild) Descriptor() ([]byte, []int) {
	return file_criteria_v1_peer_proto_rawDescGZIP(), []int{9}
}

var File_criteria_v1_peer_proto protoreflect.FileDescriptor

const file_criteria_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x16criteria/v1/peer.proto\x12\vcriteria.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x12SupervisionRequest\x12&\n" +
	"\x0fsince_event_seq\x18\x01 \x01(\x04R\rsinceEventSeq\"\xdb\x03\n" +
	"\x10SupervisionEvent\x12\x1b\n" +
	"\tevent_seq\x18\x01 \x01(\x04R\beventSeq\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12!\n" +
	"\fadapter_type\x18\x03 \x01(\tR\vadapterType\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x127\n" +
	"\aspawned\x18\x06 \x01(\v2\x1b.criteria.v1.ProcessSpawnedH\x00R\aspawned\x124\n" +
	"\x06exited\x18\a \x01(\v2\x1a.criteria.v1.ProcessExitedH\x00R\x06exited\x124\n" +
	"\x05crash\x18\b \x01(\v2\x1c.criteria.v1.CrashClassifiedH\x00R\x05crash\x126\n" +
	"\aflushed\x18\t \x01(\v2\x1a.criteria.v1.StreamFlushedH\x00R\aflushed\x12A\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2!.criteria.v1.SupervisionHeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04kind\"l\n" +
	"\x0eProcessSpawned\x12\x16\n" +
	"\x06binary\x18\x01 \x01(\tR\x06binary\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\"y\n" +
	"\rProcessExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\x12\x17\n" +
	"\aidle_ms\x18\x03 \x01(\x04R\x06idleMs\x12\x1a\n" +
	"\bgraceful\x18\x04 \x01(\bR\bgraceful\"A\n" +
	"\x0fCrashClassified\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"E\n" +
	"\rStreamFlushed\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\tup_to_seq\x18\x02 \x01(\x04R\aupToSeq\"<\n" +
	"\x14SupervisionHeartbeat\x12$\n" +
	"\x0elast_event_seq\x18\x01 \x01(\x04R\flastEventSeq\"\xa5\x01\n" +
	"\x0eControlRequest\x127\n" +
	"\n" +
	"kill_child\x18\x01 \x01(\v2\x16.criteria.v1.KillChildH\x00R\tkillChild\x12!\n" +
	"\fadapter_type\x18\x02 \x01(\tR\vadapterType\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x19\n" +
	"\bgrace_ms\x18\x04 \x01(\rR\agraceMsB\x06\n" +
	"\x04kind\"E\n" +
	"\x0fControlResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\v\n" +
	"\tKillChild2\xa2\x01\n" +
	"\vPeerService\x12M\n" +
	"\tSupervise\x12\x1f.criteria.v1.SupervisionRequest\x1a\x1d.criteria.v1.SupervisionEvent0\x01\x12D\n" +
	"\aControl\x12\x1b.criteria.v1.ControlRequest\x1a\x1c.criteria.v1.ControlResponseB>Z<github.com/brokenbots/criteria/sdk/pb/criteria/v1;criteriav1b\x06proto3"

var (
	file_criteria_v1_peer_proto_rawDescOnce sync.Once
	file_criteria_v1_peer_proto_rawDescData []byte
)

func file_criteria_v1_peer_proto_rawDescGZIP() []byte {
	file_criteria_v1_peer_proto_rawDescOnce.Do(func() {
		file_criteria_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteria_v1_peer_proto_rawDesc), len(file_criteria_v1_peer_proto_rawDesc)))
	})
	return file_criteria_v1_peer_proto_rawDescData
}

var file_criteria_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_criteria_v1_peer_proto_goTypes = []any{
	(*SupervisionRequest)(nil),    // 0: criteria.v1.SupervisionRequest
	(*SupervisionEvent)(nil),      // 1: criteria.v1.SupervisionEvent
	(*ProcessSpawned)(nil),        // 2: criteria.v1.ProcessSpawned
	(*ProcessExited)(nil),         // 3: criteria.v1.ProcessExited
	(*CrashClassified)(nil),       // 4: criteria.v1.CrashClassified
	(*StreamFlushed)(nil),         // 5: criteria.v1.StreamFlushed
	(*SupervisionHeartbeat)(nil),  // 6: criteria.v1.SupervisionHeartbeat
	(*ControlRequest)(nil),        // 7: criteria.v1.ControlRequest
	(*ControlResponse)(nil),       // 8: criteria.v1.ControlResponse
	(*KillChild)(nil),             // 9: criteria.v1.KillChild
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_criteria_v1_peer_proto_depIdxs = []int32{
	10, // 0: criteria.v1.SupervisionEvent.at:type_name -> google.protobuf.Timestamp
	2,  // 1: criteria.v1.SupervisionEvent.spawned:type_name -> criteria.v1.ProcessSpawned
	3,  // 2: criteria.v1.SupervisionEvent.exited:type_name -> criteria.v1.ProcessExited
	4,  // 3: criteria.v1.SupervisionEvent.crash:type_name -> criteria.v1.CrashClassified
	5,  // 4: criteria.v1.SupervisionEvent.flushed:type_name -> criteria.v1.StreamFlushed
	6,  // 5: criteria.v1.SupervisionEvent.heartbeat:type_name -> criteria.v1.SupervisionHeartbeat
	9,  // 6: criteria.v1.ControlRequest.kill_child:type_name -> criteria.v1.KillChild
	0,  // 7: criteria.v1.PeerService.Supervise:input_type -> criteria.v1.SupervisionRequest
	7,  // 8: criteria.v1.PeerService.Control:input_type -> criteria.v1.ControlRequest
	1,  // 9: criteria.v1.PeerService.Supervise:output_type -> criteria.v1.SupervisionEvent
	8,  // 10: criteria.v1.PeerService.Control:output_type -> criteria.v1.ControlResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_criteria_v1_peer_proto_init() }
func file_criteria_v1_peer_proto_init() {
	if File_criteria_v1_peer_proto != nil {
		return
	}
	file_criteria_v1_peer_proto_msgTypes[1].OneofWrappers = []any{
		(*SupervisionEvent_Spawned)(nil),
		(*SupervisionEvent_Exited)(nil),
		(*SupervisionEvent_Crash)(nil),
		(*SupervisionEvent_Flushed)(nil),
		(*SupervisionEvent_Heartbeat)(nil),
	}
	file_criteria_v1_peer_proto_msgTypes[7].OneofWrappers = []any{
		(*ControlRequest_KillChild)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v1_peer_proto_rawDesc), len(file_criteria_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteria_v1_peer_proto_goTypes,
		DependencyIndexes: file_criteria_v1_peer_proto_depIdxs,
		MessageInfos:      file_criteria_v1_peer_proto_msgTypes,
	}.Build()
	File_criteria_v1_peer_proto = out.File
	file_criteria_v1_peer_proto_goTypes = nil
	file_criteria_v1_peer_proto_depIdxs = nil
}
