// ServerService — read/control RPCs served by the server and consumed by UI clients
// (and any human tooling such as grpcurl).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: criteria/v1/server.proto

package criteriav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "online" | "offline"
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_criteria_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Agent) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriteriaId    string                 `protobuf:"bytes,1,opt,name=criteria_id,json=criteriaId,proto3" json:"criteria_id,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *ListRunsRequest) GetCriteriaId() string {
	if x != nil {
		return x.CriteriaId
	}
	return ""
}

func (x *ListRunsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"` // exclusive
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunEventsRequest) Reset() {
	*x = ListRunEventsRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunEventsRequest) ProtoMessage() {}

func (x *ListRunEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunEventsRequest.ProtoReflect.Descriptor instead.
func (*ListRunEventsRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *ListRunEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListRunEventsRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *ListRunEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunEventsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Events  []*Envelope            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	LastSeq uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// Continuation cursor. When set, pass this as since_seq in the next call.
	NextSinceSeq  uint64 `protobuf:"varint,3,opt,name=next_since_seq,json=nextSinceSeq,proto3" json:"next_since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunEventsResponse) Reset() {
	*x = ListRunEventsResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunEventsResponse) ProtoMessage() {}

func (x *ListRunEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunEventsResponse.ProtoReflect.Descriptor instead.
func (*ListRunEventsResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *ListRunEventsResponse) GetEvents() []*Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListRunEventsResponse) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ListRunEventsResponse) GetNextSinceSeq() uint64 {
	if x != nil {
		return x.NextSinceSeq
	}
	return 0
}

type WatchRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`            // exclusive; 0 streams from the beginning
	SubscriberId  string                 `protobuf:"bytes,3,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"` // optional durable cursor key scoped by run_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WatchRunRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *WatchRunRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *StopRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ServerTime when the cancel was issued; the run may still take time to
	// observe and react to the cancel.
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *StopRunResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type SendPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptRequest) Reset() {
	*x = SendPromptRequest{}
	mi := &file_criteria_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptRequest) ProtoMessage() {}

func (x *SendPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptRequest.ProtoReflect.Descriptor instead.
func (*SendPromptRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *SendPromptRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SendPromptRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *SendPromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SendPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptResponse) Reset() {
	*x = SendPromptResponse{}
	mi := &file_criteria_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptResponse) ProtoMessage() {}

func (x *SendPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptResponse.ProtoReflect.Descriptor instead.
func (*SendPromptResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *SendPromptResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

var File_criteria_v1_server_proto protoreflect.FileDescriptor

const file_criteria_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x18criteria/v1/server.proto\x12\vcriteria.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18criteria/v1/events.proto\x1a\x1acriteria/v1/criteria.proto\"\xc6\x02\n" +
	"\x05Agent\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x06labels\x18\x03 \x03(\v2\x1e.criteria.v1.Agent.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12<\n" +
	"\flast_seen_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x11ListAgentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"h\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.criteria.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x0fGetAgentRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\"\x7f\n" +
	"\x0fListRunsRequest\x12\x1f\n" +
	"\vcriteria_id\x18\x01 \x01(\tR\n" +
	"criteriaId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"`\n" +
	"\x10ListRunsResponse\x12$\n" +
	"\x04runs\x18\x01 \x03(\v2\x10.criteria.v1.RunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"`\n" +
	"\x14ListRunEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x87\x01\n" +
	"\x15ListRunEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.criteria.v1.EnvelopeR\x06events\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x12$\n" +
	"\x0enext_since_seq\x18\x03 \x01(\x04R\fnextSinceSeq\"j\n" +
	"\x0fWatchRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12#\n" +
	"\rsubscriber_id\x18\x03 \x01(\tR\fsubscriberId\"?\n" +
	"\x0eStopRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x0fStopRunResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"V\n" +
	"\x11SendPromptRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"M\n" +
	"\x12SendPromptResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt2\xcd\x04\n" +
	"\rServerService\x12M\n" +
	"\n" +
	"ListAgents\x12\x1e.criteria.v1.ListAgentsRequest\x1a\x1f.criteria.v1.ListAgentsResponse\x12<\n" +
	"\bGetAgent\x12\x1c.criteria.v1.GetAgentRequest\x1a\x12.criteria.v1.Agent\x12G\n" +
	"\bListRuns\x12\x1c.criteria.v1.ListRunsRequest\x1a\x1d.criteria.v1.ListRunsResponse\x126\n" +
	"\x06GetRun\x12\x1a.criteria.v1.GetRunRequest\x1a\x10.criteria.v1.Run\x12V\n" +
	"\rListRunEvents\x12!.criteria.v1.ListRunEventsRequest\x1a\".criteria.v1.ListRunEventsResponse\x12A\n" +
	"\bWatchRun\x12\x1c.criteria.v1.WatchRunRequest\x1a\x15.criteria.v1.Envelope0\x01\x12D\n" +
	"\aStopRun\x12\x1b.criteria.v1.StopRunRequest\x1a\x1c.criteria.v1.StopRunResponse\x12M\n" +
	"\n" +
	"SendPrompt\x12\x1e.criteria.v1.SendPromptRequest\x1a\x1f.criteria.v1.SendPromptResponseB>Z<github.com/brokenbots/criteria/sdk/pb/criteria/v1;criteriav1b\x06proto3"

var (
	file_criteria_v1_server_proto_rawDescOnce sync.Once
	file_criteria_v1_server_proto_rawDescData []byte
)

func file_criteria_v1_server_proto_rawDescGZIP() []byte {
	file_criteria_v1_server_proto_rawDescOnce.Do(func() {
		file_criteria_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteria_v1_server_proto_rawDesc), len(file_criteria_v1_server_proto_rawDesc)))
	})
	return file_criteria_v1_server_proto_rawDescData
}

var file_criteria_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_criteria_v1_server_proto_goTypes = []any{
	(*Agent)(nil),                 // 0: criteria.v1.Agent
	(*ListAgentsRequest)(nil),     // 1: criteria.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 2: criteria.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),       // 3: criteria.v1.GetAgentRequest
	(*ListRunsRequest)(nil),       // 4: criteria.v1.ListRunsRequest
	(*ListRunsResponse)(nil),      // 5: criteria.v1.ListRunsResponse
	(*GetRunRequest)(nil),         // 6: criteria.v1.GetRunRequest
	(*ListRunEventsRequest)(nil),  // 7: criteria.v1.ListRunEventsRequest
	(*ListRunEventsResponse)(nil), // 8: criteria.v1.ListRunEventsResponse
	(*WatchRunRequest)(nil),       // 9: criteria.v1.WatchRunRequest
	(*StopRunRequest)(nil),        // 10: criteria.v1.StopRunRequest
	(*StopRunResponse)(nil),       // 11: criteria.v1.StopRunResponse
	(*SendPromptRequest)(nil),     // 12: criteria.v1.SendPromptRequest
	(*SendPromptResponse)(nil),    // 13: criteria.v1.SendPromptResponse
	nil,                           // 14: criteria.v1.Agent.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*Run)(nil),                   // 16: criteria.v1.Run
	(*Envelope)(nil),              // 17: criteria.v1.Envelope
}
var file_criteria_v1_server_proto_depIdxs = []int32{
	14, // 0: criteria.v1.Agent.labels:type_name -> criteria.v1.Agent.LabelsEntry
	15, // 1: criteria.v1.Agent.registered_at:type_name -> google.protobuf.Timestamp
	15, // 2: criteria.v1.Agent.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 3: criteria.v1.ListAgentsResponse.agents:type_name -> criteria.v1.Agent
	16, // 4: criteria.v1.ListRunsResponse.runs:type_name -> criteria.v1.Run
	17, // 5: criteria.v1.ListRunEventsResponse.events:type_name -> criteria.v1.Envelope
	15, // 6: criteria.v1.StopRunResponse.issued_at:type_name -> google.protobuf.Timestamp
	15, // 7: criteria.v1.SendPromptResponse.issued_at:type_name -> google.protobuf.Timestamp
	1,  // 8: criteria.v1.ServerService.ListAgents:input_type -> criteria.v1.ListAgentsRequest
	3,  // 9: criteria.v1.ServerService.GetAgent:input_type -> criteria.v1.GetAgentRequest
	4,  // 10: criteria.v1.ServerService.ListRuns:input_type -> criteria.v1.ListRunsRequest
	6,  // 11: criteria.v1.ServerService.GetRun:input_type -> criteria.v1.GetRunRequest
	7,  // 12: criteria.v1.ServerService.ListRunEvents:input_type -> criteria.v1.ListRunEventsRequest
	9,  // 13: criteria.v1.ServerService.WatchRun:input_type -> criteria.v1.WatchRunRequest
	10, // 14: criteria.v1.ServerService.StopRun:input_type -> criteria.v1.StopRunRequest
	12, // 15: criteria.v1.ServerService.SendPrompt:input_type -> criteria.v1.SendPromptRequest
	2,  // 16: criteria.v1.ServerService.ListAgents:output_type -> criteria.v1.ListAgentsResponse
	0,  // 17: criteria.v1.ServerService.GetAgent:output_type -> criteria.v1.Agent
	5,  // 18: criteria.v1.ServerService.ListRuns:output_type -> criteria.v1.ListRunsResponse
	16, // 19: criteria.v1.ServerService.GetRun:output_type -> criteria.v1.Run
	8,  // 20: criteria.v1.ServerService.ListRunEvents:output_type -> criteria.v1.ListRunEventsResponse
	17, // 21: criteria.v1.ServerService.WatchRun:output_type -> criteria.v1.Envelope
	11, // 22: criteria.v1.ServerService.StopRun:output_type -> criteria.v1.StopRunResponse
	13, // 23: criteria.v1.ServerService.SendPrompt:output_type -> criteria.v1.SendPromptResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_criteria_v1_server_proto_init() }
func file_criteria_v1_server_proto_init() {
	if File_criteria_v1_server_proto != nil {
		return
	}
	file_criteria_v1_events_proto_init()
	file_criteria_v1_criteria_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v1_server_proto_rawDesc), len(file_criteria_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteria_v1_server_proto_goTypes,
		DependencyIndexes: file_criteria_v1_server_proto_depIdxs,
		MessageInfos:      file_criteria_v1_server_proto_msgTypes,
	}.Build()
	File_criteria_v1_server_proto = out.File
	file_criteria_v1_server_proto_goTypes = nil
	file_criteria_v1_server_proto_depIdxs = nil
}
