// OverseerService — RPCs served by Castle and consumed by Overseer.
//
// Authentication: all RPCs except `Register` require a token (Bearer header,
// `X-Overseer-Token` header, or `overseer-token` Connect metadata). Tokens are
// SHA-256 compared against `overseers.token_hash` in the orchestrator store.
//
// Caller ownership: mutating RPCs enforce that the authenticated caller owns
// the affected overseer or run. Implementations MUST enforce this contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: overseer/v1/overseer.proto

package overseerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Friendly name for the Overseer instance.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Free-form labels (e.g. "host=laptop", "os=darwin").
	Labels        map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	OverseerId string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	// One-time token. Clients should persist this securely and send it on all
	// subsequent RPCs.
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type CreateRunRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	OverseerId   string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	WorkflowName string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	// Hash of the compiled workflow; used by Castle for de-duplication/tracing.
	WorkflowHash  string `protobuf:"bytes,3,opt,name=workflow_hash,json=workflowHash,proto3" json:"workflow_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRunRequest) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *CreateRunRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *CreateRunRequest) GetWorkflowHash() string {
	if x != nil {
		return x.WorkflowHash
	}
	return ""
}

// Run is the persisted record of a run (mirrors Phase 0 REST DTO).
type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OverseerId    string                 `protobuf:"bytes,2,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	WorkflowHash  string                 `protobuf:"bytes,4,opt,name=workflow_hash,json=workflowHash,proto3" json:"workflow_hash,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "running" | "succeeded" | "failed" | "cancelled"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	FinalState    string                 `protobuf:"bytes,9,opt,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`
	FailureReason string                 `protobuf:"bytes,10,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{5}
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *Run) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *Run) GetWorkflowHash() string {
	if x != nil {
		return x.WorkflowHash
	}
	return ""
}

func (x *Run) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Run) GetFinalState() string {
	if x != nil {
		return x.FinalState
	}
	return ""
}

func (x *Run) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// ReattachRunRequest is sent by an Overseer on startup to query the state of
// a run it believes was in-flight before a crash.
type ReattachRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OverseerId    string                 `protobuf:"bytes,2,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReattachRunRequest) Reset() {
	*x = ReattachRunRequest{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReattachRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReattachRunRequest) ProtoMessage() {}

func (x *ReattachRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReattachRunRequest.ProtoReflect.Descriptor instead.
func (*ReattachRunRequest) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{6}
}

func (x *ReattachRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReattachRunRequest) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

// ReattachRunResponse tells the Overseer whether it may resume a run.
type ReattachRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status of the run: "running" | "paused" | "succeeded" | "failed" | "cancelled".
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Empty when the run is terminal.
	CurrentStep string `protobuf:"bytes,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	// Last started attempt for current_step. 0 if no attempt has been recorded.
	Attempt int32 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Last persisted envelope seq for the run.
	LastSeq uint64 `protobuf:"varint,4,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// Server's judgment: false when the run is terminal or belongs to a different
	// overseer.
	CanResume bool `protobuf:"varint,5,opt,name=can_resume,json=canResume,proto3" json:"can_resume,omitempty"`
	// JSON-encoded variable scope snapshot at the time of the last persisted
	// StepOutputCaptured or VariableSet event. Empty string means no scope has
	// been persisted yet. Field is permanent (W04).
	VariableScope string `protobuf:"bytes,6,opt,name=variable_scope,json=variableScope,proto3" json:"variable_scope,omitempty"` // permanent (W04)
	// pending_signal is the signal name the run is waiting for when status="paused".
	// The Overseer must re-enter the wait/approval node with this value set in
	// RunState so it immediately re-issues ErrPaused (waiting for the signal
	// to arrive via Resume). Empty when not paused. Permanent (W05).
	PendingSignal string `protobuf:"bytes,7,opt,name=pending_signal,json=pendingSignal,proto3" json:"pending_signal,omitempty"` // permanent (W05)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReattachRunResponse) Reset() {
	*x = ReattachRunResponse{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReattachRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReattachRunResponse) ProtoMessage() {}

func (x *ReattachRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReattachRunResponse.ProtoReflect.Descriptor instead.
func (*ReattachRunResponse) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{7}
}

func (x *ReattachRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReattachRunResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *ReattachRunResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReattachRunResponse) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ReattachRunResponse) GetCanResume() bool {
	if x != nil {
		return x.CanResume
	}
	return false
}

func (x *ReattachRunResponse) GetVariableScope() string {
	if x != nil {
		return x.VariableScope
	}
	return ""
}

func (x *ReattachRunResponse) GetPendingSignal() string {
	if x != nil {
		return x.PendingSignal
	}
	return ""
}

// Ack is the server's reply on SubmitEvents. One Ack per persisted Envelope.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ack) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ControlSubscribeRequest is the single message an Overseer sends to open the
// Control server-stream.
type ControlSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlSubscribeRequest) Reset() {
	*x = ControlSubscribeRequest{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlSubscribeRequest) ProtoMessage() {}

func (x *ControlSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlSubscribeRequest.ProtoReflect.Descriptor instead.
func (*ControlSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{9}
}

func (x *ControlSubscribeRequest) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

// ControlMessage is a command from the orchestrator to a connected Overseer.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ControlMessage_RunCancel
	//	*ControlMessage_AgentPrompt
	//	*ControlMessage_ControlReady
	//	*ControlMessage_ResumeRun
	Command       isControlMessage_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{10}
}

func (x *ControlMessage) GetCommand() isControlMessage_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlMessage) GetRunCancel() *RunCancel {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_RunCancel); ok {
			return x.RunCancel
		}
	}
	return nil
}

func (x *ControlMessage) GetAgentPrompt() *AgentPrompt {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_AgentPrompt); ok {
			return x.AgentPrompt
		}
	}
	return nil
}

func (x *ControlMessage) GetControlReady() *ControlReady {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_ControlReady); ok {
			return x.ControlReady
		}
	}
	return nil
}

func (x *ControlMessage) GetResumeRun() *ResumeRun {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_ResumeRun); ok {
			return x.ResumeRun
		}
	}
	return nil
}

type isControlMessage_Command interface {
	isControlMessage_Command()
}

type ControlMessage_RunCancel struct {
	RunCancel *RunCancel `protobuf:"bytes,1,opt,name=run_cancel,json=runCancel,proto3,oneof"`
}

type ControlMessage_AgentPrompt struct {
	AgentPrompt *AgentPrompt `protobuf:"bytes,2,opt,name=agent_prompt,json=agentPrompt,proto3,oneof"` // Phase 2.3; stub in 1.1.
}

type ControlMessage_ControlReady struct {
	// ControlReady is sent once, immediately after the server accepts the
	// Control subscription. It flushes the response headers so the Connect
	// client's call returns to the caller, and signals that subsequent
	// ControlMessages can be delivered. Clients must ignore it.
	ControlReady *ControlReady `protobuf:"bytes,3,opt,name=control_ready,json=controlReady,proto3,oneof"`
}

type ControlMessage_ResumeRun struct {
	// ResumeRun delivers a resume signal from the orchestrator to the Overseer
	// that owns the run. The Overseer should re-enter the paused node with the
	// supplied payload. Permanent (W05).
	ResumeRun *ResumeRun `protobuf:"bytes,4,opt,name=resume_run,json=resumeRun,proto3,oneof"` // permanent (W05)
}

func (*ControlMessage_RunCancel) isControlMessage_Command() {}

func (*ControlMessage_AgentPrompt) isControlMessage_Command() {}

func (*ControlMessage_ControlReady) isControlMessage_Command() {}

func (*ControlMessage_ResumeRun) isControlMessage_Command() {}

// RunCancel asks the Overseer to cancel an in-flight run.
type RunCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCancel) Reset() {
	*x = RunCancel{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCancel) ProtoMessage() {}

func (x *RunCancel) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCancel.ProtoReflect.Descriptor instead.
func (*RunCancel) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{11}
}

func (x *RunCancel) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AgentPrompt forwards a user prompt to a running agent step. Phase 2.3.
type AgentPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPrompt) Reset() {
	*x = AgentPrompt{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPrompt) ProtoMessage() {}

func (x *AgentPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPrompt.ProtoReflect.Descriptor instead.
func (*AgentPrompt) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{12}
}

func (x *AgentPrompt) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentPrompt) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *AgentPrompt) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// ControlReady is an attach acknowledgement sent once at stream start.
// It carries no payload.
type ControlReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlReady) Reset() {
	*x = ControlReady{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReady) ProtoMessage() {}

func (x *ControlReady) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReady.ProtoReflect.Descriptor instead.
func (*ControlReady) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{13}
}

// ResumeRun delivers a resume signal from the orchestrator to the Overseer (W05).
// The Overseer should re-enter the paused wait/approval node with the supplied
// payload and continue execution.
type ResumeRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// signal matches the run's pending_signal; the Overseer should verify this.
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// payload carries decision metadata (e.g. {"decision":"approved","actor":"alice"}).
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRun) Reset() {
	*x = ResumeRun{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRun) ProtoMessage() {}

func (x *ResumeRun) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRun.ProtoReflect.Descriptor instead.
func (*ResumeRun) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResumeRun) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ResumeRun) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ResumeRequest delivers a named signal (or an approval decision) to a paused
// run. This message is SDK contract surface: avoid orchestrator-specific names.
type ResumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// signal is the name of the pending signal to satisfy. For wait nodes with
	// signal=<name> this is that signal name. For approval nodes this is the
	// approval node name.
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// payload carries optional key/value metadata.
	// For approval: payload["decision"] = "approved" | "rejected"
	//
	//	payload["actor"]    = identity of approver (audit metadata).
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResumeRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ResumeRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ResumeResponse reports whether the Resume RPC was accepted.
type ResumeResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reason is one of: "ok" | "run_not_paused" | "signal_mismatch" | "no_pending_signal"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_overseer_v1_overseer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_v1_overseer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_overseer_v1_overseer_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResumeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_overseer_v1_overseer_proto protoreflect.FileDescriptor

const file_overseer_v1_overseer_proto_rawDesc = "" +
	"\n" +
	"\x1aoverseer/v1/overseer.proto\x12\voverseer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18overseer/v1/events.proto\"\xa2\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\x06labels\x18\x02 \x03(\v2(.overseer.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\"P\n" +
	"\x11HeartbeatResponse\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"}\n" +
	"\x10CreateRunRequest\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12#\n" +
	"\rworkflow_hash\x18\x03 \x01(\tR\fworkflowHash\"\x94\x03\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\voverseer_id\x18\x02 \x01(\tR\n" +
	"overseerId\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x12#\n" +
	"\rworkflow_hash\x18\x04 \x01(\tR\fworkflowHash\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1f\n" +
	"\vfinal_state\x18\t \x01(\tR\n" +
	"finalState\x12%\n" +
	"\x0efailure_reason\x18\n" +
	" \x01(\tR\rfailureReason\"L\n" +
	"\x12ReattachRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\voverseer_id\x18\x02 \x01(\tR\n" +
	"overseerId\"\xf2\x01\n" +
	"\x13ReattachRunResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x02 \x01(\tR\vcurrentStep\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x19\n" +
	"\blast_seq\x18\x04 \x01(\x04R\alastSeq\x12\x1d\n" +
	"\n" +
	"can_resume\x18\x05 \x01(\bR\tcanResume\x12%\n" +
	"\x0evariable_scope\x18\x06 \x01(\tR\rvariableScope\x12%\n" +
	"\x0epending_signal\x18\a \x01(\tR\rpendingSignal\"U\n" +
	"\x03Ack\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\":\n" +
	"\x17ControlSubscribeRequest\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\"\x8e\x02\n" +
	"\x0eControlMessage\x127\n" +
	"\n" +
	"run_cancel\x18\x01 \x01(\v2\x16.overseer.v1.RunCancelH\x00R\trunCancel\x12=\n" +
	"\fagent_prompt\x18\x02 \x01(\v2\x18.overseer.v1.AgentPromptH\x00R\vagentPrompt\x12@\n" +
	"\rcontrol_ready\x18\x03 \x01(\v2\x19.overseer.v1.ControlReadyH\x00R\fcontrolReady\x127\n" +
	"\n" +
	"resume_run\x18\x04 \x01(\v2\x16.overseer.v1.ResumeRunH\x00R\tresumeRunB\t\n" +
	"\acommand\":\n" +
	"\tRunCancel\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"P\n" +
	"\vAgentPrompt\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"\x0e\n" +
	"\fControlReady\"\xb5\x01\n" +
	"\tResumeRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12=\n" +
	"\apayload\x18\x03 \x03(\v2#.overseer.v1.ResumeRun.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\rResumeRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12A\n" +
	"\apayload\x18\x03 \x03(\v2'.overseer.v1.ResumeRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eResumeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x86\x04\n" +
	"\x0fOverseerService\x12G\n" +
	"\bRegister\x12\x1c.overseer.v1.RegisterRequest\x1a\x1d.overseer.v1.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.overseer.v1.HeartbeatRequest\x1a\x1e.overseer.v1.HeartbeatResponse\x12<\n" +
	"\tCreateRun\x12\x1d.overseer.v1.CreateRunRequest\x1a\x10.overseer.v1.Run\x12P\n" +
	"\vReattachRun\x12\x1f.overseer.v1.ReattachRunRequest\x1a .overseer.v1.ReattachRunResponse\x12A\n" +
	"\x06Resume\x12\x1a.overseer.v1.ResumeRequest\x1a\x1b.overseer.v1.ResumeResponse\x12;\n" +
	"\fSubmitEvents\x12\x15.overseer.v1.Envelope\x1a\x10.overseer.v1.Ack(\x010\x01\x12N\n" +
	"\aControl\x12$.overseer.v1.ControlSubscribeRequest\x1a\x1b.overseer.v1.ControlMessage0\x01B>Z<github.com/brokenbots/overseer/sdk/pb/overseer/v1;overseerv1b\x06proto3"

var (
	file_overseer_v1_overseer_proto_rawDescOnce sync.Once
	file_overseer_v1_overseer_proto_rawDescData []byte
)

func file_overseer_v1_overseer_proto_rawDescGZIP() []byte {
	file_overseer_v1_overseer_proto_rawDescOnce.Do(func() {
		file_overseer_v1_overseer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overseer_v1_overseer_proto_rawDesc), len(file_overseer_v1_overseer_proto_rawDesc)))
	})
	return file_overseer_v1_overseer_proto_rawDescData
}

var file_overseer_v1_overseer_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_overseer_v1_overseer_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: overseer.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 1: overseer.v1.RegisterResponse
	(*HeartbeatRequest)(nil),        // 2: overseer.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: overseer.v1.HeartbeatResponse
	(*CreateRunRequest)(nil),        // 4: overseer.v1.CreateRunRequest
	(*Run)(nil),                     // 5: overseer.v1.Run
	(*ReattachRunRequest)(nil),      // 6: overseer.v1.ReattachRunRequest
	(*ReattachRunResponse)(nil),     // 7: overseer.v1.ReattachRunResponse
	(*Ack)(nil),                     // 8: overseer.v1.Ack
	(*ControlSubscribeRequest)(nil), // 9: overseer.v1.ControlSubscribeRequest
	(*ControlMessage)(nil),          // 10: overseer.v1.ControlMessage
	(*RunCancel)(nil),               // 11: overseer.v1.RunCancel
	(*AgentPrompt)(nil),             // 12: overseer.v1.AgentPrompt
	(*ControlReady)(nil),            // 13: overseer.v1.ControlReady
	(*ResumeRun)(nil),               // 14: overseer.v1.ResumeRun
	(*ResumeRequest)(nil),           // 15: overseer.v1.ResumeRequest
	(*ResumeResponse)(nil),          // 16: overseer.v1.ResumeResponse
	nil,                             // 17: overseer.v1.RegisterRequest.LabelsEntry
	nil,                             // 18: overseer.v1.ResumeRun.PayloadEntry
	nil,                             // 19: overseer.v1.ResumeRequest.PayloadEntry
	(*timestamppb.Timestamp)(nil),   // 20: google.protobuf.Timestamp
	(*Envelope)(nil),                // 21: overseer.v1.Envelope
}
var file_overseer_v1_overseer_proto_depIdxs = []int32{
	17, // 0: overseer.v1.RegisterRequest.labels:type_name -> overseer.v1.RegisterRequest.LabelsEntry
	20, // 1: overseer.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	20, // 2: overseer.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: overseer.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	20, // 4: overseer.v1.Run.ended_at:type_name -> google.protobuf.Timestamp
	11, // 5: overseer.v1.ControlMessage.run_cancel:type_name -> overseer.v1.RunCancel
	12, // 6: overseer.v1.ControlMessage.agent_prompt:type_name -> overseer.v1.AgentPrompt
	13, // 7: overseer.v1.ControlMessage.control_ready:type_name -> overseer.v1.ControlReady
	14, // 8: overseer.v1.ControlMessage.resume_run:type_name -> overseer.v1.ResumeRun
	18, // 9: overseer.v1.ResumeRun.payload:type_name -> overseer.v1.ResumeRun.PayloadEntry
	19, // 10: overseer.v1.ResumeRequest.payload:type_name -> overseer.v1.ResumeRequest.PayloadEntry
	0,  // 11: overseer.v1.OverseerService.Register:input_type -> overseer.v1.RegisterRequest
	2,  // 12: overseer.v1.OverseerService.Heartbeat:input_type -> overseer.v1.HeartbeatRequest
	4,  // 13: overseer.v1.OverseerService.CreateRun:input_type -> overseer.v1.CreateRunRequest
	6,  // 14: overseer.v1.OverseerService.ReattachRun:input_type -> overseer.v1.ReattachRunRequest
	15, // 15: overseer.v1.OverseerService.Resume:input_type -> overseer.v1.ResumeRequest
	21, // 16: overseer.v1.OverseerService.SubmitEvents:input_type -> overseer.v1.Envelope
	9,  // 17: overseer.v1.OverseerService.Control:input_type -> overseer.v1.ControlSubscribeRequest
	1,  // 18: overseer.v1.OverseerService.Register:output_type -> overseer.v1.RegisterResponse
	3,  // 19: overseer.v1.OverseerService.Heartbeat:output_type -> overseer.v1.HeartbeatResponse
	5,  // 20: overseer.v1.OverseerService.CreateRun:output_type -> overseer.v1.Run
	7,  // 21: overseer.v1.OverseerService.ReattachRun:output_type -> overseer.v1.ReattachRunResponse
	16, // 22: overseer.v1.OverseerService.Resume:output_type -> overseer.v1.ResumeResponse
	8,  // 23: overseer.v1.OverseerService.SubmitEvents:output_type -> overseer.v1.Ack
	10, // 24: overseer.v1.OverseerService.Control:output_type -> overseer.v1.ControlMessage
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_overseer_v1_overseer_proto_init() }
func file_overseer_v1_overseer_proto_init() {
	if File_overseer_v1_overseer_proto != nil {
		return
	}
	file_overseer_v1_events_proto_init()
	file_overseer_v1_overseer_proto_msgTypes[10].OneofWrappers = []any{
		(*ControlMessage_RunCancel)(nil),
		(*ControlMessage_AgentPrompt)(nil),
		(*ControlMessage_ControlReady)(nil),
		(*ControlMessage_ResumeRun)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overseer_v1_overseer_proto_rawDesc), len(file_overseer_v1_overseer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_overseer_v1_overseer_proto_goTypes,
		DependencyIndexes: file_overseer_v1_overseer_proto_depIdxs,
		MessageInfos:      file_overseer_v1_overseer_proto_msgTypes,
	}.Build()
	File_overseer_v1_overseer_proto = out.File
	file_overseer_v1_overseer_proto_goTypes = nil
	file_overseer_v1_overseer_proto_depIdxs = nil
}
