package cli

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	pb "github.com/brokenbots/criteria/sdk/pb/criteria/v1"

	"github.com/brokenbots/criteria/internal/engine"
	"github.com/brokenbots/criteria/internal/run"
)

// waitForControlEndpoint polls stateDir for the first run's control.json and
// returns the loopback listener address. Run ids are generated by apply, so
// the caller discovers them via the published control endpoint record.
func waitForControlEndpoint(t *testing.T, stateDir string) string {
	t.Helper()
	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		addr, _, ok := findRunWithControlEndpoint(t, stateDir)
		if ok {
			return addr
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatalf("control endpoint record under %s not published within 15s", stateDir)
	return ""
}

// findRunWithControlEndpoint scans stateDir's runs dir for a run directory
// publishing its control endpoint; the runs dir also holds flat
// <runID>.json records that must be skipped.
func findRunWithControlEndpoint(t *testing.T, stateDir string) (addr, runID string, found bool) {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(stateDir, "runs"))
	if err != nil {
		return "", "", false
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		runID := e.Name()
		if addr, err := LocalControlEndpoint(runID); err == nil && addr != "" {
			return addr, runID, true
		}
	}
	return "", "", false
}

// runApplyAsync runs runApply in a goroutine and returns a channel that
// receives its terminal error, so the test can interact with the run's
// control listener while it executes.
func runApplyAsync(opts *applyOptions) <-chan error {
	errCh := make(chan error, 1)
	go func() {
		defer func() {
			if r := recover(); r != nil {
				errCh <- fmt.Errorf("apply panicked: %v", r)
			}
		}()
		errCh <- runApply(context.Background(), *opts)
	}()
	return errCh
}

// resolveApproval delivers a decision over the run's loopback control
// listener (the CRI-255 primary surface).
func resolveApproval(t *testing.T, addr, runID, signal string, payload map[string]string) (accepted bool, reason string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	resp, err := localControlServiceClientFor(addr).ResolveResume(ctx, &pb.ResumeRequest{
		RunId:   runID,
		Signal:  signal,
		Payload: payload,
	})
	if err != nil {
		t.Fatalf("ResolveResume over %s: %v", addr, err)
	}
	return resp.Accepted, resp.Reason
}

// runEventsFile reads the run's ND-JSON events and returns the ordered
// payload_type values (LocalSink emits PascalCase names).
func runEventsFile(t *testing.T, stateDir, runID string) []string {
	t.Helper()
	f, err := os.Open(filepath.Join(stateDir, "runs", runID, "events.ndjson"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		t.Fatalf("read events: %v", err)
	}
	defer f.Close()
	var types []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		var env struct {
			PayloadType string `json:"payload_type"`
		}
		if err := json.Unmarshal(sc.Bytes(), &env); err != nil {
			t.Fatalf("decode event line %q: %v", sc.Text(), err)
		}
		types = append(types, env.PayloadType)
	}
	return types
}

// TestApplyLocal_ApprovalResolvedOverLocalControlRPC covers the CRI-255
// acceptance path: a local apply pauses at an approval node with no
// CRITERIA_LOCAL_APPROVAL configured (the once-primary file/env path is
// unused) and the run finishes only after a decision arrives over the run's
// loopback control listener.
func TestApplyLocal_ApprovalResolvedOverLocalControlRPC(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_approval_simple"), tty: func() bool { return false }})

	addr := waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	// An unresolved pause means the run waits; check pause is observable via
	// the control surface before the decision. Then deliver approved.
	accepted, reason := resolveApproval(t, addr, runID, "review", map[string]string{"decision": "approved"})
	if !accepted || reason != "ok" {
		t.Fatalf("ResolveResume = (accepted=%t, reason=%q), want accepted ok", accepted, reason)
	}

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("expected successful run after RPC approval, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after RPC approval")
	}

	// Same event vocabulary as castle runs: an approval pause keeps the
	// richer ApprovalRequested event; resume rides RunResumed.
	evts := runEventsFile(t, stateDir, runID)
	for _, want := range []string{"ApprovalRequested", "RunResumed"} {
		if !containsString(evts, want) {
			t.Errorf("events missing %s; got %v", want, evts)
		}
	}
	// The control record is a startup artifact: it must be gone at teardown.
	if _, sErr := os.Stat(filepath.Join(stateDir, "runs", runID, "control.json")); !os.IsNotExist(sErr) {
		t.Errorf("control.json still present after run end: %v", sErr)
	}
}

// TestApplyLocal_ApprovalRejectedOverLocalControlRPC delivers a rejected
// decision over the RPC surface: the run resolves to the rejected terminal
// state and apply reports a failed run.
func TestApplyLocal_ApprovalRejectedOverLocalControlRPC(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_approval_simple"), tty: func() bool { return false }})

	addr := waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	accepted, reason := resolveApproval(t, addr, runID, "review", map[string]string{"decision": "rejected"})
	if !accepted || reason != "ok" {
		t.Fatalf("ResolveResume = (accepted=%t, reason=%q), want accepted ok", accepted, reason)
	}

	select {
	case err := <-errCh:
		if err == nil {
			t.Fatal("rejected approval: expected non-nil error for terminal failed run")
		}
		if !strings.Contains(err.Error(), "success=false") {
			t.Fatalf("error should report success=false, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after RPC rejection")
	}
}

// TestApplyLocal_SignalWaitResolvedOverLocalControlRPC covers the signal
// wait via the control listener with no resumer configured.
func TestApplyLocal_SignalWaitResolvedOverLocalControlRPC(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_signal_wait"), tty: func() bool { return false }})

	addr := waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	accepted, reason := resolveApproval(t, addr, runID, "proceed", map[string]string{"outcome": "success"})
	if !accepted || reason != "ok" {
		t.Fatalf("ResolveResume = (accepted=%t, reason=%q), want accepted ok", accepted, reason)
	}

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("expected successful run after RPC signal, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after RPC signal")
	}

	evts := runEventsFile(t, stateDir, runID)
	for _, want := range []string{"WaitEntered", "RunResumed"} {
		if !containsString(evts, want) {
			t.Errorf("events missing %s; got %v", want, evts)
		}
	}
}

// TestApplyLocal_UnknownSignalRejectedByRPC exercises the ResolveResume
// rejection reasons while a run is genuinely paused: the pause must be intact
// and the run still completable afterwards (no state corruption from bad
// delivery attempts).
func TestApplyLocal_UnknownSignalRejectedByRPC(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_approval_simple"), tty: func() bool { return false }})

	addr := waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	// An unknown signal name maps to no pending pause.
	if accepted, reason := resolveApproval(t, addr, runID, "nonexistent", nil); accepted || reason != "no_pending_signal" {
		t.Fatalf("unknown signal = (accepted=%t, reason=%q), want no_pending_signal", accepted, reason)
	}
	// A payload missing its decision for the mapped pause is refused without
	// consuming the pause.
	if accepted, reason := resolveApproval(t, addr, runID, "review", nil); accepted || reason != "signal_mismatch" {
		t.Fatalf("empty decision payload = (accepted=%t, reason=%q), want signal_mismatch", accepted, reason)
	}
	if accepted, reason := resolveApproval(t, addr, runID, "review", map[string]string{"decision": "bogus"}); accepted || reason != "signal_mismatch" {
		t.Fatalf("invalid decision = (accepted=%t, reason=%q), want signal_mismatch", accepted, reason)
	}

	// The pause survived; the correct decision resolves it.
	if accepted, reason := resolveApproval(t, addr, runID, "review", map[string]string{"decision": "approved"}); !accepted || reason != "ok" {
		t.Fatalf("ResolveResume after rejections = (accepted=%t, reason=%q), want accepted", accepted, reason)
	}
	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("expected successful run after retries, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after RPC approval")
	}
}

// TestApplyLocal_BoundaryPauseResumeOverLocalControlRPC covers the CRI-255
// boundary pause: PauseRun while a step runs, the run parks at the next
// checkpoint boundary (RunPaused with mode external), and ResumeRun (no
// payload) continues to completion.
func TestApplyLocal_BoundaryPauseResumeOverLocalControlRPC(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_control_pause")})

	addr := waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	client := localControlServiceClientFor(addr)
	if _, err := client.PauseRun(ctx, &pb.PauseRunRequest{RunId: runID}); err != nil {
		t.Fatalf("PauseRun: %v", err)
	}

	if _, err := client.ResumeRun(ctx, &pb.ResumeRunRequest{RunId: runID}); err != nil {
		t.Fatalf("ResumeRun: %v", err)
	}

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("expected successful run after resume, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after ResumeRun")
	}

	// The boundary pause carries the shared vocabulary: mode "external" only.
	var sawPausedExternal, sawResumed bool
	for _, line := range eventLines(t, stateDir, runID) {
		var env struct {
			PayloadType string `json:"payload_type"`
			Payload     struct {
				Mode string `json:"mode"`
			} `json:"payload"`
		}
		if err := json.Unmarshal([]byte(line), &env); err != nil {
			t.Fatalf("decode event: %v", err)
		}
		switch {
		case env.PayloadType == "RunPaused" && env.Payload.Mode == "external":
			sawPausedExternal = true
		case env.PayloadType == "RunResumed":
			sawResumed = true
		}
	}
	if !sawPausedExternal {
		t.Error("events missing RunPaused with mode external")
	}
	if !sawResumed {
		t.Error("events missing RunResumed")
	}
}

// TestPauseResumeCLIVerbsTargetLocalRun pins the CLI verb wiring (CRI-255
// acceptance: pause/resume verbs work against a local run with no castle
// running): both verbs execute as plain cobra commands with no --server flag
// and no CRITERIA_SERVER_URL, discover the run's control listener from
// control.json, and land their effect — the run pauses, then resumes to
// completion with the shared RunPaused/RunResumed event vocabulary.
func TestPauseResumeCLIVerbsTargetLocalRun(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")
	t.Setenv("CRITERIA_SERVER_URL", "")
	t.Setenv("CRITERIA_CONTROL_ADDR", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_control_pause")})

	waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	pauseCmd := NewPauseCmd()
	pauseCmd.SetArgs([]string{"--run-id", runID})
	if err := pauseCmd.Execute(); err != nil {
		t.Fatalf("pause verb against local run: %v", err)
	}

	// The pause verb blocks until the pause lands with durable state; the
	// parked run must carry the same vocabulary the castle path emits.
	if !waitForPayloadType(t, stateDir, runID, "RunPaused") {
		t.Error("events missing RunPaused after the pause verb")
	}

	resumeCmd := NewResumeCmd()
	resumeCmd.SetArgs([]string{"--run-id", runID})
	if err := resumeCmd.Execute(); err != nil {
		t.Fatalf("resume verb against local run: %v", err)
	}

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("expected successful run after the resume verb, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after the resume verb")
	}
	if !containsString(runEventsFile(t, stateDir, runID), "RunResumed") {
		t.Error("events missing RunResumed after the resume verb")
	}
}

// waitForPayloadType polls the run's event stream for a payload type,
// tolerating the async drain between the control RPC and the run-state
// view.
func waitForPayloadType(t *testing.T, stateDir, runID, payloadType string) bool {
	t.Helper()
	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		if containsString(runEventsFile(t, stateDir, runID), payloadType) {
			return true
		}
		time.Sleep(40 * time.Millisecond)
	}
	return false
}

// TestApproveCLIVerbResolvesLocalApproval pins the CLI approval-delivery
// wiring (CRI-255 acceptance: approve delivered over the local RPC resolves
// an approval node): the approve verb executes with only the run id, the
// pending signal, and the decision, resolves the parked approval node, and
// the run completes successfully on the approved route.
func TestApproveCLIVerbResolvesLocalApproval(t *testing.T) {
	adapterDir := filepath.Dir(buildNoopAdapterBinary(t))
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_ADAPTERS", adapterDir)
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	t.Setenv("CRITERIA_LOCAL_APPROVAL", "")
	t.Setenv("CRITERIA_SERVER_URL", "")

	errCh := runApplyAsync(&applyOptions{workflowPath: filepath.Join("testdata", "local_approval_simple"), tty: func() bool { return false }})

	waitForControlEndpoint(t, stateDir)
	runID := singleRunID(t, stateDir)

	approveCmd := NewApproveCmd()
	approveCmd.SetArgs([]string{"--run-id", runID, "--signal", "review", "--decision", "approved", "--actor", "tess"})
	if err := approveCmd.Execute(); err != nil {
		t.Fatalf("approve verb against local run: %v", err)
	}

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("expected successful run after the approve verb, got: %v", err)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("runApply did not return after the approve verb")
	}

	types := runEventsFile(t, stateDir, runID)
	if !containsString(types, "ApprovalDecision") {
		t.Error("events missing ApprovalDecision after the approve verb")
	}
	if !containsString(types, "RunResumed") {
		t.Error("events missing RunResumed after the approve verb")
	}
}

// singleRunID returns the run id of the run whose control endpoint is
// published under stateDir (skipping the flat <runID>.json records).
func singleRunID(t *testing.T, stateDir string) string {
	t.Helper()
	if _, runID, ok := findRunWithControlEndpoint(t, stateDir); ok {
		return runID
	}
	t.Fatalf("no run dir with a control endpoint under %s", stateDir)
	return ""
}

func containsString(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}

func eventLines(t *testing.T, stateDir, runID string) []string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(stateDir, "runs", runID, "events.ndjson"))
	if err != nil {
		t.Fatalf("read events: %v", err)
	}
	var lines []string
	for _, l := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		if l != "" {
			lines = append(lines, l)
		}
	}
	return lines
}

// TestControlEndpointRecord_Roundtrip pins the control.json contract: the
// apply process publishes protocol/addr/run/pid under the run's state dir,
// the CLI discovers it via LocalControlEndpoint, and removing the record
// falls back to the castle surface (empty addr, no error).
func TestControlEndpointRecord_Roundtrip(t *testing.T) {
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_STATE_DIR", stateDir)

	addr, err := LocalControlEndpoint("endpoint-run")
	if err != nil || addr != "" {
		t.Fatalf("before publish: LocalControlEndpoint = (%q, %v), want empty/nil", addr, err)
	}

	if err := writeControlEndpoint("endpoint-run", "127.0.0.1:8123"); err != nil {
		t.Fatalf("writeControlEndpoint: %v", err)
	}
	addr, err = LocalControlEndpoint("endpoint-run")
	if err != nil {
		t.Fatalf("LocalControlEndpoint: %v", err)
	}
	if addr != "127.0.0.1:8123" {
		t.Fatalf("LocalControlEndpoint = %q, want 127.0.0.1:8123", addr)
	}

	// The record must live under the run's existing state dir (no new store).
	if _, statErr := os.Stat(filepath.Join(stateDir, "runs", "endpoint-run", "control.json")); statErr != nil {
		t.Fatalf("control.json not under runs/<runID>: %v", statErr)
	}

	// A foreign run id in the record is rejected (wrong-run reads 403 from the
	// server's checkRun; the CLI must not even dial).
	if err := writeControlEndpoint("other-run", "127.0.0.1:8123"); err != nil {
		t.Fatalf("writeControlEndpoint(other): %v", err)
	}
	if _, err := LocalControlEndpoint("other-run"); err != nil {
		t.Fatalf("LocalControlEndpoint(other): %v", err)
	}

	removeControlEndpoint("endpoint-run")
	addr, err = LocalControlEndpoint("endpoint-run")
	if err != nil || addr != "" {
		t.Fatalf("after remove: LocalControlEndpoint = (%q, %v), want empty/nil", addr, err)
	}
}

// TestControlEndpointRecord_RejectsBadRecords pins the defensive reads in
// LocalControlEndpoint: corrupt JSON, a foreign protocol, a mismatched run id,
// and a non-loopback address all fail closed.
func TestControlEndpointRecord_RejectsBadRecords(t *testing.T) {
	stateDir := t.TempDir()
	t.Setenv("CRITERIA_STATE_DIR", stateDir)
	p, err := controlEndpointPath("bad-record-run")
	if err != nil {
		t.Fatalf("controlEndpointPath: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	for _, tc := range []struct {
		name    string
		body    string
		wantMsg string
	}{
		{"corrupt", "{not json", "decode control endpoint"},
		{"foreign protocol", `{"protocol":"other.v1.Control/connect","control_addr":"127.0.0.1:1","run_id":"bad-record-run","pid":1}`, "this CLI speaks"},
		{"mismatched run id", `{"protocol":"criteria.v1.LocalControlService/connect","control_addr":"127.0.0.1:1","run_id":"someoneelse","pid":1}`, "incomplete"},
		{"missing addr", `{"protocol":"criteria.v1.LocalControlService/connect","control_addr":"","run_id":"bad-record-run","pid":1}`, "incomplete"},
		{"non-loopback", `{"protocol":"criteria.v1.LocalControlService/connect","control_addr":"0.0.0.0:1","run_id":"bad-record-run","pid":1}`, "non-loopback"},
	} {
		if err := os.WriteFile(p, []byte(tc.body), 0o600); err != nil {
			t.Fatalf("write record: %v", err)
		}
		_, err := LocalControlEndpoint("bad-record-run")
		if err == nil || !strings.Contains(err.Error(), tc.wantMsg) {
			t.Errorf("%s: LocalControlEndpoint err = %v, want containing %q", tc.name, err, tc.wantMsg)
		}
	}
}

// TestValidateControlHostPort pins the locked loopback-only rule at the
// validator the apply-side bind and the client-side record both use.
func TestValidateControlHostPort(t *testing.T) {
	for _, good := range []string{"127.0.0.1:9", "[::1]:8123", ":9"} {
		if err := validateControlHostPort(good); err != nil {
			t.Errorf("loopback %q refused: %v", good, err)
		}
	}
	for _, bad := range []string{"0.0.0.0:9", "192.168.1.5:9", "example.com:9", "[::]:9", "999.1.1.1:9", "127.0.0.1"} {
		if err := validateControlHostPort(bad); err == nil {
			t.Errorf("non-loopback/missing-port %q accepted", bad)
		}
	}
}

// TestResolveControlAddr pins --control-addr parsing: empty binds a random
// loopback port, localhost maps to 127.0.0.1, and wide or malformed values
// are refused.
func TestResolveControlAddr(t *testing.T) {
	host, port, err := resolveControlAddr("")
	if err != nil || host != "127.0.0.1" || port != 0 {
		t.Fatalf("default = (%q, %d, %v), want 127.0.0.1:0/nil", host, port, err)
	}
	for _, addr := range []string{"127.0.0.1:9001", "localhost:9001", "[::1]:9001"} {
		host, port, err = resolveControlAddr(addr)
		if err != nil {
			t.Errorf("%q: %v", addr, err)
			continue
		}
		if ip := net.ParseIP(host); ip == nil || !ip.IsLoopback() || port != 9001 {
			t.Errorf("%q resolved to %s:%d, want loopback:9001", addr, host, port)
		}
	}
	for _, addr := range []string{"0.0.0.0:9001", "192.168.1.5:9001", "example.com:9001", "noport", "127.0.0.1:notaport"} {
		if _, _, err := resolveControlAddr(addr); err == nil {
			t.Errorf("%q accepted, want refusal", addr)
		}
	}
}

// TestLocalControlServiceRetryAcrossPauseLanding pins the service-layer
// landing window: control verbs that race the run's start-up (engine not yet
// registered, first pause not yet landed) must succeed once the run reaches
// its registered state within the bounded window instead of answering a hard
// precondition error.
func TestLocalControlServiceRetryAcrossPauseLanding(t *testing.T) {
	requireNoGoroutineLeak(t)
	home := t.TempDir()
	t.Setenv("CRITERIA_STATE_DIR", home)

	wfPath := writeWorkflowFile(t, pauseResumeWorkflow)
	ctx := context.Background()
	_, graph, loader, err := compileForExecution(ctx, wfPath, discardLogger(), false, false)
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	defer func() { _ = loader.Shutdown(context.WithoutCancel(ctx)) }()

	sink := func() *run.LocalSink {
		return &run.LocalSink{RunID: "landing-test", Out: os.Stdout}
	}

	// ResolveResume racing the first pause landing: answered run_not_paused
	// until the pause lands, then accepted by the bounded retry.
	waitTracker := &pauseTracker{Sink: sink()}
	pauseCtrl := newLocalRunControl("landing-test", graph, waitTracker, nil)
	pauseSvc := &localControlService{ctrl: pauseCtrl, runID: "landing-test"}
	pauseReady := make(chan struct{})
	go func() {
		time.Sleep(100 * time.Millisecond)
		pauseCtrl.setEngine(engine.New(graph, loader, sink()))
		waitTracker.OnRunPaused("gate", "signal", "resume")
		close(pauseReady)
	}()
	accepted, reason := pauseSvc.ctrlResolve("resume", nil)
	if !accepted || reason != "ok" {
		t.Fatalf("ctrlResolve racing landing = (%v, %q), want (true, ok)", accepted, reason)
	}
	<-pauseReady

	// ResumeRun racing engine registration: the engine pointer registers
	// 100ms into the retry window; the verb must succeed, not answer
	// errRunNotRunning.
	regTracker := &pauseTracker{Sink: sink()}
	regCtrl := newLocalRunControl("landing-test", graph, regTracker, nil)
	regSvc := &localControlService{ctrl: regCtrl, runID: "landing-test"}
	engineReady := make(chan struct{})
	go func() {
		time.Sleep(100 * time.Millisecond)
		regCtrl.setEngine(engine.New(graph, loader, sink()))
		close(engineReady)
	}()
	if err := regSvc.ctrlResume(); err != nil {
		t.Fatalf("ctrlResume racing registration: %v", err)
	}
	<-engineReady

	// A terminal (finished) run answers immediately, without waiting out
	// the full retry window.
	waitTracker.ClearPaused()
	pauseCtrl.markFinished()
	start := time.Now()
	accepted, reason = pauseSvc.ctrlResolve("resume", nil)
	if accepted || reason != "run_not_paused" {
		t.Fatalf("finished run resolve = (%v, %q), want (false, run_not_paused)", accepted, reason)
	}
	if elapsed := time.Since(start); elapsed >= pauseLandingRetryWindow {
		t.Fatalf("finished run resolve took %v, want fast final answer", elapsed)
	}
}
