// CastleService — read/control RPCs served by Castle and consumed by Parapet
// (and any human tooling such as grpcurl).

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/castle.proto

package overseerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/overseer/sdk/pb/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CastleServiceName is the fully-qualified name of the CastleService service.
	CastleServiceName = "overseer.v1.CastleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CastleServiceListOverseersProcedure is the fully-qualified name of the CastleService's
	// ListOverseers RPC.
	CastleServiceListOverseersProcedure = "/overseer.v1.CastleService/ListOverseers"
	// CastleServiceGetOverseerProcedure is the fully-qualified name of the CastleService's GetOverseer
	// RPC.
	CastleServiceGetOverseerProcedure = "/overseer.v1.CastleService/GetOverseer"
	// CastleServiceListRunsProcedure is the fully-qualified name of the CastleService's ListRuns RPC.
	CastleServiceListRunsProcedure = "/overseer.v1.CastleService/ListRuns"
	// CastleServiceGetRunProcedure is the fully-qualified name of the CastleService's GetRun RPC.
	CastleServiceGetRunProcedure = "/overseer.v1.CastleService/GetRun"
	// CastleServiceListRunEventsProcedure is the fully-qualified name of the CastleService's
	// ListRunEvents RPC.
	CastleServiceListRunEventsProcedure = "/overseer.v1.CastleService/ListRunEvents"
	// CastleServiceWatchRunProcedure is the fully-qualified name of the CastleService's WatchRun RPC.
	CastleServiceWatchRunProcedure = "/overseer.v1.CastleService/WatchRun"
	// CastleServiceStopRunProcedure is the fully-qualified name of the CastleService's StopRun RPC.
	CastleServiceStopRunProcedure = "/overseer.v1.CastleService/StopRun"
	// CastleServiceSendPromptProcedure is the fully-qualified name of the CastleService's SendPrompt
	// RPC.
	CastleServiceSendPromptProcedure = "/overseer.v1.CastleService/SendPrompt"
)

// CastleServiceClient is a client for the overseer.v1.CastleService service.
type CastleServiceClient interface {
	ListOverseers(context.Context, *connect.Request[v1.ListOverseersRequest]) (*connect.Response[v1.ListOverseersResponse], error)
	GetOverseer(context.Context, *connect.Request[v1.GetOverseerRequest]) (*connect.Response[v1.Overseer], error)
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error)
	// ListRunEvents replaces the Phase 0 run-events HTTP endpoint.
	ListRunEvents(context.Context, *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error)
	// WatchRun replaces the Phase 0 run-stream endpoint. Emits any already
	// persisted events (since `since_seq`) and then tails live events until the
	// client disconnects or the run reaches a terminal state.
	WatchRun(context.Context, *connect.Request[v1.WatchRunRequest]) (*connect.ServerStreamForClient[v1.Envelope], error)
	// StopRun cancels a run. If an Overseer is attached to the run via its
	// Control stream, the orchestrator pushes a RunCancel to it. Returns
	// FAILED_PRECONDITION if the Overseer is not connected.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's overseer.
	StopRun(context.Context, *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error)
	// SendPrompt — schema-only stub for Phase 2.3. Parapet can wire up UI
	// against this method, but Castle currently returns UNIMPLEMENTED.
	SendPrompt(context.Context, *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error)
}

// NewCastleServiceClient constructs a client for the overseer.v1.CastleService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCastleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CastleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	castleServiceMethods := v1.File_v1_castle_proto.Services().ByName("CastleService").Methods()
	return &castleServiceClient{
		listOverseers: connect.NewClient[v1.ListOverseersRequest, v1.ListOverseersResponse](
			httpClient,
			baseURL+CastleServiceListOverseersProcedure,
			connect.WithSchema(castleServiceMethods.ByName("ListOverseers")),
			connect.WithClientOptions(opts...),
		),
		getOverseer: connect.NewClient[v1.GetOverseerRequest, v1.Overseer](
			httpClient,
			baseURL+CastleServiceGetOverseerProcedure,
			connect.WithSchema(castleServiceMethods.ByName("GetOverseer")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[v1.ListRunsRequest, v1.ListRunsResponse](
			httpClient,
			baseURL+CastleServiceListRunsProcedure,
			connect.WithSchema(castleServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		getRun: connect.NewClient[v1.GetRunRequest, v1.Run](
			httpClient,
			baseURL+CastleServiceGetRunProcedure,
			connect.WithSchema(castleServiceMethods.ByName("GetRun")),
			connect.WithClientOptions(opts...),
		),
		listRunEvents: connect.NewClient[v1.ListRunEventsRequest, v1.ListRunEventsResponse](
			httpClient,
			baseURL+CastleServiceListRunEventsProcedure,
			connect.WithSchema(castleServiceMethods.ByName("ListRunEvents")),
			connect.WithClientOptions(opts...),
		),
		watchRun: connect.NewClient[v1.WatchRunRequest, v1.Envelope](
			httpClient,
			baseURL+CastleServiceWatchRunProcedure,
			connect.WithSchema(castleServiceMethods.ByName("WatchRun")),
			connect.WithClientOptions(opts...),
		),
		stopRun: connect.NewClient[v1.StopRunRequest, v1.StopRunResponse](
			httpClient,
			baseURL+CastleServiceStopRunProcedure,
			connect.WithSchema(castleServiceMethods.ByName("StopRun")),
			connect.WithClientOptions(opts...),
		),
		sendPrompt: connect.NewClient[v1.SendPromptRequest, v1.SendPromptResponse](
			httpClient,
			baseURL+CastleServiceSendPromptProcedure,
			connect.WithSchema(castleServiceMethods.ByName("SendPrompt")),
			connect.WithClientOptions(opts...),
		),
	}
}

// castleServiceClient implements CastleServiceClient.
type castleServiceClient struct {
	listOverseers *connect.Client[v1.ListOverseersRequest, v1.ListOverseersResponse]
	getOverseer   *connect.Client[v1.GetOverseerRequest, v1.Overseer]
	listRuns      *connect.Client[v1.ListRunsRequest, v1.ListRunsResponse]
	getRun        *connect.Client[v1.GetRunRequest, v1.Run]
	listRunEvents *connect.Client[v1.ListRunEventsRequest, v1.ListRunEventsResponse]
	watchRun      *connect.Client[v1.WatchRunRequest, v1.Envelope]
	stopRun       *connect.Client[v1.StopRunRequest, v1.StopRunResponse]
	sendPrompt    *connect.Client[v1.SendPromptRequest, v1.SendPromptResponse]
}

// ListOverseers calls overseer.v1.CastleService.ListOverseers.
func (c *castleServiceClient) ListOverseers(ctx context.Context, req *connect.Request[v1.ListOverseersRequest]) (*connect.Response[v1.ListOverseersResponse], error) {
	return c.listOverseers.CallUnary(ctx, req)
}

// GetOverseer calls overseer.v1.CastleService.GetOverseer.
func (c *castleServiceClient) GetOverseer(ctx context.Context, req *connect.Request[v1.GetOverseerRequest]) (*connect.Response[v1.Overseer], error) {
	return c.getOverseer.CallUnary(ctx, req)
}

// ListRuns calls overseer.v1.CastleService.ListRuns.
func (c *castleServiceClient) ListRuns(ctx context.Context, req *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// GetRun calls overseer.v1.CastleService.GetRun.
func (c *castleServiceClient) GetRun(ctx context.Context, req *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error) {
	return c.getRun.CallUnary(ctx, req)
}

// ListRunEvents calls overseer.v1.CastleService.ListRunEvents.
func (c *castleServiceClient) ListRunEvents(ctx context.Context, req *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error) {
	return c.listRunEvents.CallUnary(ctx, req)
}

// WatchRun calls overseer.v1.CastleService.WatchRun.
func (c *castleServiceClient) WatchRun(ctx context.Context, req *connect.Request[v1.WatchRunRequest]) (*connect.ServerStreamForClient[v1.Envelope], error) {
	return c.watchRun.CallServerStream(ctx, req)
}

// StopRun calls overseer.v1.CastleService.StopRun.
func (c *castleServiceClient) StopRun(ctx context.Context, req *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error) {
	return c.stopRun.CallUnary(ctx, req)
}

// SendPrompt calls overseer.v1.CastleService.SendPrompt.
func (c *castleServiceClient) SendPrompt(ctx context.Context, req *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error) {
	return c.sendPrompt.CallUnary(ctx, req)
}

// CastleServiceHandler is an implementation of the overseer.v1.CastleService service.
type CastleServiceHandler interface {
	ListOverseers(context.Context, *connect.Request[v1.ListOverseersRequest]) (*connect.Response[v1.ListOverseersResponse], error)
	GetOverseer(context.Context, *connect.Request[v1.GetOverseerRequest]) (*connect.Response[v1.Overseer], error)
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error)
	// ListRunEvents replaces the Phase 0 run-events HTTP endpoint.
	ListRunEvents(context.Context, *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error)
	// WatchRun replaces the Phase 0 run-stream endpoint. Emits any already
	// persisted events (since `since_seq`) and then tails live events until the
	// client disconnects or the run reaches a terminal state.
	WatchRun(context.Context, *connect.Request[v1.WatchRunRequest], *connect.ServerStream[v1.Envelope]) error
	// StopRun cancels a run. If an Overseer is attached to the run via its
	// Control stream, the orchestrator pushes a RunCancel to it. Returns
	// FAILED_PRECONDITION if the Overseer is not connected.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's overseer.
	StopRun(context.Context, *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error)
	// SendPrompt — schema-only stub for Phase 2.3. Parapet can wire up UI
	// against this method, but Castle currently returns UNIMPLEMENTED.
	SendPrompt(context.Context, *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error)
}

// NewCastleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCastleServiceHandler(svc CastleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	castleServiceMethods := v1.File_v1_castle_proto.Services().ByName("CastleService").Methods()
	castleServiceListOverseersHandler := connect.NewUnaryHandler(
		CastleServiceListOverseersProcedure,
		svc.ListOverseers,
		connect.WithSchema(castleServiceMethods.ByName("ListOverseers")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceGetOverseerHandler := connect.NewUnaryHandler(
		CastleServiceGetOverseerProcedure,
		svc.GetOverseer,
		connect.WithSchema(castleServiceMethods.ByName("GetOverseer")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceListRunsHandler := connect.NewUnaryHandler(
		CastleServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(castleServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceGetRunHandler := connect.NewUnaryHandler(
		CastleServiceGetRunProcedure,
		svc.GetRun,
		connect.WithSchema(castleServiceMethods.ByName("GetRun")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceListRunEventsHandler := connect.NewUnaryHandler(
		CastleServiceListRunEventsProcedure,
		svc.ListRunEvents,
		connect.WithSchema(castleServiceMethods.ByName("ListRunEvents")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceWatchRunHandler := connect.NewServerStreamHandler(
		CastleServiceWatchRunProcedure,
		svc.WatchRun,
		connect.WithSchema(castleServiceMethods.ByName("WatchRun")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceStopRunHandler := connect.NewUnaryHandler(
		CastleServiceStopRunProcedure,
		svc.StopRun,
		connect.WithSchema(castleServiceMethods.ByName("StopRun")),
		connect.WithHandlerOptions(opts...),
	)
	castleServiceSendPromptHandler := connect.NewUnaryHandler(
		CastleServiceSendPromptProcedure,
		svc.SendPrompt,
		connect.WithSchema(castleServiceMethods.ByName("SendPrompt")),
		connect.WithHandlerOptions(opts...),
	)
	return "/overseer.v1.CastleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CastleServiceListOverseersProcedure:
			castleServiceListOverseersHandler.ServeHTTP(w, r)
		case CastleServiceGetOverseerProcedure:
			castleServiceGetOverseerHandler.ServeHTTP(w, r)
		case CastleServiceListRunsProcedure:
			castleServiceListRunsHandler.ServeHTTP(w, r)
		case CastleServiceGetRunProcedure:
			castleServiceGetRunHandler.ServeHTTP(w, r)
		case CastleServiceListRunEventsProcedure:
			castleServiceListRunEventsHandler.ServeHTTP(w, r)
		case CastleServiceWatchRunProcedure:
			castleServiceWatchRunHandler.ServeHTTP(w, r)
		case CastleServiceStopRunProcedure:
			castleServiceStopRunHandler.ServeHTTP(w, r)
		case CastleServiceSendPromptProcedure:
			castleServiceSendPromptHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCastleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCastleServiceHandler struct{}

func (UnimplementedCastleServiceHandler) ListOverseers(context.Context, *connect.Request[v1.ListOverseersRequest]) (*connect.Response[v1.ListOverseersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.ListOverseers is not implemented"))
}

func (UnimplementedCastleServiceHandler) GetOverseer(context.Context, *connect.Request[v1.GetOverseerRequest]) (*connect.Response[v1.Overseer], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.GetOverseer is not implemented"))
}

func (UnimplementedCastleServiceHandler) ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.ListRuns is not implemented"))
}

func (UnimplementedCastleServiceHandler) GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.GetRun is not implemented"))
}

func (UnimplementedCastleServiceHandler) ListRunEvents(context.Context, *connect.Request[v1.ListRunEventsRequest]) (*connect.Response[v1.ListRunEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.ListRunEvents is not implemented"))
}

func (UnimplementedCastleServiceHandler) WatchRun(context.Context, *connect.Request[v1.WatchRunRequest], *connect.ServerStream[v1.Envelope]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.WatchRun is not implemented"))
}

func (UnimplementedCastleServiceHandler) StopRun(context.Context, *connect.Request[v1.StopRunRequest]) (*connect.Response[v1.StopRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.StopRun is not implemented"))
}

func (UnimplementedCastleServiceHandler) SendPrompt(context.Context, *connect.Request[v1.SendPromptRequest]) (*connect.Response[v1.SendPromptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.CastleService.SendPrompt is not implemented"))
}
