// OverseerService — RPCs served by Castle and consumed by Overseer.
//
// Authentication: all RPCs except `Register` require a token (Bearer header,
// `X-Overseer-Token` header, or `overseer-token` Connect metadata). Tokens are
// SHA-256 compared against `overseers.token_hash` in the orchestrator store.
//
// Caller ownership: mutating RPCs enforce that the authenticated caller owns
// the affected overseer or run. Implementations MUST enforce this contract.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/overseer.proto

package overseerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/overseer/sdk/pb/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OverseerServiceName is the fully-qualified name of the OverseerService service.
	OverseerServiceName = "overseer.v1.OverseerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OverseerServiceRegisterProcedure is the fully-qualified name of the OverseerService's Register
	// RPC.
	OverseerServiceRegisterProcedure = "/overseer.v1.OverseerService/Register"
	// OverseerServiceHeartbeatProcedure is the fully-qualified name of the OverseerService's Heartbeat
	// RPC.
	OverseerServiceHeartbeatProcedure = "/overseer.v1.OverseerService/Heartbeat"
	// OverseerServiceCreateRunProcedure is the fully-qualified name of the OverseerService's CreateRun
	// RPC.
	OverseerServiceCreateRunProcedure = "/overseer.v1.OverseerService/CreateRun"
	// OverseerServiceReattachRunProcedure is the fully-qualified name of the OverseerService's
	// ReattachRun RPC.
	OverseerServiceReattachRunProcedure = "/overseer.v1.OverseerService/ReattachRun"
	// OverseerServiceResumeProcedure is the fully-qualified name of the OverseerService's Resume RPC.
	OverseerServiceResumeProcedure = "/overseer.v1.OverseerService/Resume"
	// OverseerServiceSubmitEventsProcedure is the fully-qualified name of the OverseerService's
	// SubmitEvents RPC.
	OverseerServiceSubmitEventsProcedure = "/overseer.v1.OverseerService/SubmitEvents"
	// OverseerServiceControlProcedure is the fully-qualified name of the OverseerService's Control RPC.
	OverseerServiceControlProcedure = "/overseer.v1.OverseerService/Control"
)

// OverseerServiceClient is a client for the overseer.v1.OverseerService service.
type OverseerServiceClient interface {
	// Register enrolls an Overseer with the orchestrator. Returns the assigned
	// overseer id and an auth token the Overseer must present on all subsequent
	// RPCs.
	//
	// Bootstrap gate: implementations MUST require a bootstrap token (e.g. via
	// an `X-Castle-Bootstrap` header) before accepting Register. When no
	// bootstrap mechanism is configured, implementations MUST return
	// Unimplemented. This prevents open self-registration in production.
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	// Heartbeat advances the Overseer's `last_seen_at`. The orchestrator marks
	// Overseers offline whose heartbeat is older than a configurable threshold.
	//
	// The authenticated caller's identity is the canonical overseer being
	// updated. Implementations MUST ignore any request-supplied overseer_id and
	// use the caller's authenticated identity instead.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
	// CreateRun mints a new run owned by the authenticated caller. The
	// orchestrator is the sole source of run ids.
	//
	// The run is always recorded under the authenticated caller's overseer ID.
	// The request's `overseer_id` field is informational only. Implementations
	// MUST ignore any request-supplied overseer_id and use the caller's
	// authenticated identity.
	CreateRun(context.Context, *connect.Request[v1.CreateRunRequest]) (*connect.Response[v1.Run], error)
	// ReattachRun lets an Overseer query the orchestrator about an in-flight run
	// after a crash or restart. The orchestrator returns the current status,
	// last active step, and whether the Overseer may resume execution.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's overseer.
	ReattachRun(context.Context, *connect.Request[v1.ReattachRunRequest]) (*connect.Response[v1.ReattachRunResponse], error)
	// Resume delivers a named signal (or an approval decision) to a paused run.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's overseer.
	//
	// This RPC is SDK contract surface: field names, payload semantics, and
	// error-reason strings are stable for third-party orchestrators.
	Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error)
	// SubmitEvents is a bidirectional stream. The client writes Envelopes and
	// the server replies with an Ack per persisted envelope (run_id, seq,
	// correlation_id). On reconnect the client may include `since_seq` in
	// request metadata to request replay of events that were persisted but not
	// yet acknowledged.
	//
	// Implementations MUST verify on every envelope that the authenticated caller
	// owns the envelope's run_id. On the first violation the stream MUST be
	// rejected with PERMISSION_DENIED; envelopes MUST NOT be silently dropped.
	SubmitEvents(context.Context) *connect.BidiStreamForClient[v1.Envelope, v1.Ack]
	// Control is a long-lived server-stream that the orchestrator uses to push
	// commands to a connected Overseer (cancel a run, send a prompt to an
	// agent, ...).
	//
	// The authenticated caller's identity determines the registry key for the
	// Control subscription. Implementations MUST ignore any request-supplied
	// overseer_id and use the caller's authenticated identity.
	Control(context.Context, *connect.Request[v1.ControlSubscribeRequest]) (*connect.ServerStreamForClient[v1.ControlMessage], error)
}

// NewOverseerServiceClient constructs a client for the overseer.v1.OverseerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOverseerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OverseerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	overseerServiceMethods := v1.File_v1_overseer_proto.Services().ByName("OverseerService").Methods()
	return &overseerServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+OverseerServiceRegisterProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatRequest, v1.HeartbeatResponse](
			httpClient,
			baseURL+OverseerServiceHeartbeatProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		createRun: connect.NewClient[v1.CreateRunRequest, v1.Run](
			httpClient,
			baseURL+OverseerServiceCreateRunProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("CreateRun")),
			connect.WithClientOptions(opts...),
		),
		reattachRun: connect.NewClient[v1.ReattachRunRequest, v1.ReattachRunResponse](
			httpClient,
			baseURL+OverseerServiceReattachRunProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("ReattachRun")),
			connect.WithClientOptions(opts...),
		),
		resume: connect.NewClient[v1.ResumeRequest, v1.ResumeResponse](
			httpClient,
			baseURL+OverseerServiceResumeProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("Resume")),
			connect.WithClientOptions(opts...),
		),
		submitEvents: connect.NewClient[v1.Envelope, v1.Ack](
			httpClient,
			baseURL+OverseerServiceSubmitEventsProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("SubmitEvents")),
			connect.WithClientOptions(opts...),
		),
		control: connect.NewClient[v1.ControlSubscribeRequest, v1.ControlMessage](
			httpClient,
			baseURL+OverseerServiceControlProcedure,
			connect.WithSchema(overseerServiceMethods.ByName("Control")),
			connect.WithClientOptions(opts...),
		),
	}
}

// overseerServiceClient implements OverseerServiceClient.
type overseerServiceClient struct {
	register     *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	heartbeat    *connect.Client[v1.HeartbeatRequest, v1.HeartbeatResponse]
	createRun    *connect.Client[v1.CreateRunRequest, v1.Run]
	reattachRun  *connect.Client[v1.ReattachRunRequest, v1.ReattachRunResponse]
	resume       *connect.Client[v1.ResumeRequest, v1.ResumeResponse]
	submitEvents *connect.Client[v1.Envelope, v1.Ack]
	control      *connect.Client[v1.ControlSubscribeRequest, v1.ControlMessage]
}

// Register calls overseer.v1.OverseerService.Register.
func (c *overseerServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Heartbeat calls overseer.v1.OverseerService.Heartbeat.
func (c *overseerServiceClient) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// CreateRun calls overseer.v1.OverseerService.CreateRun.
func (c *overseerServiceClient) CreateRun(ctx context.Context, req *connect.Request[v1.CreateRunRequest]) (*connect.Response[v1.Run], error) {
	return c.createRun.CallUnary(ctx, req)
}

// ReattachRun calls overseer.v1.OverseerService.ReattachRun.
func (c *overseerServiceClient) ReattachRun(ctx context.Context, req *connect.Request[v1.ReattachRunRequest]) (*connect.Response[v1.ReattachRunResponse], error) {
	return c.reattachRun.CallUnary(ctx, req)
}

// Resume calls overseer.v1.OverseerService.Resume.
func (c *overseerServiceClient) Resume(ctx context.Context, req *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error) {
	return c.resume.CallUnary(ctx, req)
}

// SubmitEvents calls overseer.v1.OverseerService.SubmitEvents.
func (c *overseerServiceClient) SubmitEvents(ctx context.Context) *connect.BidiStreamForClient[v1.Envelope, v1.Ack] {
	return c.submitEvents.CallBidiStream(ctx)
}

// Control calls overseer.v1.OverseerService.Control.
func (c *overseerServiceClient) Control(ctx context.Context, req *connect.Request[v1.ControlSubscribeRequest]) (*connect.ServerStreamForClient[v1.ControlMessage], error) {
	return c.control.CallServerStream(ctx, req)
}

// OverseerServiceHandler is an implementation of the overseer.v1.OverseerService service.
type OverseerServiceHandler interface {
	// Register enrolls an Overseer with the orchestrator. Returns the assigned
	// overseer id and an auth token the Overseer must present on all subsequent
	// RPCs.
	//
	// Bootstrap gate: implementations MUST require a bootstrap token (e.g. via
	// an `X-Castle-Bootstrap` header) before accepting Register. When no
	// bootstrap mechanism is configured, implementations MUST return
	// Unimplemented. This prevents open self-registration in production.
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	// Heartbeat advances the Overseer's `last_seen_at`. The orchestrator marks
	// Overseers offline whose heartbeat is older than a configurable threshold.
	//
	// The authenticated caller's identity is the canonical overseer being
	// updated. Implementations MUST ignore any request-supplied overseer_id and
	// use the caller's authenticated identity instead.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
	// CreateRun mints a new run owned by the authenticated caller. The
	// orchestrator is the sole source of run ids.
	//
	// The run is always recorded under the authenticated caller's overseer ID.
	// The request's `overseer_id` field is informational only. Implementations
	// MUST ignore any request-supplied overseer_id and use the caller's
	// authenticated identity.
	CreateRun(context.Context, *connect.Request[v1.CreateRunRequest]) (*connect.Response[v1.Run], error)
	// ReattachRun lets an Overseer query the orchestrator about an in-flight run
	// after a crash or restart. The orchestrator returns the current status,
	// last active step, and whether the Overseer may resume execution.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's overseer.
	ReattachRun(context.Context, *connect.Request[v1.ReattachRunRequest]) (*connect.Response[v1.ReattachRunResponse], error)
	// Resume delivers a named signal (or an approval decision) to a paused run.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's overseer.
	//
	// This RPC is SDK contract surface: field names, payload semantics, and
	// error-reason strings are stable for third-party orchestrators.
	Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error)
	// SubmitEvents is a bidirectional stream. The client writes Envelopes and
	// the server replies with an Ack per persisted envelope (run_id, seq,
	// correlation_id). On reconnect the client may include `since_seq` in
	// request metadata to request replay of events that were persisted but not
	// yet acknowledged.
	//
	// Implementations MUST verify on every envelope that the authenticated caller
	// owns the envelope's run_id. On the first violation the stream MUST be
	// rejected with PERMISSION_DENIED; envelopes MUST NOT be silently dropped.
	SubmitEvents(context.Context, *connect.BidiStream[v1.Envelope, v1.Ack]) error
	// Control is a long-lived server-stream that the orchestrator uses to push
	// commands to a connected Overseer (cancel a run, send a prompt to an
	// agent, ...).
	//
	// The authenticated caller's identity determines the registry key for the
	// Control subscription. Implementations MUST ignore any request-supplied
	// overseer_id and use the caller's authenticated identity.
	Control(context.Context, *connect.Request[v1.ControlSubscribeRequest], *connect.ServerStream[v1.ControlMessage]) error
}

// NewOverseerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOverseerServiceHandler(svc OverseerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	overseerServiceMethods := v1.File_v1_overseer_proto.Services().ByName("OverseerService").Methods()
	overseerServiceRegisterHandler := connect.NewUnaryHandler(
		OverseerServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(overseerServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	overseerServiceHeartbeatHandler := connect.NewUnaryHandler(
		OverseerServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(overseerServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	overseerServiceCreateRunHandler := connect.NewUnaryHandler(
		OverseerServiceCreateRunProcedure,
		svc.CreateRun,
		connect.WithSchema(overseerServiceMethods.ByName("CreateRun")),
		connect.WithHandlerOptions(opts...),
	)
	overseerServiceReattachRunHandler := connect.NewUnaryHandler(
		OverseerServiceReattachRunProcedure,
		svc.ReattachRun,
		connect.WithSchema(overseerServiceMethods.ByName("ReattachRun")),
		connect.WithHandlerOptions(opts...),
	)
	overseerServiceResumeHandler := connect.NewUnaryHandler(
		OverseerServiceResumeProcedure,
		svc.Resume,
		connect.WithSchema(overseerServiceMethods.ByName("Resume")),
		connect.WithHandlerOptions(opts...),
	)
	overseerServiceSubmitEventsHandler := connect.NewBidiStreamHandler(
		OverseerServiceSubmitEventsProcedure,
		svc.SubmitEvents,
		connect.WithSchema(overseerServiceMethods.ByName("SubmitEvents")),
		connect.WithHandlerOptions(opts...),
	)
	overseerServiceControlHandler := connect.NewServerStreamHandler(
		OverseerServiceControlProcedure,
		svc.Control,
		connect.WithSchema(overseerServiceMethods.ByName("Control")),
		connect.WithHandlerOptions(opts...),
	)
	return "/overseer.v1.OverseerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OverseerServiceRegisterProcedure:
			overseerServiceRegisterHandler.ServeHTTP(w, r)
		case OverseerServiceHeartbeatProcedure:
			overseerServiceHeartbeatHandler.ServeHTTP(w, r)
		case OverseerServiceCreateRunProcedure:
			overseerServiceCreateRunHandler.ServeHTTP(w, r)
		case OverseerServiceReattachRunProcedure:
			overseerServiceReattachRunHandler.ServeHTTP(w, r)
		case OverseerServiceResumeProcedure:
			overseerServiceResumeHandler.ServeHTTP(w, r)
		case OverseerServiceSubmitEventsProcedure:
			overseerServiceSubmitEventsHandler.ServeHTTP(w, r)
		case OverseerServiceControlProcedure:
			overseerServiceControlHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOverseerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOverseerServiceHandler struct{}

func (UnimplementedOverseerServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.Register is not implemented"))
}

func (UnimplementedOverseerServiceHandler) Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.Heartbeat is not implemented"))
}

func (UnimplementedOverseerServiceHandler) CreateRun(context.Context, *connect.Request[v1.CreateRunRequest]) (*connect.Response[v1.Run], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.CreateRun is not implemented"))
}

func (UnimplementedOverseerServiceHandler) ReattachRun(context.Context, *connect.Request[v1.ReattachRunRequest]) (*connect.Response[v1.ReattachRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.ReattachRun is not implemented"))
}

func (UnimplementedOverseerServiceHandler) Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.Resume is not implemented"))
}

func (UnimplementedOverseerServiceHandler) SubmitEvents(context.Context, *connect.BidiStream[v1.Envelope, v1.Ack]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.SubmitEvents is not implemented"))
}

func (UnimplementedOverseerServiceHandler) Control(context.Context, *connect.Request[v1.ControlSubscribeRequest], *connect.ServerStream[v1.ControlMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.OverseerService.Control is not implemented"))
}
