// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: overseer/v1/adapter_plugin.proto

package overseerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/overseer/sdk/pb/overseer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdapterPluginServiceName is the fully-qualified name of the AdapterPluginService service.
	AdapterPluginServiceName = "overseer.v1.AdapterPluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdapterPluginServiceInfoProcedure is the fully-qualified name of the AdapterPluginService's Info
	// RPC.
	AdapterPluginServiceInfoProcedure = "/overseer.v1.AdapterPluginService/Info"
	// AdapterPluginServiceOpenSessionProcedure is the fully-qualified name of the
	// AdapterPluginService's OpenSession RPC.
	AdapterPluginServiceOpenSessionProcedure = "/overseer.v1.AdapterPluginService/OpenSession"
	// AdapterPluginServiceExecuteProcedure is the fully-qualified name of the AdapterPluginService's
	// Execute RPC.
	AdapterPluginServiceExecuteProcedure = "/overseer.v1.AdapterPluginService/Execute"
	// AdapterPluginServicePermitProcedure is the fully-qualified name of the AdapterPluginService's
	// Permit RPC.
	AdapterPluginServicePermitProcedure = "/overseer.v1.AdapterPluginService/Permit"
	// AdapterPluginServiceCloseSessionProcedure is the fully-qualified name of the
	// AdapterPluginService's CloseSession RPC.
	AdapterPluginServiceCloseSessionProcedure = "/overseer.v1.AdapterPluginService/CloseSession"
)

// AdapterPluginServiceClient is a client for the overseer.v1.AdapterPluginService service.
type AdapterPluginServiceClient interface {
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	OpenSession(context.Context, *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error)
	Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.ServerStreamForClient[v1.ExecuteEvent], error)
	Permit(context.Context, *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error)
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
}

// NewAdapterPluginServiceClient constructs a client for the overseer.v1.AdapterPluginService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdapterPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdapterPluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adapterPluginServiceMethods := v1.File_overseer_v1_adapter_plugin_proto.Services().ByName("AdapterPluginService").Methods()
	return &adapterPluginServiceClient{
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+AdapterPluginServiceInfoProcedure,
			connect.WithSchema(adapterPluginServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		openSession: connect.NewClient[v1.OpenSessionRequest, v1.OpenSessionResponse](
			httpClient,
			baseURL+AdapterPluginServiceOpenSessionProcedure,
			connect.WithSchema(adapterPluginServiceMethods.ByName("OpenSession")),
			connect.WithClientOptions(opts...),
		),
		execute: connect.NewClient[v1.ExecuteRequest, v1.ExecuteEvent](
			httpClient,
			baseURL+AdapterPluginServiceExecuteProcedure,
			connect.WithSchema(adapterPluginServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
		permit: connect.NewClient[v1.PermitRequest, v1.PermitResponse](
			httpClient,
			baseURL+AdapterPluginServicePermitProcedure,
			connect.WithSchema(adapterPluginServiceMethods.ByName("Permit")),
			connect.WithClientOptions(opts...),
		),
		closeSession: connect.NewClient[v1.CloseSessionRequest, v1.CloseSessionResponse](
			httpClient,
			baseURL+AdapterPluginServiceCloseSessionProcedure,
			connect.WithSchema(adapterPluginServiceMethods.ByName("CloseSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adapterPluginServiceClient implements AdapterPluginServiceClient.
type adapterPluginServiceClient struct {
	info         *connect.Client[v1.InfoRequest, v1.InfoResponse]
	openSession  *connect.Client[v1.OpenSessionRequest, v1.OpenSessionResponse]
	execute      *connect.Client[v1.ExecuteRequest, v1.ExecuteEvent]
	permit       *connect.Client[v1.PermitRequest, v1.PermitResponse]
	closeSession *connect.Client[v1.CloseSessionRequest, v1.CloseSessionResponse]
}

// Info calls overseer.v1.AdapterPluginService.Info.
func (c *adapterPluginServiceClient) Info(ctx context.Context, req *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// OpenSession calls overseer.v1.AdapterPluginService.OpenSession.
func (c *adapterPluginServiceClient) OpenSession(ctx context.Context, req *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error) {
	return c.openSession.CallUnary(ctx, req)
}

// Execute calls overseer.v1.AdapterPluginService.Execute.
func (c *adapterPluginServiceClient) Execute(ctx context.Context, req *connect.Request[v1.ExecuteRequest]) (*connect.ServerStreamForClient[v1.ExecuteEvent], error) {
	return c.execute.CallServerStream(ctx, req)
}

// Permit calls overseer.v1.AdapterPluginService.Permit.
func (c *adapterPluginServiceClient) Permit(ctx context.Context, req *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error) {
	return c.permit.CallUnary(ctx, req)
}

// CloseSession calls overseer.v1.AdapterPluginService.CloseSession.
func (c *adapterPluginServiceClient) CloseSession(ctx context.Context, req *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return c.closeSession.CallUnary(ctx, req)
}

// AdapterPluginServiceHandler is an implementation of the overseer.v1.AdapterPluginService service.
type AdapterPluginServiceHandler interface {
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	OpenSession(context.Context, *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error)
	Execute(context.Context, *connect.Request[v1.ExecuteRequest], *connect.ServerStream[v1.ExecuteEvent]) error
	Permit(context.Context, *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error)
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
}

// NewAdapterPluginServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdapterPluginServiceHandler(svc AdapterPluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adapterPluginServiceMethods := v1.File_overseer_v1_adapter_plugin_proto.Services().ByName("AdapterPluginService").Methods()
	adapterPluginServiceInfoHandler := connect.NewUnaryHandler(
		AdapterPluginServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(adapterPluginServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	adapterPluginServiceOpenSessionHandler := connect.NewUnaryHandler(
		AdapterPluginServiceOpenSessionProcedure,
		svc.OpenSession,
		connect.WithSchema(adapterPluginServiceMethods.ByName("OpenSession")),
		connect.WithHandlerOptions(opts...),
	)
	adapterPluginServiceExecuteHandler := connect.NewServerStreamHandler(
		AdapterPluginServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(adapterPluginServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	adapterPluginServicePermitHandler := connect.NewUnaryHandler(
		AdapterPluginServicePermitProcedure,
		svc.Permit,
		connect.WithSchema(adapterPluginServiceMethods.ByName("Permit")),
		connect.WithHandlerOptions(opts...),
	)
	adapterPluginServiceCloseSessionHandler := connect.NewUnaryHandler(
		AdapterPluginServiceCloseSessionProcedure,
		svc.CloseSession,
		connect.WithSchema(adapterPluginServiceMethods.ByName("CloseSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/overseer.v1.AdapterPluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdapterPluginServiceInfoProcedure:
			adapterPluginServiceInfoHandler.ServeHTTP(w, r)
		case AdapterPluginServiceOpenSessionProcedure:
			adapterPluginServiceOpenSessionHandler.ServeHTTP(w, r)
		case AdapterPluginServiceExecuteProcedure:
			adapterPluginServiceExecuteHandler.ServeHTTP(w, r)
		case AdapterPluginServicePermitProcedure:
			adapterPluginServicePermitHandler.ServeHTTP(w, r)
		case AdapterPluginServiceCloseSessionProcedure:
			adapterPluginServiceCloseSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdapterPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdapterPluginServiceHandler struct{}

func (UnimplementedAdapterPluginServiceHandler) Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.AdapterPluginService.Info is not implemented"))
}

func (UnimplementedAdapterPluginServiceHandler) OpenSession(context.Context, *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.AdapterPluginService.OpenSession is not implemented"))
}

func (UnimplementedAdapterPluginServiceHandler) Execute(context.Context, *connect.Request[v1.ExecuteRequest], *connect.ServerStream[v1.ExecuteEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.AdapterPluginService.Execute is not implemented"))
}

func (UnimplementedAdapterPluginServiceHandler) Permit(context.Context, *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.AdapterPluginService.Permit is not implemented"))
}

func (UnimplementedAdapterPluginServiceHandler) CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("overseer.v1.AdapterPluginService.CloseSession is not implemented"))
}
