// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: criteria/v1/adapter_plugin.proto

package criteriav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/criteria/sdk/pb/criteria/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdapterServiceName is the fully-qualified name of the AdapterService service.
	AdapterServiceName = "criteria.v1.AdapterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdapterServiceInfoProcedure is the fully-qualified name of the AdapterService's Info RPC.
	AdapterServiceInfoProcedure = "/criteria.v1.AdapterService/Info"
	// AdapterServiceOpenSessionProcedure is the fully-qualified name of the AdapterService's
	// OpenSession RPC.
	AdapterServiceOpenSessionProcedure = "/criteria.v1.AdapterService/OpenSession"
	// AdapterServiceExecuteProcedure is the fully-qualified name of the AdapterService's Execute RPC.
	AdapterServiceExecuteProcedure = "/criteria.v1.AdapterService/Execute"
	// AdapterServicePermitProcedure is the fully-qualified name of the AdapterService's Permit RPC.
	AdapterServicePermitProcedure = "/criteria.v1.AdapterService/Permit"
	// AdapterServiceCloseSessionProcedure is the fully-qualified name of the AdapterService's
	// CloseSession RPC.
	AdapterServiceCloseSessionProcedure = "/criteria.v1.AdapterService/CloseSession"
)

// AdapterServiceClient is a client for the criteria.v1.AdapterService service.
type AdapterServiceClient interface {
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	OpenSession(context.Context, *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error)
	Execute(context.Context, *connect.Request[v1.ExecuteRequest]) (*connect.ServerStreamForClient[v1.ExecuteEvent], error)
	Permit(context.Context, *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error)
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
}

// NewAdapterServiceClient constructs a client for the criteria.v1.AdapterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdapterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdapterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adapterServiceMethods := v1.File_criteria_v1_adapter_plugin_proto.Services().ByName("AdapterService").Methods()
	return &adapterServiceClient{
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+AdapterServiceInfoProcedure,
			connect.WithSchema(adapterServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		openSession: connect.NewClient[v1.OpenSessionRequest, v1.OpenSessionResponse](
			httpClient,
			baseURL+AdapterServiceOpenSessionProcedure,
			connect.WithSchema(adapterServiceMethods.ByName("OpenSession")),
			connect.WithClientOptions(opts...),
		),
		execute: connect.NewClient[v1.ExecuteRequest, v1.ExecuteEvent](
			httpClient,
			baseURL+AdapterServiceExecuteProcedure,
			connect.WithSchema(adapterServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
		permit: connect.NewClient[v1.PermitRequest, v1.PermitResponse](
			httpClient,
			baseURL+AdapterServicePermitProcedure,
			connect.WithSchema(adapterServiceMethods.ByName("Permit")),
			connect.WithClientOptions(opts...),
		),
		closeSession: connect.NewClient[v1.CloseSessionRequest, v1.CloseSessionResponse](
			httpClient,
			baseURL+AdapterServiceCloseSessionProcedure,
			connect.WithSchema(adapterServiceMethods.ByName("CloseSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adapterServiceClient implements AdapterServiceClient.
type adapterServiceClient struct {
	info         *connect.Client[v1.InfoRequest, v1.InfoResponse]
	openSession  *connect.Client[v1.OpenSessionRequest, v1.OpenSessionResponse]
	execute      *connect.Client[v1.ExecuteRequest, v1.ExecuteEvent]
	permit       *connect.Client[v1.PermitRequest, v1.PermitResponse]
	closeSession *connect.Client[v1.CloseSessionRequest, v1.CloseSessionResponse]
}

// Info calls criteria.v1.AdapterService.Info.
func (c *adapterServiceClient) Info(ctx context.Context, req *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// OpenSession calls criteria.v1.AdapterService.OpenSession.
func (c *adapterServiceClient) OpenSession(ctx context.Context, req *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error) {
	return c.openSession.CallUnary(ctx, req)
}

// Execute calls criteria.v1.AdapterService.Execute.
func (c *adapterServiceClient) Execute(ctx context.Context, req *connect.Request[v1.ExecuteRequest]) (*connect.ServerStreamForClient[v1.ExecuteEvent], error) {
	return c.execute.CallServerStream(ctx, req)
}

// Permit calls criteria.v1.AdapterService.Permit.
func (c *adapterServiceClient) Permit(ctx context.Context, req *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error) {
	return c.permit.CallUnary(ctx, req)
}

// CloseSession calls criteria.v1.AdapterService.CloseSession.
func (c *adapterServiceClient) CloseSession(ctx context.Context, req *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return c.closeSession.CallUnary(ctx, req)
}

// AdapterServiceHandler is an implementation of the criteria.v1.AdapterService service.
type AdapterServiceHandler interface {
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	OpenSession(context.Context, *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error)
	Execute(context.Context, *connect.Request[v1.ExecuteRequest], *connect.ServerStream[v1.ExecuteEvent]) error
	Permit(context.Context, *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error)
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
}

// NewAdapterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdapterServiceHandler(svc AdapterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adapterServiceMethods := v1.File_criteria_v1_adapter_plugin_proto.Services().ByName("AdapterService").Methods()
	adapterServiceInfoHandler := connect.NewUnaryHandler(
		AdapterServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(adapterServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	adapterServiceOpenSessionHandler := connect.NewUnaryHandler(
		AdapterServiceOpenSessionProcedure,
		svc.OpenSession,
		connect.WithSchema(adapterServiceMethods.ByName("OpenSession")),
		connect.WithHandlerOptions(opts...),
	)
	adapterServiceExecuteHandler := connect.NewServerStreamHandler(
		AdapterServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(adapterServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	adapterServicePermitHandler := connect.NewUnaryHandler(
		AdapterServicePermitProcedure,
		svc.Permit,
		connect.WithSchema(adapterServiceMethods.ByName("Permit")),
		connect.WithHandlerOptions(opts...),
	)
	adapterServiceCloseSessionHandler := connect.NewUnaryHandler(
		AdapterServiceCloseSessionProcedure,
		svc.CloseSession,
		connect.WithSchema(adapterServiceMethods.ByName("CloseSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/criteria.v1.AdapterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdapterServiceInfoProcedure:
			adapterServiceInfoHandler.ServeHTTP(w, r)
		case AdapterServiceOpenSessionProcedure:
			adapterServiceOpenSessionHandler.ServeHTTP(w, r)
		case AdapterServiceExecuteProcedure:
			adapterServiceExecuteHandler.ServeHTTP(w, r)
		case AdapterServicePermitProcedure:
			adapterServicePermitHandler.ServeHTTP(w, r)
		case AdapterServiceCloseSessionProcedure:
			adapterServiceCloseSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdapterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdapterServiceHandler struct{}

func (UnimplementedAdapterServiceHandler) Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.AdapterService.Info is not implemented"))
}

func (UnimplementedAdapterServiceHandler) OpenSession(context.Context, *connect.Request[v1.OpenSessionRequest]) (*connect.Response[v1.OpenSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.AdapterService.OpenSession is not implemented"))
}

func (UnimplementedAdapterServiceHandler) Execute(context.Context, *connect.Request[v1.ExecuteRequest], *connect.ServerStream[v1.ExecuteEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.AdapterService.Execute is not implemented"))
}

func (UnimplementedAdapterServiceHandler) Permit(context.Context, *connect.Request[v1.PermitRequest]) (*connect.Response[v1.PermitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.AdapterService.Permit is not implemented"))
}

func (UnimplementedAdapterServiceHandler) CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.AdapterService.CloseSession is not implemented"))
}
