// CriteriaService — RPCs served by the server and consumed by Criteria agents.
//
// Authentication: all RPCs except `Register` require a token (Bearer header,
// `X-Criteria-Token` header, or `criteria-token` Connect metadata). Tokens are
// SHA-256 compared against `criteria.token_hash` in the orchestrator store.
//
// Caller ownership: mutating RPCs enforce that the authenticated caller owns
// the affected criteria agent or run. Implementations MUST enforce this contract.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: criteria/v1/criteria.proto

package criteriav1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v1 "github.com/brokenbots/criteria/sdk/pb/criteria/v1"
	sync "sync"
)

const (
	// CriteriaServiceName is the fully-qualified name of the CriteriaService service.
	CriteriaServiceName = "criteria.v1.CriteriaService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CriteriaServiceRegisterProcedure is the procedure name of the CriteriaService's Register RPC.
	CriteriaServiceRegisterProcedure = "/criteria.v1.CriteriaService/Register"
	// CriteriaServiceHeartbeatProcedure is the procedure name of the CriteriaService's Heartbeat RPC.
	CriteriaServiceHeartbeatProcedure = "/criteria.v1.CriteriaService/Heartbeat"
	// CriteriaServiceCreateRunProcedure is the procedure name of the CriteriaService's CreateRun RPC.
	CriteriaServiceCreateRunProcedure = "/criteria.v1.CriteriaService/CreateRun"
	// CriteriaServiceReattachRunProcedure is the procedure name of the CriteriaService's ReattachRun
	// RPC.
	CriteriaServiceReattachRunProcedure = "/criteria.v1.CriteriaService/ReattachRun"
	// CriteriaServiceResumeProcedure is the procedure name of the CriteriaService's Resume RPC.
	CriteriaServiceResumeProcedure = "/criteria.v1.CriteriaService/Resume"
	// CriteriaServiceSubmitEventsProcedure is the procedure name of the CriteriaService's SubmitEvents
	// RPC.
	CriteriaServiceSubmitEventsProcedure = "/criteria.v1.CriteriaService/SubmitEvents"
	// CriteriaServiceControlProcedure is the procedure name of the CriteriaService's Control RPC.
	CriteriaServiceControlProcedure = "/criteria.v1.CriteriaService/Control"
)

var (
	criteriaServiceRegisterSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("Register"),
			Procedure:  CriteriaServiceRegisterProcedure,
		}
	})
	criteriaServiceHeartbeatSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("Heartbeat"),
			Procedure:  CriteriaServiceHeartbeatProcedure,
		}
	})
	criteriaServiceCreateRunSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("CreateRun"),
			Procedure:  CriteriaServiceCreateRunProcedure,
		}
	})
	criteriaServiceReattachRunSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("ReattachRun"),
			Procedure:  CriteriaServiceReattachRunProcedure,
		}
	})
	criteriaServiceResumeSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("Resume"),
			Procedure:  CriteriaServiceResumeProcedure,
		}
	})
	criteriaServiceSubmitEventsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeBidi,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("SubmitEvents"),
			Procedure:  CriteriaServiceSubmitEventsProcedure,
		}
	})
	criteriaServiceControlSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeServer,
			Schema:     v1.File_criteria_v1_criteria_proto.Services().ByName("CriteriaService").Methods().ByName("Control"),
			Procedure:  CriteriaServiceControlProcedure,
		}
	})
)

// CriteriaServiceClient is a client for the criteria.v1.CriteriaService service.
type CriteriaServiceClient interface {
	// Register enrolls a Criteria agent with the orchestrator. Returns the assigned
	// criteria id and an auth token the agent must present on all subsequent
	// RPCs.
	//
	// Bootstrap gate: implementations MUST require a bootstrap token (e.g. via
	// an `X-Server-Bootstrap` header) before accepting Register. When no
	// bootstrap mechanism is configured, implementations MUST return
	// Unimplemented. This prevents open self-registration in production.
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
	// Heartbeat advances the agent's `last_seen_at`. The orchestrator marks
	// agents offline whose heartbeat is older than a configurable threshold.
	//
	// The authenticated caller's identity is the canonical criteria agent being
	// updated. Implementations MUST ignore any request-supplied criteria_id and
	// use the caller's authenticated identity instead.
	Heartbeat(context.Context, *v1.HeartbeatRequest) (*v1.HeartbeatResponse, error)
	// CreateRun mints a new run owned by the authenticated caller. The
	// orchestrator is the sole source of run ids.
	//
	// The run is always recorded under the authenticated caller's criteria ID.
	// The request's `criteria_id` field is informational only. Implementations
	// MUST ignore any request-supplied criteria_id and use the caller's
	// authenticated identity.
	CreateRun(context.Context, *v1.CreateRunRequest) (*v1.Run, error)
	// ReattachRun lets a Criteria agent query the orchestrator about an in-flight run
	// after a crash or restart. The orchestrator returns the current status,
	// last active step, and whether the agent may resume execution.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's criteria agent.
	ReattachRun(context.Context, *v1.ReattachRunRequest) (*v1.ReattachRunResponse, error)
	// Resume delivers a named signal (or an approval decision) to a paused run.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's criteria agent.
	//
	// This RPC is SDK contract surface: field names, payload semantics, and
	// error-reason strings are stable for third-party orchestrators.
	Resume(context.Context, *v1.ResumeRequest) (*v1.ResumeResponse, error)
	// SubmitEvents is a bidirectional stream. The client writes Envelopes and
	// the server replies with an Ack per persisted envelope (run_id, seq,
	// correlation_id). On reconnect the client may include `since_seq` in
	// request metadata to request replay of events that were persisted but not
	// yet acknowledged.
	//
	// Implementations MUST verify on every envelope that the authenticated caller
	// owns the envelope's run_id. On the first violation the stream MUST be
	// rejected with PERMISSION_DENIED; envelopes MUST NOT be silently dropped.
	SubmitEvents(context.Context) (CriteriaServiceSubmitEventsClientStream, error)
	// Control is a long-lived server-stream that the orchestrator uses to push
	// commands to a connected Criteria agent (cancel a run, send a prompt to an
	// agent, ...).
	//
	// The authenticated caller's identity determines the registry key for the
	// Control subscription. Implementations MUST ignore any request-supplied
	// criteria_id and use the caller's authenticated identity.
	Control(context.Context, *v1.ControlSubscribeRequest) (CriteriaServiceControlClientStream, error)
}

// NewCriteriaServiceClient constructs a client for the criteria.v1.CriteriaService service.
// Multiple service clients may share a single connect.Client.
func NewCriteriaServiceClient(client *connect.Client) CriteriaServiceClient {
	return &criteriaServiceClient{client: client}
}

// CriteriaServiceSubmitEventsClientStream is the client stream for the CriteriaService's
// SubmitEvents RPC.
type CriteriaServiceSubmitEventsClientStream struct {
	stream connect.ClientStream
}

// SendHeaders opens the stream and flushes the request headers without a message. The first Send or
// Receive does this implicitly.
func (s CriteriaServiceSubmitEventsClientStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a request message to the server.
func (s CriteriaServiceSubmitEventsClientStream) Send(req *v1.Envelope) error {
	return s.stream.Send(req)
}

// CloseSend closes the request side of the stream.
func (s CriteriaServiceSubmitEventsClientStream) CloseSend() error {
	return s.stream.CloseSend()
}

// Receive returns the next response message from the server.
func (s CriteriaServiceSubmitEventsClientStream) Receive() (*v1.Ack, error) {
	var res v1.Ack
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s CriteriaServiceSubmitEventsClientStream) Close() error {
	return s.stream.Close()
}

// CriteriaServiceControlClientStream is the client stream for the CriteriaService's Control RPC.
type CriteriaServiceControlClientStream struct {
	stream connect.ClientStream
}

// Receive returns the next response message from the server.
func (s CriteriaServiceControlClientStream) Receive() (*v1.ControlMessage, error) {
	var res v1.ControlMessage
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s CriteriaServiceControlClientStream) Close() error {
	return s.stream.Close()
}

// CriteriaServiceHandler is an implementation of the criteria.v1.CriteriaService service.
type CriteriaServiceHandler interface {
	// Register enrolls a Criteria agent with the orchestrator. Returns the assigned
	// criteria id and an auth token the agent must present on all subsequent
	// RPCs.
	//
	// Bootstrap gate: implementations MUST require a bootstrap token (e.g. via
	// an `X-Server-Bootstrap` header) before accepting Register. When no
	// bootstrap mechanism is configured, implementations MUST return
	// Unimplemented. This prevents open self-registration in production.
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
	// Heartbeat advances the agent's `last_seen_at`. The orchestrator marks
	// agents offline whose heartbeat is older than a configurable threshold.
	//
	// The authenticated caller's identity is the canonical criteria agent being
	// updated. Implementations MUST ignore any request-supplied criteria_id and
	// use the caller's authenticated identity instead.
	Heartbeat(context.Context, *v1.HeartbeatRequest) (*v1.HeartbeatResponse, error)
	// CreateRun mints a new run owned by the authenticated caller. The
	// orchestrator is the sole source of run ids.
	//
	// The run is always recorded under the authenticated caller's criteria ID.
	// The request's `criteria_id` field is informational only. Implementations
	// MUST ignore any request-supplied criteria_id and use the caller's
	// authenticated identity.
	CreateRun(context.Context, *v1.CreateRunRequest) (*v1.Run, error)
	// ReattachRun lets a Criteria agent query the orchestrator about an in-flight run
	// after a crash or restart. The orchestrator returns the current status,
	// last active step, and whether the agent may resume execution.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's criteria agent.
	ReattachRun(context.Context, *v1.ReattachRunRequest) (*v1.ReattachRunResponse, error)
	// Resume delivers a named signal (or an approval decision) to a paused run.
	//
	// Implementations MUST reject the request with PERMISSION_DENIED if the
	// authenticated caller does not own the target run's criteria agent.
	//
	// This RPC is SDK contract surface: field names, payload semantics, and
	// error-reason strings are stable for third-party orchestrators.
	Resume(context.Context, *v1.ResumeRequest) (*v1.ResumeResponse, error)
	// SubmitEvents is a bidirectional stream. The client writes Envelopes and
	// the server replies with an Ack per persisted envelope (run_id, seq,
	// correlation_id). On reconnect the client may include `since_seq` in
	// request metadata to request replay of events that were persisted but not
	// yet acknowledged.
	//
	// Implementations MUST verify on every envelope that the authenticated caller
	// owns the envelope's run_id. On the first violation the stream MUST be
	// rejected with PERMISSION_DENIED; envelopes MUST NOT be silently dropped.
	SubmitEvents(context.Context, CriteriaServiceSubmitEventsServerStream) error
	// Control is a long-lived server-stream that the orchestrator uses to push
	// commands to a connected Criteria agent (cancel a run, send a prompt to an
	// agent, ...).
	//
	// The authenticated caller's identity determines the registry key for the
	// Control subscription. Implementations MUST ignore any request-supplied
	// criteria_id and use the caller's authenticated identity.
	Control(context.Context, *v1.ControlSubscribeRequest, CriteriaServiceControlServerStream) error
}

// RegisterCriteriaServiceHandler registers svc as the criteria.v1.CriteriaService implementation on
// server.
func RegisterCriteriaServiceHandler(server *connect.Server, svc CriteriaServiceHandler) {
	adapter := criteriaServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: criteriaServiceRegisterSpec(), Handler: adapter.register},
		connect.Method{Spec: criteriaServiceHeartbeatSpec(), Handler: adapter.heartbeat},
		connect.Method{Spec: criteriaServiceCreateRunSpec(), Handler: adapter.createRun},
		connect.Method{Spec: criteriaServiceReattachRunSpec(), Handler: adapter.reattachRun},
		connect.Method{Spec: criteriaServiceResumeSpec(), Handler: adapter.resume},
		connect.Method{Spec: criteriaServiceSubmitEventsSpec(), Handler: adapter.submitEvents},
		connect.Method{Spec: criteriaServiceControlSpec(), Handler: adapter.control},
	)
}

// CriteriaServiceSubmitEventsServerStream is the server stream for the CriteriaService's
// SubmitEvents RPC.
type CriteriaServiceSubmitEventsServerStream struct {
	stream connect.ServerStream
}

// Receive returns the next request message from the client.
func (s CriteriaServiceSubmitEventsServerStream) Receive() (*v1.Envelope, error) {
	var req v1.Envelope
	if err := s.stream.Receive(&req); err != nil {
		return nil, err
	}
	return &req, nil
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s CriteriaServiceSubmitEventsServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s CriteriaServiceSubmitEventsServerStream) Send(res *v1.Ack) error {
	return s.stream.Send(res)
}

// CriteriaServiceControlServerStream is the server stream for the CriteriaService's Control RPC.
type CriteriaServiceControlServerStream struct {
	stream connect.ServerStream
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s CriteriaServiceControlServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s CriteriaServiceControlServerStream) Send(res *v1.ControlMessage) error {
	return s.stream.Send(res)
}

// UnimplementedCriteriaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCriteriaServiceHandler struct{}

func (UnimplementedCriteriaServiceHandler) Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.Register is not implemented")
}

func (UnimplementedCriteriaServiceHandler) Heartbeat(context.Context, *v1.HeartbeatRequest) (*v1.HeartbeatResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.Heartbeat is not implemented")
}

func (UnimplementedCriteriaServiceHandler) CreateRun(context.Context, *v1.CreateRunRequest) (*v1.Run, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.CreateRun is not implemented")
}

func (UnimplementedCriteriaServiceHandler) ReattachRun(context.Context, *v1.ReattachRunRequest) (*v1.ReattachRunResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.ReattachRun is not implemented")
}

func (UnimplementedCriteriaServiceHandler) Resume(context.Context, *v1.ResumeRequest) (*v1.ResumeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.Resume is not implemented")
}

func (UnimplementedCriteriaServiceHandler) SubmitEvents(context.Context, CriteriaServiceSubmitEventsServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.SubmitEvents is not implemented")
}

func (UnimplementedCriteriaServiceHandler) Control(context.Context, *v1.ControlSubscribeRequest, CriteriaServiceControlServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "criteria.v1.CriteriaService.Control is not implemented")
}

type criteriaServiceClient struct {
	client *connect.Client
}

func (c *criteriaServiceClient) Register(ctx context.Context, req *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	var res v1.RegisterResponse
	if err := c.client.CallUnary(ctx, criteriaServiceRegisterSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *criteriaServiceClient) Heartbeat(ctx context.Context, req *v1.HeartbeatRequest) (*v1.HeartbeatResponse, error) {
	var res v1.HeartbeatResponse
	if err := c.client.CallUnary(ctx, criteriaServiceHeartbeatSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *criteriaServiceClient) CreateRun(ctx context.Context, req *v1.CreateRunRequest) (*v1.Run, error) {
	var res v1.Run
	if err := c.client.CallUnary(ctx, criteriaServiceCreateRunSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *criteriaServiceClient) ReattachRun(ctx context.Context, req *v1.ReattachRunRequest) (*v1.ReattachRunResponse, error) {
	var res v1.ReattachRunResponse
	if err := c.client.CallUnary(ctx, criteriaServiceReattachRunSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *criteriaServiceClient) Resume(ctx context.Context, req *v1.ResumeRequest) (*v1.ResumeResponse, error) {
	var res v1.ResumeResponse
	if err := c.client.CallUnary(ctx, criteriaServiceResumeSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *criteriaServiceClient) SubmitEvents(ctx context.Context) (CriteriaServiceSubmitEventsClientStream, error) {
	stream, err := c.client.CallClientStream(ctx, criteriaServiceSubmitEventsSpec())
	if err != nil {
		return CriteriaServiceSubmitEventsClientStream{}, err
	}
	return CriteriaServiceSubmitEventsClientStream{stream: stream}, nil
}

func (c *criteriaServiceClient) Control(ctx context.Context, req *v1.ControlSubscribeRequest) (CriteriaServiceControlClientStream, error) {
	stream, err := c.client.CallServerStream(ctx, criteriaServiceControlSpec(), req)
	if err != nil {
		return CriteriaServiceControlClientStream{}, err
	}
	return CriteriaServiceControlClientStream{stream: stream}, nil
}

type criteriaServiceHandler struct{ svc CriteriaServiceHandler }

func (h criteriaServiceHandler) register(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.RegisterRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Register(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h criteriaServiceHandler) heartbeat(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.HeartbeatRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Heartbeat(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h criteriaServiceHandler) createRun(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.CreateRunRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.CreateRun(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h criteriaServiceHandler) reattachRun(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ReattachRunRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ReattachRun(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h criteriaServiceHandler) resume(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ResumeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Resume(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h criteriaServiceHandler) submitEvents(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	return h.svc.SubmitEvents(ctx, CriteriaServiceSubmitEventsServerStream{stream: stream})
}

func (h criteriaServiceHandler) control(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ControlSubscribeRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	return h.svc.Control(ctx, &req, CriteriaServiceControlServerStream{stream: stream})
}
