// OrchestratorService — operator-facing APIs for reconciling run
// lifecycle directly from Castle (CRI-133). Design note:
// docs/adrs/ADR-0005-orchestrator-event-subscription.md (polling was chosen
// over a server stream).
//
// The read RPCs are observation-only. CancelRun (CRI-142) is the single
// operator-facing write: it stamps a run terminal in Castle when the operator
// deliberately deletes the CriteriaRun, without requiring the owning agent
// to act. It is never anonymously reachable and is not covered by dev-mode
// anonymous reads.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: criteria/v1/orchestrator.proto

package criteriav1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v1 "github.com/brokenbots/criteria/sdk/pb/criteria/v1"
	sync "sync"
)

const (
	// OrchestratorServiceName is the fully-qualified name of the OrchestratorService service.
	OrchestratorServiceName = "criteria.v1.OrchestratorService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrchestratorServiceSubscribeRunEventsProcedure is the procedure name of the OrchestratorService's
	// SubscribeRunEvents RPC.
	OrchestratorServiceSubscribeRunEventsProcedure = "/criteria.v1.OrchestratorService/SubscribeRunEvents"
	// OrchestratorServiceListActiveRunsProcedure is the procedure name of the OrchestratorService's
	// ListActiveRuns RPC.
	OrchestratorServiceListActiveRunsProcedure = "/criteria.v1.OrchestratorService/ListActiveRuns"
	// OrchestratorServiceCancelRunProcedure is the procedure name of the OrchestratorService's
	// CancelRun RPC.
	OrchestratorServiceCancelRunProcedure = "/criteria.v1.OrchestratorService/CancelRun"
)

var (
	orchestratorServiceSubscribeRunEventsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_orchestrator_proto.Services().ByName("OrchestratorService").Methods().ByName("SubscribeRunEvents"),
			Procedure:  OrchestratorServiceSubscribeRunEventsProcedure,
		}
	})
	orchestratorServiceListActiveRunsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_orchestrator_proto.Services().ByName("OrchestratorService").Methods().ByName("ListActiveRuns"),
			Procedure:  OrchestratorServiceListActiveRunsProcedure,
		}
	})
	orchestratorServiceCancelRunSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_criteria_v1_orchestrator_proto.Services().ByName("OrchestratorService").Methods().ByName("CancelRun"),
			Procedure:  OrchestratorServiceCancelRunProcedure,
		}
	})
)

// OrchestratorServiceClient is a client for the criteria.v1.OrchestratorService service.
type OrchestratorServiceClient interface {
	// SubscribeRunEvents returns the persisted events for one run with
	// seq > since_seq, in ascending seq order (CRI-133).
	//
	// Polling semantics: one bounded page per call; the operator re-polls
	// within its reconcile interval. `since_seq` is exclusive — pass 0 to
	// replay the run from the beginning, or the previously returned cursor to
	// resume after an operator restart. Events are durable in the store, so
	// replay is gapless and duplicate-free under interleaved writers.
	//
	// Cursor handling: after consuming a NON-EMPTY page, persist `last_seq`
	// (the highest seq in the page) as the per-run cursor. When the page is
	// empty, keep the previously persisted cursor: `last_seq` is 0 on empty
	// pages and must NOT be persisted, otherwise an idle run would reset its
	// cursor to 0 and replay from the beginning on every reconcile. When the
	// page is full (len(events) == limit), `next_since_seq`
	// is also set so the operator can continue paging immediately; the
	// terminal event of a run is a normal listable event.
	SubscribeRunEvents(context.Context, *v1.SubscribeRunEventsRequest) (*v1.SubscribeRunEventsResponse, error)
	// ListActiveRuns returns runs that have not reached a terminal state
	// (pending | running | paused). This is the discovery step of the operator
	// reconcile loop: subscribe to each returned run with SubscribeRunEvents.
	// Terminal runs (succeeded | failed | cancelled) are excluded; their final
	// events remain pollable via SubscribeRunEvents.
	ListActiveRuns(context.Context, *v1.ListActiveRunsRequest) (*v1.ListActiveRunsResponse, error)
	// CancelRun marks one run terminal (status "cancelled") on the operator's
	// behalf (CRI-142). It exists for deterministic cleanup: when the operator
	// deletes the CriteriaRun, it stamps the Castle run terminal itself instead
	// of waiting for a dead agent's SubmitEvents.
	//
	// Semantics:
	//   - Unknown run_id is NotFound.
	//   - A run already in a terminal state (succeeded | failed | cancelled) is
	//     FailedPrecondition; terminal states are never overwritten.
	//   - The run is stamped "cancelled" with ended_at set and the supplied
	//     reason (default "cancelled by operator") recorded as the run's
	//     failure reason. Any queued or leased workflow assignment for the run
	//     is also marked terminal so the work is never re-dispatched.
	//
	// Auth: orchestrator identities may cancel any run they can observe; agent
	// identities may cancel only runs they own. Anonymous callers are rejected
	// even in dev mode.
	CancelRun(context.Context, *v1.CancelRunRequest) (*v1.CancelRunResponse, error)
}

// NewOrchestratorServiceClient constructs a client for the criteria.v1.OrchestratorService service.
// Multiple service clients may share a single connect.Client.
func NewOrchestratorServiceClient(client *connect.Client) OrchestratorServiceClient {
	return &orchestratorServiceClient{client: client}
}

// OrchestratorServiceHandler is an implementation of the criteria.v1.OrchestratorService service.
type OrchestratorServiceHandler interface {
	// SubscribeRunEvents returns the persisted events for one run with
	// seq > since_seq, in ascending seq order (CRI-133).
	//
	// Polling semantics: one bounded page per call; the operator re-polls
	// within its reconcile interval. `since_seq` is exclusive — pass 0 to
	// replay the run from the beginning, or the previously returned cursor to
	// resume after an operator restart. Events are durable in the store, so
	// replay is gapless and duplicate-free under interleaved writers.
	//
	// Cursor handling: after consuming a NON-EMPTY page, persist `last_seq`
	// (the highest seq in the page) as the per-run cursor. When the page is
	// empty, keep the previously persisted cursor: `last_seq` is 0 on empty
	// pages and must NOT be persisted, otherwise an idle run would reset its
	// cursor to 0 and replay from the beginning on every reconcile. When the
	// page is full (len(events) == limit), `next_since_seq`
	// is also set so the operator can continue paging immediately; the
	// terminal event of a run is a normal listable event.
	SubscribeRunEvents(context.Context, *v1.SubscribeRunEventsRequest) (*v1.SubscribeRunEventsResponse, error)
	// ListActiveRuns returns runs that have not reached a terminal state
	// (pending | running | paused). This is the discovery step of the operator
	// reconcile loop: subscribe to each returned run with SubscribeRunEvents.
	// Terminal runs (succeeded | failed | cancelled) are excluded; their final
	// events remain pollable via SubscribeRunEvents.
	ListActiveRuns(context.Context, *v1.ListActiveRunsRequest) (*v1.ListActiveRunsResponse, error)
	// CancelRun marks one run terminal (status "cancelled") on the operator's
	// behalf (CRI-142). It exists for deterministic cleanup: when the operator
	// deletes the CriteriaRun, it stamps the Castle run terminal itself instead
	// of waiting for a dead agent's SubmitEvents.
	//
	// Semantics:
	//   - Unknown run_id is NotFound.
	//   - A run already in a terminal state (succeeded | failed | cancelled) is
	//     FailedPrecondition; terminal states are never overwritten.
	//   - The run is stamped "cancelled" with ended_at set and the supplied
	//     reason (default "cancelled by operator") recorded as the run's
	//     failure reason. Any queued or leased workflow assignment for the run
	//     is also marked terminal so the work is never re-dispatched.
	//
	// Auth: orchestrator identities may cancel any run they can observe; agent
	// identities may cancel only runs they own. Anonymous callers are rejected
	// even in dev mode.
	CancelRun(context.Context, *v1.CancelRunRequest) (*v1.CancelRunResponse, error)
}

// RegisterOrchestratorServiceHandler registers svc as the criteria.v1.OrchestratorService
// implementation on server.
func RegisterOrchestratorServiceHandler(server *connect.Server, svc OrchestratorServiceHandler) {
	adapter := orchestratorServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: orchestratorServiceSubscribeRunEventsSpec(), Handler: adapter.subscribeRunEvents},
		connect.Method{Spec: orchestratorServiceListActiveRunsSpec(), Handler: adapter.listActiveRuns},
		connect.Method{Spec: orchestratorServiceCancelRunSpec(), Handler: adapter.cancelRun},
	)
}

// UnimplementedOrchestratorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrchestratorServiceHandler struct{}

func (UnimplementedOrchestratorServiceHandler) SubscribeRunEvents(context.Context, *v1.SubscribeRunEventsRequest) (*v1.SubscribeRunEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.OrchestratorService.SubscribeRunEvents is not implemented")
}

func (UnimplementedOrchestratorServiceHandler) ListActiveRuns(context.Context, *v1.ListActiveRunsRequest) (*v1.ListActiveRunsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.OrchestratorService.ListActiveRuns is not implemented")
}

func (UnimplementedOrchestratorServiceHandler) CancelRun(context.Context, *v1.CancelRunRequest) (*v1.CancelRunResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "criteria.v1.OrchestratorService.CancelRun is not implemented")
}

type orchestratorServiceClient struct {
	client *connect.Client
}

func (c *orchestratorServiceClient) SubscribeRunEvents(ctx context.Context, req *v1.SubscribeRunEventsRequest) (*v1.SubscribeRunEventsResponse, error) {
	var res v1.SubscribeRunEventsResponse
	if err := c.client.CallUnary(ctx, orchestratorServiceSubscribeRunEventsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *orchestratorServiceClient) ListActiveRuns(ctx context.Context, req *v1.ListActiveRunsRequest) (*v1.ListActiveRunsResponse, error) {
	var res v1.ListActiveRunsResponse
	if err := c.client.CallUnary(ctx, orchestratorServiceListActiveRunsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *orchestratorServiceClient) CancelRun(ctx context.Context, req *v1.CancelRunRequest) (*v1.CancelRunResponse, error) {
	var res v1.CancelRunResponse
	if err := c.client.CallUnary(ctx, orchestratorServiceCancelRunSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type orchestratorServiceHandler struct{ svc OrchestratorServiceHandler }

func (h orchestratorServiceHandler) subscribeRunEvents(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.SubscribeRunEventsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.SubscribeRunEvents(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h orchestratorServiceHandler) listActiveRuns(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListActiveRunsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListActiveRuns(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h orchestratorServiceHandler) cancelRun(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.CancelRunRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.CancelRun(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
