// OrchestratorService — operator-facing APIs for reconciling run
// lifecycle directly from Castle (CRI-133). Design note:
// docs/adrs/ADR-0005-orchestrator-event-subscription.md (polling was chosen
// over a server stream).
//
// The read RPCs are observation-only. CancelRun (CRI-142) is the single
// operator-facing write: it stamps a run terminal in Castle when the operator
// deliberately deletes the CriteriaRun, without requiring the owning agent
// to act. It is never anonymously reachable and is not covered by dev-mode
// anonymous reads.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: criteria/v1/orchestrator.proto

package criteriav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/criteria/sdk/pb/criteria/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrchestratorServiceName is the fully-qualified name of the OrchestratorService service.
	OrchestratorServiceName = "criteria.v1.OrchestratorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrchestratorServiceSubscribeRunEventsProcedure is the fully-qualified name of the
	// OrchestratorService's SubscribeRunEvents RPC.
	OrchestratorServiceSubscribeRunEventsProcedure = "/criteria.v1.OrchestratorService/SubscribeRunEvents"
	// OrchestratorServiceListActiveRunsProcedure is the fully-qualified name of the
	// OrchestratorService's ListActiveRuns RPC.
	OrchestratorServiceListActiveRunsProcedure = "/criteria.v1.OrchestratorService/ListActiveRuns"
	// OrchestratorServiceCancelRunProcedure is the fully-qualified name of the OrchestratorService's
	// CancelRun RPC.
	OrchestratorServiceCancelRunProcedure = "/criteria.v1.OrchestratorService/CancelRun"
)

// OrchestratorServiceClient is a client for the criteria.v1.OrchestratorService service.
type OrchestratorServiceClient interface {
	// SubscribeRunEvents returns the persisted events for one run with
	// seq > since_seq, in ascending seq order (CRI-133).
	//
	// Polling semantics: one bounded page per call; the operator re-polls
	// within its reconcile interval. `since_seq` is exclusive — pass 0 to
	// replay the run from the beginning, or the previously returned cursor to
	// resume after an operator restart. Events are durable in the store, so
	// replay is gapless and duplicate-free under interleaved writers.
	//
	// Cursor handling: after consuming a NON-EMPTY page, persist `last_seq`
	// (the highest seq in the page) as the per-run cursor. When the page is
	// empty, keep the previously persisted cursor: `last_seq` is 0 on empty
	// pages and must NOT be persisted, otherwise an idle run would reset its
	// cursor to 0 and replay from the beginning on every reconcile. When the
	// page is full (len(events) == limit), `next_since_seq`
	// is also set so the operator can continue paging immediately; the
	// terminal event of a run is a normal listable event.
	SubscribeRunEvents(context.Context, *connect.Request[v1.SubscribeRunEventsRequest]) (*connect.Response[v1.SubscribeRunEventsResponse], error)
	// ListActiveRuns returns runs that have not reached a terminal state
	// (pending | running | paused). This is the discovery step of the operator
	// reconcile loop: subscribe to each returned run with SubscribeRunEvents.
	// Terminal runs (succeeded | failed | cancelled) are excluded; their final
	// events remain pollable via SubscribeRunEvents.
	ListActiveRuns(context.Context, *connect.Request[v1.ListActiveRunsRequest]) (*connect.Response[v1.ListActiveRunsResponse], error)
	// CancelRun marks one run terminal (status "cancelled") on the operator's
	// behalf (CRI-142). It exists for deterministic cleanup: when the operator
	// deletes the CriteriaRun, it stamps the Castle run terminal itself instead
	// of waiting for a dead agent's SubmitEvents.
	//
	// Semantics:
	//   - Unknown run_id is NotFound.
	//   - A run already in a terminal state (succeeded | failed | cancelled) is
	//     FailedPrecondition; terminal states are never overwritten.
	//   - The run is stamped "cancelled" with ended_at set and the supplied
	//     reason (default "cancelled by operator") recorded as the run's
	//     failure reason. Any queued or leased workflow assignment for the run
	//     is also marked terminal so the work is never re-dispatched.
	//
	// Auth: orchestrator identities may cancel any run they can observe; agent
	// identities may cancel only runs they own. Anonymous callers are rejected
	// even in dev mode.
	CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error)
}

// NewOrchestratorServiceClient constructs a client for the criteria.v1.OrchestratorService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrchestratorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrchestratorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orchestratorServiceMethods := v1.File_criteria_v1_orchestrator_proto.Services().ByName("OrchestratorService").Methods()
	return &orchestratorServiceClient{
		subscribeRunEvents: connect.NewClient[v1.SubscribeRunEventsRequest, v1.SubscribeRunEventsResponse](
			httpClient,
			baseURL+OrchestratorServiceSubscribeRunEventsProcedure,
			connect.WithSchema(orchestratorServiceMethods.ByName("SubscribeRunEvents")),
			connect.WithClientOptions(opts...),
		),
		listActiveRuns: connect.NewClient[v1.ListActiveRunsRequest, v1.ListActiveRunsResponse](
			httpClient,
			baseURL+OrchestratorServiceListActiveRunsProcedure,
			connect.WithSchema(orchestratorServiceMethods.ByName("ListActiveRuns")),
			connect.WithClientOptions(opts...),
		),
		cancelRun: connect.NewClient[v1.CancelRunRequest, v1.CancelRunResponse](
			httpClient,
			baseURL+OrchestratorServiceCancelRunProcedure,
			connect.WithSchema(orchestratorServiceMethods.ByName("CancelRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orchestratorServiceClient implements OrchestratorServiceClient.
type orchestratorServiceClient struct {
	subscribeRunEvents *connect.Client[v1.SubscribeRunEventsRequest, v1.SubscribeRunEventsResponse]
	listActiveRuns     *connect.Client[v1.ListActiveRunsRequest, v1.ListActiveRunsResponse]
	cancelRun          *connect.Client[v1.CancelRunRequest, v1.CancelRunResponse]
}

// SubscribeRunEvents calls criteria.v1.OrchestratorService.SubscribeRunEvents.
func (c *orchestratorServiceClient) SubscribeRunEvents(ctx context.Context, req *connect.Request[v1.SubscribeRunEventsRequest]) (*connect.Response[v1.SubscribeRunEventsResponse], error) {
	return c.subscribeRunEvents.CallUnary(ctx, req)
}

// ListActiveRuns calls criteria.v1.OrchestratorService.ListActiveRuns.
func (c *orchestratorServiceClient) ListActiveRuns(ctx context.Context, req *connect.Request[v1.ListActiveRunsRequest]) (*connect.Response[v1.ListActiveRunsResponse], error) {
	return c.listActiveRuns.CallUnary(ctx, req)
}

// CancelRun calls criteria.v1.OrchestratorService.CancelRun.
func (c *orchestratorServiceClient) CancelRun(ctx context.Context, req *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error) {
	return c.cancelRun.CallUnary(ctx, req)
}

// OrchestratorServiceHandler is an implementation of the criteria.v1.OrchestratorService service.
type OrchestratorServiceHandler interface {
	// SubscribeRunEvents returns the persisted events for one run with
	// seq > since_seq, in ascending seq order (CRI-133).
	//
	// Polling semantics: one bounded page per call; the operator re-polls
	// within its reconcile interval. `since_seq` is exclusive — pass 0 to
	// replay the run from the beginning, or the previously returned cursor to
	// resume after an operator restart. Events are durable in the store, so
	// replay is gapless and duplicate-free under interleaved writers.
	//
	// Cursor handling: after consuming a NON-EMPTY page, persist `last_seq`
	// (the highest seq in the page) as the per-run cursor. When the page is
	// empty, keep the previously persisted cursor: `last_seq` is 0 on empty
	// pages and must NOT be persisted, otherwise an idle run would reset its
	// cursor to 0 and replay from the beginning on every reconcile. When the
	// page is full (len(events) == limit), `next_since_seq`
	// is also set so the operator can continue paging immediately; the
	// terminal event of a run is a normal listable event.
	SubscribeRunEvents(context.Context, *connect.Request[v1.SubscribeRunEventsRequest]) (*connect.Response[v1.SubscribeRunEventsResponse], error)
	// ListActiveRuns returns runs that have not reached a terminal state
	// (pending | running | paused). This is the discovery step of the operator
	// reconcile loop: subscribe to each returned run with SubscribeRunEvents.
	// Terminal runs (succeeded | failed | cancelled) are excluded; their final
	// events remain pollable via SubscribeRunEvents.
	ListActiveRuns(context.Context, *connect.Request[v1.ListActiveRunsRequest]) (*connect.Response[v1.ListActiveRunsResponse], error)
	// CancelRun marks one run terminal (status "cancelled") on the operator's
	// behalf (CRI-142). It exists for deterministic cleanup: when the operator
	// deletes the CriteriaRun, it stamps the Castle run terminal itself instead
	// of waiting for a dead agent's SubmitEvents.
	//
	// Semantics:
	//   - Unknown run_id is NotFound.
	//   - A run already in a terminal state (succeeded | failed | cancelled) is
	//     FailedPrecondition; terminal states are never overwritten.
	//   - The run is stamped "cancelled" with ended_at set and the supplied
	//     reason (default "cancelled by operator") recorded as the run's
	//     failure reason. Any queued or leased workflow assignment for the run
	//     is also marked terminal so the work is never re-dispatched.
	//
	// Auth: orchestrator identities may cancel any run they can observe; agent
	// identities may cancel only runs they own. Anonymous callers are rejected
	// even in dev mode.
	CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error)
}

// NewOrchestratorServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrchestratorServiceHandler(svc OrchestratorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orchestratorServiceMethods := v1.File_criteria_v1_orchestrator_proto.Services().ByName("OrchestratorService").Methods()
	orchestratorServiceSubscribeRunEventsHandler := connect.NewUnaryHandler(
		OrchestratorServiceSubscribeRunEventsProcedure,
		svc.SubscribeRunEvents,
		connect.WithSchema(orchestratorServiceMethods.ByName("SubscribeRunEvents")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorServiceListActiveRunsHandler := connect.NewUnaryHandler(
		OrchestratorServiceListActiveRunsProcedure,
		svc.ListActiveRuns,
		connect.WithSchema(orchestratorServiceMethods.ByName("ListActiveRuns")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorServiceCancelRunHandler := connect.NewUnaryHandler(
		OrchestratorServiceCancelRunProcedure,
		svc.CancelRun,
		connect.WithSchema(orchestratorServiceMethods.ByName("CancelRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/criteria.v1.OrchestratorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrchestratorServiceSubscribeRunEventsProcedure:
			orchestratorServiceSubscribeRunEventsHandler.ServeHTTP(w, r)
		case OrchestratorServiceListActiveRunsProcedure:
			orchestratorServiceListActiveRunsHandler.ServeHTTP(w, r)
		case OrchestratorServiceCancelRunProcedure:
			orchestratorServiceCancelRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrchestratorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrchestratorServiceHandler struct{}

func (UnimplementedOrchestratorServiceHandler) SubscribeRunEvents(context.Context, *connect.Request[v1.SubscribeRunEventsRequest]) (*connect.Response[v1.SubscribeRunEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.OrchestratorService.SubscribeRunEvents is not implemented"))
}

func (UnimplementedOrchestratorServiceHandler) ListActiveRuns(context.Context, *connect.Request[v1.ListActiveRunsRequest]) (*connect.Response[v1.ListActiveRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.OrchestratorService.ListActiveRuns is not implemented"))
}

func (UnimplementedOrchestratorServiceHandler) CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.OrchestratorService.CancelRun is not implemented"))
}
