// PeerService — host->peer supervision journal (ADR-0007 Stage A).
//
// Stage A supervision truth: process-lifecycle facts cross the wire as
// first-class typed events instead of being inferred from gRPC transport
// errors. The peer (a remote Criteria or adapter host process) is the gRPC
// server on the phone-home connection; the host opens Supervise and reads
// the lifecycle journal.
//
// Evolution discipline (additive-only):
//   - Field numbers in this file are permanent once assigned. Never reuse,
//     renumber, or re-type an existing field; only ever append.
//   - The next free `kind` oneof arm in SupervisionEvent is field 11. Do NOT
//     `reserved` forward numbers — reserve only genuinely abandoned ones.
//   - Stage B run-graph events ride THIS journal: extend SupervisionEvent
//     with new arms; do not fork a second supervision stream or file.
//   - Supervision protocol evolution is negotiated via capabilities strings,
//     not proto package churn: `criteria.v1` stays.
//
// Delivery semantics:
//   - At-least-once delivery. Consumers dedup on (peer conn identity,
//     event_seq).
//   - event_seq is global monotonic per peer process and gapless.
//   - Replay: a host (re-)opening Supervise passes since_event_seq; the peer
//     streams lifecycle truth strictly after that value (exclusive).
//   - Terminal events (ProcessExited, CrashClassified) persist to a bounded
//     in-peer journal (default 4096 events, env-tunable) and are replayed
//     FIRST on reconnect, so crash evidence survives the RPC stream that
//     died.
//
// Ordering:
//   - Journal append order == emission order.
//   - StreamFlushed.up_to_seq is monotonic per channel.
//
// Heartbeat:
//   - Supervise emits SupervisionHeartbeat every 30s while idle. It
//     complements, and does not replace, the CRI-276 transport keepalive.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: criteria/v1/peer.proto

package criteriav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/brokenbots/criteria/sdk/pb/criteria/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PeerServiceName is the fully-qualified name of the PeerService service.
	PeerServiceName = "criteria.v1.PeerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PeerServiceSuperviseProcedure is the fully-qualified name of the PeerService's Supervise RPC.
	PeerServiceSuperviseProcedure = "/criteria.v1.PeerService/Supervise"
	// PeerServiceControlProcedure is the fully-qualified name of the PeerService's Control RPC.
	PeerServiceControlProcedure = "/criteria.v1.PeerService/Control"
)

// PeerServiceClient is a client for the criteria.v1.PeerService service.
type PeerServiceClient interface {
	// Host->peer: open/reopen supervision. The peer streams lifecycle truth
	// strictly after since_event_seq (exclusive). Host-initiated: the
	// phone-home conn has the peer as gRPC server.
	Supervise(context.Context, *connect.Request[v1.SupervisionRequest]) (*connect.ServerStreamForClient[v1.SupervisionEvent], error)
	// Host->peer control plane (Stage A: kill child; future: respawn, detach).
	Control(context.Context, *connect.Request[v1.ControlRequest]) (*connect.Response[v1.ControlResponse], error)
}

// NewPeerServiceClient constructs a client for the criteria.v1.PeerService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPeerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PeerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	peerServiceMethods := v1.File_criteria_v1_peer_proto.Services().ByName("PeerService").Methods()
	return &peerServiceClient{
		supervise: connect.NewClient[v1.SupervisionRequest, v1.SupervisionEvent](
			httpClient,
			baseURL+PeerServiceSuperviseProcedure,
			connect.WithSchema(peerServiceMethods.ByName("Supervise")),
			connect.WithClientOptions(opts...),
		),
		control: connect.NewClient[v1.ControlRequest, v1.ControlResponse](
			httpClient,
			baseURL+PeerServiceControlProcedure,
			connect.WithSchema(peerServiceMethods.ByName("Control")),
			connect.WithClientOptions(opts...),
		),
	}
}

// peerServiceClient implements PeerServiceClient.
type peerServiceClient struct {
	supervise *connect.Client[v1.SupervisionRequest, v1.SupervisionEvent]
	control   *connect.Client[v1.ControlRequest, v1.ControlResponse]
}

// Supervise calls criteria.v1.PeerService.Supervise.
func (c *peerServiceClient) Supervise(ctx context.Context, req *connect.Request[v1.SupervisionRequest]) (*connect.ServerStreamForClient[v1.SupervisionEvent], error) {
	return c.supervise.CallServerStream(ctx, req)
}

// Control calls criteria.v1.PeerService.Control.
func (c *peerServiceClient) Control(ctx context.Context, req *connect.Request[v1.ControlRequest]) (*connect.Response[v1.ControlResponse], error) {
	return c.control.CallUnary(ctx, req)
}

// PeerServiceHandler is an implementation of the criteria.v1.PeerService service.
type PeerServiceHandler interface {
	// Host->peer: open/reopen supervision. The peer streams lifecycle truth
	// strictly after since_event_seq (exclusive). Host-initiated: the
	// phone-home conn has the peer as gRPC server.
	Supervise(context.Context, *connect.Request[v1.SupervisionRequest], *connect.ServerStream[v1.SupervisionEvent]) error
	// Host->peer control plane (Stage A: kill child; future: respawn, detach).
	Control(context.Context, *connect.Request[v1.ControlRequest]) (*connect.Response[v1.ControlResponse], error)
}

// NewPeerServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPeerServiceHandler(svc PeerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	peerServiceMethods := v1.File_criteria_v1_peer_proto.Services().ByName("PeerService").Methods()
	peerServiceSuperviseHandler := connect.NewServerStreamHandler(
		PeerServiceSuperviseProcedure,
		svc.Supervise,
		connect.WithSchema(peerServiceMethods.ByName("Supervise")),
		connect.WithHandlerOptions(opts...),
	)
	peerServiceControlHandler := connect.NewUnaryHandler(
		PeerServiceControlProcedure,
		svc.Control,
		connect.WithSchema(peerServiceMethods.ByName("Control")),
		connect.WithHandlerOptions(opts...),
	)
	return "/criteria.v1.PeerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PeerServiceSuperviseProcedure:
			peerServiceSuperviseHandler.ServeHTTP(w, r)
		case PeerServiceControlProcedure:
			peerServiceControlHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPeerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPeerServiceHandler struct{}

func (UnimplementedPeerServiceHandler) Supervise(context.Context, *connect.Request[v1.SupervisionRequest], *connect.ServerStream[v1.SupervisionEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.PeerService.Supervise is not implemented"))
}

func (UnimplementedPeerServiceHandler) Control(context.Context, *connect.Request[v1.ControlRequest]) (*connect.Response[v1.ControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("criteria.v1.PeerService.Control is not implemented"))
}
