// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/adapter_plugin.proto

package overseerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{0}
}

// ConfigFieldProto describes a single field in an adapter's config or input schema.
// Added in W02; all field numbers are permanent.
type ConfigFieldProto struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Required bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"` // permanent
	// type is one of: "string", "number", "bool", "list_string"
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // permanent
	Doc           string `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`   // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldProto) Reset() {
	*x = ConfigFieldProto{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldProto) ProtoMessage() {}

func (x *ConfigFieldProto) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldProto.ProtoReflect.Descriptor instead.
func (*ConfigFieldProto) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigFieldProto) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigFieldProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigFieldProto) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

// AdapterSchemaProto holds a named set of config fields for schema validation.
// Added in W02; all field numbers are permanent.
type AdapterSchemaProto struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Fields        map[string]*ConfigFieldProto `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterSchemaProto) Reset() {
	*x = AdapterSchemaProto{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterSchemaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterSchemaProto) ProtoMessage() {}

func (x *AdapterSchemaProto) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterSchemaProto.ProtoReflect.Descriptor instead.
func (*AdapterSchemaProto) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *AdapterSchemaProto) GetFields() map[string]*ConfigFieldProto {
	if x != nil {
		return x.Fields
	}
	return nil
}

type InfoResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                 // permanent
	Version      string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`           // permanent
	Capabilities []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // permanent
	// config_schema and input_schema were added in W02. Legacy plugins that do
	// not return these fields will be treated as permissive (any keys accepted).
	ConfigSchema  *AdapterSchemaProto `protobuf:"bytes,4,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"` // permanent (W02)
	InputSchema   *AdapterSchemaProto `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`    // permanent (W02)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *InfoResponse) GetConfigSchema() *AdapterSchemaProto {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *InfoResponse) GetInputSchema() *AdapterSchemaProto {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                    // permanent
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *OpenSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenSessionRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{5}
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                    // permanent
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`                                                       // permanent
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecuteRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExecuteEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteEvent_Log
	//	*ExecuteEvent_Adapter
	//	*ExecuteEvent_Permission
	//	*ExecuteEvent_Result
	Event         isExecuteEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteEvent) GetEvent() isExecuteEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteEvent) GetLog() *LogEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ExecuteEvent) GetAdapter() *AdapterEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Adapter); ok {
			return x.Adapter
		}
	}
	return nil
}

func (x *ExecuteEvent) GetPermission() *PermissionRequest {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Permission); ok {
			return x.Permission
		}
	}
	return nil
}

func (x *ExecuteEvent) GetResult() *ExecuteResult {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isExecuteEvent_Event interface {
	isExecuteEvent_Event()
}

type ExecuteEvent_Log struct {
	Log *LogEvent `protobuf:"bytes,1,opt,name=log,proto3,oneof"` // permanent
}

type ExecuteEvent_Adapter struct {
	Adapter *AdapterEvent `protobuf:"bytes,2,opt,name=adapter,proto3,oneof"` // permanent
}

type ExecuteEvent_Permission struct {
	Permission *PermissionRequest `protobuf:"bytes,3,opt,name=permission,proto3,oneof"` // permanent
}

type ExecuteEvent_Result struct {
	Result *ExecuteResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"` // permanent
}

func (*ExecuteEvent_Log) isExecuteEvent_Event() {}

func (*ExecuteEvent_Adapter) isExecuteEvent_Event() {}

func (*ExecuteEvent_Permission) isExecuteEvent_Event() {}

func (*ExecuteEvent_Result) isExecuteEvent_Event() {}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"` // permanent
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`   // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *LogEvent) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEvent) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                     // permanent
	Permission    string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`                                                                     // permanent
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *PermissionRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ExecuteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`                                                                           // permanent
	Outputs       map[string]string      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // permanent (W04)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ExecuteResult) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type PermitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // permanent
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"` // permanent
	Allow         bool                   `protobuf:"varint,3,opt,name=allow,proto3" json:"allow,omitempty"`                                  // permanent
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                 // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermitRequest) Reset() {
	*x = PermitRequest{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitRequest) ProtoMessage() {}

func (x *PermitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitRequest.ProtoReflect.Descriptor instead.
func (*PermitRequest) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PermitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PermitRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *PermitRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *PermitRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PermitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermitResponse) Reset() {
	*x = PermitResponse{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitResponse) ProtoMessage() {}

func (x *PermitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitResponse.ProtoReflect.Descriptor instead.
func (*PermitResponse) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{12}
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_v1_adapter_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_adapter_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_adapter_plugin_proto_rawDescGZIP(), []int{14}
}

var File_v1_adapter_plugin_proto protoreflect.FileDescriptor

const file_v1_adapter_plugin_proto_rawDesc = "" +
	"\n" +
	"\x17v1/adapter_plugin.proto\x12\voverseer.v1\x1a\x0fv1/events.proto\"\r\n" +
	"\vInfoRequest\"T\n" +
	"\x10ConfigFieldProto\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\"\xb3\x01\n" +
	"\x12AdapterSchemaProto\x12C\n" +
	"\x06fields\x18\x01 \x03(\v2+.overseer.v1.AdapterSchemaProto.FieldsEntryR\x06fields\x1aX\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.overseer.v1.ConfigFieldProtoR\x05value:\x028\x01\"\xea\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12D\n" +
	"\rconfig_schema\x18\x04 \x01(\v2\x1f.overseer.v1.AdapterSchemaProtoR\fconfigSchema\x12B\n" +
	"\finput_schema\x18\x05 \x01(\v2\x1f.overseer.v1.AdapterSchemaProtoR\vinputSchema\"\xb3\x01\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12C\n" +
	"\x06config\x18\x02 \x03(\v2+.overseer.v1.OpenSessionRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13OpenSessionResponse\"\xc8\x01\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12?\n" +
	"\x06config\x18\x03 \x03(\v2'.overseer.v1.ExecuteRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\fExecuteEvent\x12)\n" +
	"\x03log\x18\x01 \x01(\v2\x15.overseer.v1.LogEventH\x00R\x03log\x125\n" +
	"\aadapter\x18\x02 \x01(\v2\x19.overseer.v1.AdapterEventH\x00R\aadapter\x12@\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x1e.overseer.v1.PermissionRequestH\x00R\n" +
	"permission\x124\n" +
	"\x06result\x18\x04 \x01(\v2\x1a.overseer.v1.ExecuteResultH\x00R\x06resultB\a\n" +
	"\x05event\"8\n" +
	"\bLogEvent\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"\xc6\x01\n" +
	"\x11PermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\x12E\n" +
	"\adetails\x18\x03 \x03(\v2+.overseer.v1.PermissionRequest.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\rExecuteResult\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12A\n" +
	"\aoutputs\x18\x02 \x03(\v2'.overseer.v1.ExecuteResult.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\rPermitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12\x14\n" +
	"\x05allow\x18\x03 \x01(\bR\x05allow\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x10\n" +
	"\x0ePermitResponse\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse2\x82\x03\n" +
	"\x14AdapterPluginService\x12;\n" +
	"\x04Info\x12\x18.overseer.v1.InfoRequest\x1a\x19.overseer.v1.InfoResponse\x12P\n" +
	"\vOpenSession\x12\x1f.overseer.v1.OpenSessionRequest\x1a .overseer.v1.OpenSessionResponse\x12C\n" +
	"\aExecute\x12\x1b.overseer.v1.ExecuteRequest\x1a\x19.overseer.v1.ExecuteEvent0\x01\x12A\n" +
	"\x06Permit\x12\x1a.overseer.v1.PermitRequest\x1a\x1b.overseer.v1.PermitResponse\x12S\n" +
	"\fCloseSession\x12 .overseer.v1.CloseSessionRequest\x1a!.overseer.v1.CloseSessionResponseB5Z3github.com/brokenbots/overseer/sdk/pb/v1;overseerv1b\x06proto3"

var (
	file_v1_adapter_plugin_proto_rawDescOnce sync.Once
	file_v1_adapter_plugin_proto_rawDescData []byte
)

func file_v1_adapter_plugin_proto_rawDescGZIP() []byte {
	file_v1_adapter_plugin_proto_rawDescOnce.Do(func() {
		file_v1_adapter_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_adapter_plugin_proto_rawDesc), len(file_v1_adapter_plugin_proto_rawDesc)))
	})
	return file_v1_adapter_plugin_proto_rawDescData
}

var file_v1_adapter_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v1_adapter_plugin_proto_goTypes = []any{
	(*InfoRequest)(nil),          // 0: overseer.v1.InfoRequest
	(*ConfigFieldProto)(nil),     // 1: overseer.v1.ConfigFieldProto
	(*AdapterSchemaProto)(nil),   // 2: overseer.v1.AdapterSchemaProto
	(*InfoResponse)(nil),         // 3: overseer.v1.InfoResponse
	(*OpenSessionRequest)(nil),   // 4: overseer.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),  // 5: overseer.v1.OpenSessionResponse
	(*ExecuteRequest)(nil),       // 6: overseer.v1.ExecuteRequest
	(*ExecuteEvent)(nil),         // 7: overseer.v1.ExecuteEvent
	(*LogEvent)(nil),             // 8: overseer.v1.LogEvent
	(*PermissionRequest)(nil),    // 9: overseer.v1.PermissionRequest
	(*ExecuteResult)(nil),        // 10: overseer.v1.ExecuteResult
	(*PermitRequest)(nil),        // 11: overseer.v1.PermitRequest
	(*PermitResponse)(nil),       // 12: overseer.v1.PermitResponse
	(*CloseSessionRequest)(nil),  // 13: overseer.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 14: overseer.v1.CloseSessionResponse
	nil,                          // 15: overseer.v1.AdapterSchemaProto.FieldsEntry
	nil,                          // 16: overseer.v1.OpenSessionRequest.ConfigEntry
	nil,                          // 17: overseer.v1.ExecuteRequest.ConfigEntry
	nil,                          // 18: overseer.v1.PermissionRequest.DetailsEntry
	nil,                          // 19: overseer.v1.ExecuteResult.OutputsEntry
	(*AdapterEvent)(nil),         // 20: overseer.v1.AdapterEvent
}
var file_v1_adapter_plugin_proto_depIdxs = []int32{
	15, // 0: overseer.v1.AdapterSchemaProto.fields:type_name -> overseer.v1.AdapterSchemaProto.FieldsEntry
	2,  // 1: overseer.v1.InfoResponse.config_schema:type_name -> overseer.v1.AdapterSchemaProto
	2,  // 2: overseer.v1.InfoResponse.input_schema:type_name -> overseer.v1.AdapterSchemaProto
	16, // 3: overseer.v1.OpenSessionRequest.config:type_name -> overseer.v1.OpenSessionRequest.ConfigEntry
	17, // 4: overseer.v1.ExecuteRequest.config:type_name -> overseer.v1.ExecuteRequest.ConfigEntry
	8,  // 5: overseer.v1.ExecuteEvent.log:type_name -> overseer.v1.LogEvent
	20, // 6: overseer.v1.ExecuteEvent.adapter:type_name -> overseer.v1.AdapterEvent
	9,  // 7: overseer.v1.ExecuteEvent.permission:type_name -> overseer.v1.PermissionRequest
	10, // 8: overseer.v1.ExecuteEvent.result:type_name -> overseer.v1.ExecuteResult
	18, // 9: overseer.v1.PermissionRequest.details:type_name -> overseer.v1.PermissionRequest.DetailsEntry
	19, // 10: overseer.v1.ExecuteResult.outputs:type_name -> overseer.v1.ExecuteResult.OutputsEntry
	1,  // 11: overseer.v1.AdapterSchemaProto.FieldsEntry.value:type_name -> overseer.v1.ConfigFieldProto
	0,  // 12: overseer.v1.AdapterPluginService.Info:input_type -> overseer.v1.InfoRequest
	4,  // 13: overseer.v1.AdapterPluginService.OpenSession:input_type -> overseer.v1.OpenSessionRequest
	6,  // 14: overseer.v1.AdapterPluginService.Execute:input_type -> overseer.v1.ExecuteRequest
	11, // 15: overseer.v1.AdapterPluginService.Permit:input_type -> overseer.v1.PermitRequest
	13, // 16: overseer.v1.AdapterPluginService.CloseSession:input_type -> overseer.v1.CloseSessionRequest
	3,  // 17: overseer.v1.AdapterPluginService.Info:output_type -> overseer.v1.InfoResponse
	5,  // 18: overseer.v1.AdapterPluginService.OpenSession:output_type -> overseer.v1.OpenSessionResponse
	7,  // 19: overseer.v1.AdapterPluginService.Execute:output_type -> overseer.v1.ExecuteEvent
	12, // 20: overseer.v1.AdapterPluginService.Permit:output_type -> overseer.v1.PermitResponse
	14, // 21: overseer.v1.AdapterPluginService.CloseSession:output_type -> overseer.v1.CloseSessionResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_adapter_plugin_proto_init() }
func file_v1_adapter_plugin_proto_init() {
	if File_v1_adapter_plugin_proto != nil {
		return
	}
	file_v1_events_proto_init()
	file_v1_adapter_plugin_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecuteEvent_Log)(nil),
		(*ExecuteEvent_Adapter)(nil),
		(*ExecuteEvent_Permission)(nil),
		(*ExecuteEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_adapter_plugin_proto_rawDesc), len(file_v1_adapter_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_adapter_plugin_proto_goTypes,
		DependencyIndexes: file_v1_adapter_plugin_proto_depIdxs,
		MessageInfos:      file_v1_adapter_plugin_proto_msgTypes,
	}.Build()
	File_v1_adapter_plugin_proto = out.File
	file_v1_adapter_plugin_proto_goTypes = nil
	file_v1_adapter_plugin_proto_depIdxs = nil
}
