// Overlord event schema.
//
// The `Envelope` message is the wire format for every event flowing between
// Overseer, Castle, and Parapet. Field numbers in `payload` are **stable** once
// assigned — see WORKSTREAM Phase 1.1 §3.1. A new event type must use the next
// unused field number and never reuse an old one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/events.proto

package overseerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogStream identifies which stream a StepLog chunk came from.
type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
	LogStream_LOG_STREAM_AGENT       LogStream = 3
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
		3: "LOG_STREAM_AGENT",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
		"LOG_STREAM_AGENT":       3,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_events_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_v1_events_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{0}
}

// Envelope is the wire format for every event.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version. Always 1 for this package; bump only with a new
	// `overlord.vN` package.
	SchemaVersion int32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Run the event belongs to.
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Castle-assigned monotonic sequence number per run_id. 0 when an Overseer
	// submits; Castle stamps the real value before persistence and fan-out.
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Event timestamp (UTC).
	Ts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	// Optional correlation id used to match a SubmitEvents envelope with its Ack.
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Typed payload. Field numbers here are permanent.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_RunStarted
	//	*Envelope_RunCompleted
	//	*Envelope_RunFailed
	//	*Envelope_StepEntered
	//	*Envelope_StepOutcome
	//	*Envelope_StepTransition
	//	*Envelope_StepLog
	//	*Envelope_AdapterEvent
	//	*Envelope_OverseerHeartbeat
	//	*Envelope_OverseerDisconnected
	//	*Envelope_StepResumed
	//	*Envelope_VariableSet
	//	*Envelope_StepOutputCaptured
	//	*Envelope_WaitEntered
	//	*Envelope_WaitResumed
	//	*Envelope_ApprovalRequested
	//	*Envelope_ApprovalDecision
	//	*Envelope_BranchEvaluated
	//	*Envelope_ForEachEntered
	//	*Envelope_ForEachIteration
	//	*Envelope_ForEachOutcome
	//	*Envelope_ScopeIterCursorSet
	//	*Envelope_WatchReady
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Envelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRunStarted() *RunStarted {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RunStarted); ok {
			return x.RunStarted
		}
	}
	return nil
}

func (x *Envelope) GetRunCompleted() *RunCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RunCompleted); ok {
			return x.RunCompleted
		}
	}
	return nil
}

func (x *Envelope) GetRunFailed() *RunFailed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RunFailed); ok {
			return x.RunFailed
		}
	}
	return nil
}

func (x *Envelope) GetStepEntered() *StepEntered {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepEntered); ok {
			return x.StepEntered
		}
	}
	return nil
}

func (x *Envelope) GetStepOutcome() *StepOutcome {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepOutcome); ok {
			return x.StepOutcome
		}
	}
	return nil
}

func (x *Envelope) GetStepTransition() *StepTransition {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepTransition); ok {
			return x.StepTransition
		}
	}
	return nil
}

func (x *Envelope) GetStepLog() *StepLog {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepLog); ok {
			return x.StepLog
		}
	}
	return nil
}

func (x *Envelope) GetAdapterEvent() *AdapterEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AdapterEvent); ok {
			return x.AdapterEvent
		}
	}
	return nil
}

func (x *Envelope) GetOverseerHeartbeat() *OverseerHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OverseerHeartbeat); ok {
			return x.OverseerHeartbeat
		}
	}
	return nil
}

func (x *Envelope) GetOverseerDisconnected() *OverseerDisconnected {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OverseerDisconnected); ok {
			return x.OverseerDisconnected
		}
	}
	return nil
}

func (x *Envelope) GetStepResumed() *StepResumed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepResumed); ok {
			return x.StepResumed
		}
	}
	return nil
}

func (x *Envelope) GetVariableSet() *VariableSet {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_VariableSet); ok {
			return x.VariableSet
		}
	}
	return nil
}

func (x *Envelope) GetStepOutputCaptured() *StepOutputCaptured {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepOutputCaptured); ok {
			return x.StepOutputCaptured
		}
	}
	return nil
}

func (x *Envelope) GetWaitEntered() *WaitEntered {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WaitEntered); ok {
			return x.WaitEntered
		}
	}
	return nil
}

func (x *Envelope) GetWaitResumed() *WaitResumed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WaitResumed); ok {
			return x.WaitResumed
		}
	}
	return nil
}

func (x *Envelope) GetApprovalRequested() *ApprovalRequested {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ApprovalRequested); ok {
			return x.ApprovalRequested
		}
	}
	return nil
}

func (x *Envelope) GetApprovalDecision() *ApprovalDecision {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ApprovalDecision); ok {
			return x.ApprovalDecision
		}
	}
	return nil
}

func (x *Envelope) GetBranchEvaluated() *BranchEvaluated {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BranchEvaluated); ok {
			return x.BranchEvaluated
		}
	}
	return nil
}

func (x *Envelope) GetForEachEntered() *ForEachEntered {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ForEachEntered); ok {
			return x.ForEachEntered
		}
	}
	return nil
}

func (x *Envelope) GetForEachIteration() *ForEachIteration {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ForEachIteration); ok {
			return x.ForEachIteration
		}
	}
	return nil
}

func (x *Envelope) GetForEachOutcome() *ForEachOutcome {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ForEachOutcome); ok {
			return x.ForEachOutcome
		}
	}
	return nil
}

func (x *Envelope) GetScopeIterCursorSet() *ScopeIterCursorSet {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ScopeIterCursorSet); ok {
			return x.ScopeIterCursorSet
		}
	}
	return nil
}

func (x *Envelope) GetWatchReady() *WatchReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WatchReady); ok {
			return x.WatchReady
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_RunStarted struct {
	RunStarted *RunStarted `protobuf:"bytes,10,opt,name=run_started,json=runStarted,proto3,oneof"`
}

type Envelope_RunCompleted struct {
	RunCompleted *RunCompleted `protobuf:"bytes,11,opt,name=run_completed,json=runCompleted,proto3,oneof"`
}

type Envelope_RunFailed struct {
	RunFailed *RunFailed `protobuf:"bytes,12,opt,name=run_failed,json=runFailed,proto3,oneof"`
}

type Envelope_StepEntered struct {
	StepEntered *StepEntered `protobuf:"bytes,13,opt,name=step_entered,json=stepEntered,proto3,oneof"`
}

type Envelope_StepOutcome struct {
	StepOutcome *StepOutcome `protobuf:"bytes,14,opt,name=step_outcome,json=stepOutcome,proto3,oneof"`
}

type Envelope_StepTransition struct {
	StepTransition *StepTransition `protobuf:"bytes,15,opt,name=step_transition,json=stepTransition,proto3,oneof"`
}

type Envelope_StepLog struct {
	StepLog *StepLog `protobuf:"bytes,16,opt,name=step_log,json=stepLog,proto3,oneof"`
}

type Envelope_AdapterEvent struct {
	AdapterEvent *AdapterEvent `protobuf:"bytes,17,opt,name=adapter_event,json=adapterEvent,proto3,oneof"`
}

type Envelope_OverseerHeartbeat struct {
	OverseerHeartbeat *OverseerHeartbeat `protobuf:"bytes,18,opt,name=overseer_heartbeat,json=overseerHeartbeat,proto3,oneof"`
}

type Envelope_OverseerDisconnected struct {
	OverseerDisconnected *OverseerDisconnected `protobuf:"bytes,19,opt,name=overseer_disconnected,json=overseerDisconnected,proto3,oneof"`
}

type Envelope_StepResumed struct {
	StepResumed *StepResumed `protobuf:"bytes,20,opt,name=step_resumed,json=stepResumed,proto3,oneof"`
}

type Envelope_VariableSet struct {
	VariableSet *VariableSet `protobuf:"bytes,21,opt,name=variable_set,json=variableSet,proto3,oneof"` // permanent (W04)
}

type Envelope_StepOutputCaptured struct {
	StepOutputCaptured *StepOutputCaptured `protobuf:"bytes,22,opt,name=step_output_captured,json=stepOutputCaptured,proto3,oneof"` // permanent (W04)
}

type Envelope_WaitEntered struct {
	// W05 wait/approval events — overseer-emitted; permanent (W05).
	WaitEntered *WaitEntered `protobuf:"bytes,23,opt,name=wait_entered,json=waitEntered,proto3,oneof"` // permanent (W05)
}

type Envelope_WaitResumed struct {
	WaitResumed *WaitResumed `protobuf:"bytes,24,opt,name=wait_resumed,json=waitResumed,proto3,oneof"` // permanent (W05)
}

type Envelope_ApprovalRequested struct {
	ApprovalRequested *ApprovalRequested `protobuf:"bytes,25,opt,name=approval_requested,json=approvalRequested,proto3,oneof"` // permanent (W05)
}

type Envelope_ApprovalDecision struct {
	ApprovalDecision *ApprovalDecision `protobuf:"bytes,26,opt,name=approval_decision,json=approvalDecision,proto3,oneof"` // permanent (W05)
}

type Envelope_BranchEvaluated struct {
	// BranchEvaluated — emitted when a branch node selects a transition arm (W06).
	// Overseer-owned event; permanent field numbers.
	BranchEvaluated *BranchEvaluated `protobuf:"bytes,27,opt,name=branch_evaluated,json=branchEvaluated,proto3,oneof"`
}

type Envelope_ForEachEntered struct {
	// ForEach events — emitted by Overseer during for_each node execution (W07).
	// Overseer-owned events; permanent field numbers.
	ForEachEntered *ForEachEntered `protobuf:"bytes,28,opt,name=for_each_entered,json=forEachEntered,proto3,oneof"`
}

type Envelope_ForEachIteration struct {
	ForEachIteration *ForEachIteration `protobuf:"bytes,29,opt,name=for_each_iteration,json=forEachIteration,proto3,oneof"`
}

type Envelope_ForEachOutcome struct {
	ForEachOutcome *ForEachOutcome `protobuf:"bytes,30,opt,name=for_each_outcome,json=forEachOutcome,proto3,oneof"`
}

type Envelope_ScopeIterCursorSet struct {
	// ScopeIterCursorSet — emitted by Overseer whenever the for_each iteration
	// cursor changes. Castle stores cursor_json verbatim into the
	// runs.variable_scope "iter" field without interpreting its contents,
	// preserving 1.6 split independence (W07). Permanent field number.
	ScopeIterCursorSet *ScopeIterCursorSet `protobuf:"bytes,31,opt,name=scope_iter_cursor_set,json=scopeIterCursorSet,proto3,oneof"`
}

type Envelope_WatchReady struct {
	// WatchReady is a protocol-level sentinel sent once at the start of a
	// WatchRun server-stream, after any persisted-event replay, to flush
	// response headers so the client's WatchRun call can return. It has no
	// associated run state; clients MUST ignore it.
	WatchReady *WatchReady `protobuf:"bytes,99,opt,name=watch_ready,json=watchReady,proto3,oneof"`
}

func (*Envelope_RunStarted) isEnvelope_Payload() {}

func (*Envelope_RunCompleted) isEnvelope_Payload() {}

func (*Envelope_RunFailed) isEnvelope_Payload() {}

func (*Envelope_StepEntered) isEnvelope_Payload() {}

func (*Envelope_StepOutcome) isEnvelope_Payload() {}

func (*Envelope_StepTransition) isEnvelope_Payload() {}

func (*Envelope_StepLog) isEnvelope_Payload() {}

func (*Envelope_AdapterEvent) isEnvelope_Payload() {}

func (*Envelope_OverseerHeartbeat) isEnvelope_Payload() {}

func (*Envelope_OverseerDisconnected) isEnvelope_Payload() {}

func (*Envelope_StepResumed) isEnvelope_Payload() {}

func (*Envelope_VariableSet) isEnvelope_Payload() {}

func (*Envelope_StepOutputCaptured) isEnvelope_Payload() {}

func (*Envelope_WaitEntered) isEnvelope_Payload() {}

func (*Envelope_WaitResumed) isEnvelope_Payload() {}

func (*Envelope_ApprovalRequested) isEnvelope_Payload() {}

func (*Envelope_ApprovalDecision) isEnvelope_Payload() {}

func (*Envelope_BranchEvaluated) isEnvelope_Payload() {}

func (*Envelope_ForEachEntered) isEnvelope_Payload() {}

func (*Envelope_ForEachIteration) isEnvelope_Payload() {}

func (*Envelope_ForEachOutcome) isEnvelope_Payload() {}

func (*Envelope_ScopeIterCursorSet) isEnvelope_Payload() {}

func (*Envelope_WatchReady) isEnvelope_Payload() {}

// RunStarted — a run has begun executing.
type RunStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	InitialStep   string                 `protobuf:"bytes,2,opt,name=initial_step,json=initialStep,proto3" json:"initial_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStarted) Reset() {
	*x = RunStarted{}
	mi := &file_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStarted) ProtoMessage() {}

func (x *RunStarted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStarted.ProtoReflect.Descriptor instead.
func (*RunStarted) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *RunStarted) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunStarted) GetInitialStep() string {
	if x != nil {
		return x.InitialStep
	}
	return ""
}

// RunCompleted — a run reached a terminal state successfully.
type RunCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalState    string                 `protobuf:"bytes,1,opt,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCompleted) Reset() {
	*x = RunCompleted{}
	mi := &file_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompleted) ProtoMessage() {}

func (x *RunCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompleted.ProtoReflect.Descriptor instead.
func (*RunCompleted) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *RunCompleted) GetFinalState() string {
	if x != nil {
		return x.FinalState
	}
	return ""
}

func (x *RunCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RunFailed — a run ended in a terminal failure.
type RunFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFailed) Reset() {
	*x = RunFailed{}
	mi := &file_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFailed) ProtoMessage() {}

func (x *RunFailed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFailed.ProtoReflect.Descriptor instead.
func (*RunFailed) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *RunFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RunFailed) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

// StepEntered — the engine began executing a step.
type StepEntered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Adapter       string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEntered) Reset() {
	*x = StepEntered{}
	mi := &file_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEntered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEntered) ProtoMessage() {}

func (x *StepEntered) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEntered.ProtoReflect.Descriptor instead.
func (*StepEntered) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *StepEntered) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepEntered) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *StepEntered) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// StepOutcome — a step finished with a named outcome (or error).
type StepOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepOutcome) Reset() {
	*x = StepOutcome{}
	mi := &file_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepOutcome) ProtoMessage() {}

func (x *StepOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepOutcome.ProtoReflect.Descriptor instead.
func (*StepOutcome) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *StepOutcome) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepOutcome) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *StepOutcome) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepOutcome) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StepTransition — the FSM moved from one node to another via an outcome.
type StepTransition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	ViaOutcome    string                 `protobuf:"bytes,3,opt,name=via_outcome,json=viaOutcome,proto3" json:"via_outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepTransition) Reset() {
	*x = StepTransition{}
	mi := &file_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepTransition) ProtoMessage() {}

func (x *StepTransition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepTransition.ProtoReflect.Descriptor instead.
func (*StepTransition) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *StepTransition) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *StepTransition) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *StepTransition) GetViaOutcome() string {
	if x != nil {
		return x.ViaOutcome
	}
	return ""
}

// StepLog — a chunk of log output from a running step.
type StepLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Stream        LogStream              `protobuf:"varint,2,opt,name=stream,proto3,enum=overseer.v1.LogStream" json:"stream,omitempty"`
	Chunk         string                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepLog) Reset() {
	*x = StepLog{}
	mi := &file_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepLog) ProtoMessage() {}

func (x *StepLog) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepLog.ProtoReflect.Descriptor instead.
func (*StepLog) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *StepLog) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepLog) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *StepLog) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

// AdapterEvent — adapter-specific structured event.
//
// On-wire contract for `data`: adapter sinks SHOULD emit JSON objects
// (top-level `{}`). For backward compatibility with Phase 0 adapters that
// emitted scalars or arrays, the Overseer transport wraps non-object
// payloads under a `value` key before conversion to Struct (e.g. the
// wire payload for the array `[1,2,3]` becomes `{"value": [1,2,3]}`).
// Subscribers MUST tolerate the wrapped shape. New adapters SHOULD
// produce object payloads and avoid relying on the wrapping.
type AdapterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Adapter       string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterEvent) Reset() {
	*x = AdapterEvent{}
	mi := &file_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterEvent) ProtoMessage() {}

func (x *AdapterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterEvent.ProtoReflect.Descriptor instead.
func (*AdapterEvent) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *AdapterEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *AdapterEvent) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *AdapterEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// OverseerHeartbeat — periodic liveness signal from an Overseer.
type OverseerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverseerHeartbeat) Reset() {
	*x = OverseerHeartbeat{}
	mi := &file_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverseerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerHeartbeat) ProtoMessage() {}

func (x *OverseerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerHeartbeat.ProtoReflect.Descriptor instead.
func (*OverseerHeartbeat) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *OverseerHeartbeat) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

// OverseerDisconnected — Castle observed the Overseer going away.
type OverseerDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverseerDisconnected) Reset() {
	*x = OverseerDisconnected{}
	mi := &file_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverseerDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerDisconnected) ProtoMessage() {}

func (x *OverseerDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerDisconnected.ProtoReflect.Descriptor instead.
func (*OverseerDisconnected) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *OverseerDisconnected) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *OverseerDisconnected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StepResumed is emitted by an Overseer before re-executing a step after a
// crash. It distinguishes a crash-restart rerun from a normal retry after a
// step failure. Castle stores and fans out this event identically to other
// envelopes; it has no run-status side-effects.
type StepResumed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Attempt       int32                  `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResumed) Reset() {
	*x = StepResumed{}
	mi := &file_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResumed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResumed) ProtoMessage() {}

func (x *StepResumed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResumed.ProtoReflect.Descriptor instead.
func (*StepResumed) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *StepResumed) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepResumed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StepResumed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WatchReady is a protocol-level sentinel payload sent by WatchRun once at
// stream start. It has no fields and no run-semantic meaning; it exists
// solely to flush Connect server-stream response headers so the client's
// WatchRun call can return before any real event is published.
type WatchReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReady) Reset() {
	*x = WatchReady{}
	mi := &file_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReady) ProtoMessage() {}

func (x *WatchReady) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReady.ProtoReflect.Descriptor instead.
func (*WatchReady) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{12}
}

// VariableSet — emitted when a workflow variable value is established.
// In W04 this fires at run start for each variable's default value.
// All field numbers are permanent.
type VariableSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // permanent
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`   // string-rendered cty value for log/UI; permanent
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // "default" | "step_output:<step>"; permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableSet) Reset() {
	*x = VariableSet{}
	mi := &file_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableSet) ProtoMessage() {}

func (x *VariableSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableSet.ProtoReflect.Descriptor instead.
func (*VariableSet) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *VariableSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableSet) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VariableSet) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// StepOutputCaptured — emitted after a step completes with captured outputs.
// All field numbers are permanent.
type StepOutputCaptured struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`                                                                                 // permanent
	Outputs       map[string]string      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepOutputCaptured) Reset() {
	*x = StepOutputCaptured{}
	mi := &file_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepOutputCaptured) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepOutputCaptured) ProtoMessage() {}

func (x *StepOutputCaptured) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepOutputCaptured.ProtoReflect.Descriptor instead.
func (*StepOutputCaptured) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *StepOutputCaptured) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepOutputCaptured) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// WaitEntered — emitted when the engine enters a wait node (W05).
// Overseer-owned event; permanent field numbers.
type WaitEntered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`         // "duration" | "signal"
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"` // present when mode=duration; e.g. "30s"
	Signal        string                 `protobuf:"bytes,4,opt,name=signal,proto3" json:"signal,omitempty"`     // present when mode=signal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitEntered) Reset() {
	*x = WaitEntered{}
	mi := &file_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitEntered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitEntered) ProtoMessage() {}

func (x *WaitEntered) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitEntered.ProtoReflect.Descriptor instead.
func (*WaitEntered) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{15}
}

func (x *WaitEntered) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WaitEntered) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WaitEntered) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *WaitEntered) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

// WaitResumed — emitted when a wait node is satisfied and execution continues (W05).
// Overseer-owned event; permanent field numbers.
type WaitResumed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Signal        string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResumed) Reset() {
	*x = WaitResumed{}
	mi := &file_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResumed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResumed) ProtoMessage() {}

func (x *WaitResumed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResumed.ProtoReflect.Descriptor instead.
func (*WaitResumed) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{16}
}

func (x *WaitResumed) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WaitResumed) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WaitResumed) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *WaitResumed) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ApprovalRequested — emitted when the engine enters an approval node (W05).
// Overseer-owned event; permanent field numbers.
type ApprovalRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Approvers     []string               `protobuf:"bytes,2,rep,name=approvers,proto3" json:"approvers,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequested) Reset() {
	*x = ApprovalRequested{}
	mi := &file_v1_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequested) ProtoMessage() {}

func (x *ApprovalRequested) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequested.ProtoReflect.Descriptor instead.
func (*ApprovalRequested) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{17}
}

func (x *ApprovalRequested) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ApprovalRequested) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *ApprovalRequested) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ApprovalDecision — emitted when an approval node is resolved via Resume (W05).
// Overseer-owned event; permanent field numbers.
type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"` // "approved" | "rejected"
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`       // audit metadata; not semantically load-bearing
	Payload       map[string]string      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_v1_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{18}
}

func (x *ApprovalDecision) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ApprovalDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ApprovalDecision) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApprovalDecision) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// BranchEvaluated — emitted when a branch node selects a transition arm (W06).
// Overseer-owned event; permanent field numbers.
type BranchEvaluated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`                               // branch node name; permanent
	MatchedArm    string                 `protobuf:"bytes,2,opt,name=matched_arm,json=matchedArm,proto3" json:"matched_arm,omitempty"` // "arm[<index>]" | "default"; permanent
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                           // transition target node name; permanent
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`                     // string-rendered condition for the matched arm; empty for default; permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchEvaluated) Reset() {
	*x = BranchEvaluated{}
	mi := &file_v1_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchEvaluated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchEvaluated) ProtoMessage() {}

func (x *BranchEvaluated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchEvaluated.ProtoReflect.Descriptor instead.
func (*BranchEvaluated) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{19}
}

func (x *BranchEvaluated) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *BranchEvaluated) GetMatchedArm() string {
	if x != nil {
		return x.MatchedArm
	}
	return ""
}

func (x *BranchEvaluated) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *BranchEvaluated) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

// ForEachEntered — emitted when a for_each node begins iterating (W07).
// Overseer-owned event; permanent field numbers.
type ForEachEntered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`    // for_each node name; permanent
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // number of items; permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForEachEntered) Reset() {
	*x = ForEachEntered{}
	mi := &file_v1_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForEachEntered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForEachEntered) ProtoMessage() {}

func (x *ForEachEntered) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForEachEntered.ProtoReflect.Descriptor instead.
func (*ForEachEntered) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{20}
}

func (x *ForEachEntered) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ForEachEntered) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ForEachIteration — emitted at the start of each per-item iteration (W07).
// Overseer-owned event; permanent field numbers.
type ForEachIteration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`                             // for_each node name; permanent
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                          // zero-based iteration index; permanent
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                           // string-rendered cty value of the current item; permanent
	AnyFailed     bool                   `protobuf:"varint,4,opt,name=any_failed,json=anyFailed,proto3" json:"any_failed,omitempty"` // true if any prior iteration produced a failure outcome; permanent.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForEachIteration) Reset() {
	*x = ForEachIteration{}
	mi := &file_v1_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForEachIteration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForEachIteration) ProtoMessage() {}

func (x *ForEachIteration) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForEachIteration.ProtoReflect.Descriptor instead.
func (*ForEachIteration) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{21}
}

func (x *ForEachIteration) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ForEachIteration) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ForEachIteration) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ForEachIteration) GetAnyFailed() bool {
	if x != nil {
		return x.AnyFailed
	}
	return false
}

// ForEachOutcome — emitted when a for_each node finishes iterating (W07).
// Overseer-owned event; permanent field numbers.
type ForEachOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`       // for_each node name; permanent
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"` // "all_succeeded" | "any_failed"; permanent
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`   // transition target node name; permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForEachOutcome) Reset() {
	*x = ForEachOutcome{}
	mi := &file_v1_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForEachOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForEachOutcome) ProtoMessage() {}

func (x *ForEachOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForEachOutcome.ProtoReflect.Descriptor instead.
func (*ForEachOutcome) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{22}
}

func (x *ForEachOutcome) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ForEachOutcome) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ForEachOutcome) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// ScopeIterCursorSet — emitted by Overseer whenever the for_each iteration
// cursor is created, advanced, or cleared. cursor_json is the JSON-encoded
// IterCursor blob; an empty string means the cursor has been cleared.
// Castle stores this verbatim into the runs.variable_scope "iter" field
// without parsing it, preserving schema independence at the 1.6 split (W07).
type ScopeIterCursorSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CursorJson    string                 `protobuf:"bytes,1,opt,name=cursor_json,json=cursorJson,proto3" json:"cursor_json,omitempty"` // JSON-encoded IterCursor or "" to clear; permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeIterCursorSet) Reset() {
	*x = ScopeIterCursorSet{}
	mi := &file_v1_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeIterCursorSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeIterCursorSet) ProtoMessage() {}

func (x *ScopeIterCursorSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeIterCursorSet.ProtoReflect.Descriptor instead.
func (*ScopeIterCursorSet) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{23}
}

func (x *ScopeIterCursorSet) GetCursorJson() string {
	if x != nil {
		return x.CursorJson
	}
	return ""
}

var File_v1_events_proto protoreflect.FileDescriptor

const file_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/events.proto\x12\voverseer.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x0e\n" +
	"\bEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12:\n" +
	"\vrun_started\x18\n" +
	" \x01(\v2\x17.overseer.v1.RunStartedH\x00R\n" +
	"runStarted\x12@\n" +
	"\rrun_completed\x18\v \x01(\v2\x19.overseer.v1.RunCompletedH\x00R\frunCompleted\x127\n" +
	"\n" +
	"run_failed\x18\f \x01(\v2\x16.overseer.v1.RunFailedH\x00R\trunFailed\x12=\n" +
	"\fstep_entered\x18\r \x01(\v2\x18.overseer.v1.StepEnteredH\x00R\vstepEntered\x12=\n" +
	"\fstep_outcome\x18\x0e \x01(\v2\x18.overseer.v1.StepOutcomeH\x00R\vstepOutcome\x12F\n" +
	"\x0fstep_transition\x18\x0f \x01(\v2\x1b.overseer.v1.StepTransitionH\x00R\x0estepTransition\x121\n" +
	"\bstep_log\x18\x10 \x01(\v2\x14.overseer.v1.StepLogH\x00R\astepLog\x12@\n" +
	"\radapter_event\x18\x11 \x01(\v2\x19.overseer.v1.AdapterEventH\x00R\fadapterEvent\x12O\n" +
	"\x12overseer_heartbeat\x18\x12 \x01(\v2\x1e.overseer.v1.OverseerHeartbeatH\x00R\x11overseerHeartbeat\x12X\n" +
	"\x15overseer_disconnected\x18\x13 \x01(\v2!.overseer.v1.OverseerDisconnectedH\x00R\x14overseerDisconnected\x12=\n" +
	"\fstep_resumed\x18\x14 \x01(\v2\x18.overseer.v1.StepResumedH\x00R\vstepResumed\x12=\n" +
	"\fvariable_set\x18\x15 \x01(\v2\x18.overseer.v1.VariableSetH\x00R\vvariableSet\x12S\n" +
	"\x14step_output_captured\x18\x16 \x01(\v2\x1f.overseer.v1.StepOutputCapturedH\x00R\x12stepOutputCaptured\x12=\n" +
	"\fwait_entered\x18\x17 \x01(\v2\x18.overseer.v1.WaitEnteredH\x00R\vwaitEntered\x12=\n" +
	"\fwait_resumed\x18\x18 \x01(\v2\x18.overseer.v1.WaitResumedH\x00R\vwaitResumed\x12O\n" +
	"\x12approval_requested\x18\x19 \x01(\v2\x1e.overseer.v1.ApprovalRequestedH\x00R\x11approvalRequested\x12L\n" +
	"\x11approval_decision\x18\x1a \x01(\v2\x1d.overseer.v1.ApprovalDecisionH\x00R\x10approvalDecision\x12I\n" +
	"\x10branch_evaluated\x18\x1b \x01(\v2\x1c.overseer.v1.BranchEvaluatedH\x00R\x0fbranchEvaluated\x12G\n" +
	"\x10for_each_entered\x18\x1c \x01(\v2\x1b.overseer.v1.ForEachEnteredH\x00R\x0eforEachEntered\x12M\n" +
	"\x12for_each_iteration\x18\x1d \x01(\v2\x1d.overseer.v1.ForEachIterationH\x00R\x10forEachIteration\x12G\n" +
	"\x10for_each_outcome\x18\x1e \x01(\v2\x1b.overseer.v1.ForEachOutcomeH\x00R\x0eforEachOutcome\x12T\n" +
	"\x15scope_iter_cursor_set\x18\x1f \x01(\v2\x1f.overseer.v1.ScopeIterCursorSetH\x00R\x12scopeIterCursorSet\x12:\n" +
	"\vwatch_ready\x18c \x01(\v2\x17.overseer.v1.WatchReadyH\x00R\n" +
	"watchReadyB\t\n" +
	"\apayload\"T\n" +
	"\n" +
	"RunStarted\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12!\n" +
	"\finitial_step\x18\x02 \x01(\tR\vinitialStep\"I\n" +
	"\fRunCompleted\x12\x1f\n" +
	"\vfinal_state\x18\x01 \x01(\tR\n" +
	"finalState\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"7\n" +
	"\tRunFailed\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\"U\n" +
	"\vStepEntered\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\"r\n" +
	"\vStepOutcome\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"U\n" +
	"\x0eStepTransition\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1f\n" +
	"\vvia_outcome\x18\x03 \x01(\tR\n" +
	"viaOutcome\"c\n" +
	"\aStepLog\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12.\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x16.overseer.v1.LogStreamR\x06stream\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\tR\x05chunk\"}\n" +
	"\fAdapterEvent\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\"4\n" +
	"\x11OverseerHeartbeat\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\"O\n" +
	"\x14OverseerDisconnected\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"S\n" +
	"\vStepResumed\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x05R\aattempt\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\f\n" +
	"\n" +
	"WatchReady\"O\n" +
	"\vVariableSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\xac\x01\n" +
	"\x12StepOutputCaptured\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12F\n" +
	"\aoutputs\x18\x02 \x03(\v2,.overseer.v1.StepOutputCaptured.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\vWaitEntered\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12\x16\n" +
	"\x06signal\x18\x04 \x01(\tR\x06signal\"\xca\x01\n" +
	"\vWaitResumed\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\x12?\n" +
	"\apayload\x18\x04 \x03(\v2%.overseer.v1.WaitResumed.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x11ApprovalRequested\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1c\n" +
	"\tapprovers\x18\x02 \x03(\tR\tapprovers\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xda\x01\n" +
	"\x10ApprovalDecision\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12D\n" +
	"\apayload\x18\x04 \x03(\v2*.overseer.v1.ApprovalDecision.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x0fBranchEvaluated\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1f\n" +
	"\vmatched_arm\x18\x02 \x01(\tR\n" +
	"matchedArm\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\":\n" +
	"\x0eForEachEntered\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"q\n" +
	"\x10ForEachIteration\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"any_failed\x18\x04 \x01(\bR\tanyFailed\"V\n" +
	"\x0eForEachOutcome\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"5\n" +
	"\x12ScopeIterCursorSet\x12\x1f\n" +
	"\vcursor_json\x18\x01 \x01(\tR\n" +
	"cursorJson*k\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02\x12\x14\n" +
	"\x10LOG_STREAM_AGENT\x10\x03B5Z3github.com/brokenbots/overseer/sdk/pb/v1;overseerv1b\x06proto3"

var (
	file_v1_events_proto_rawDescOnce sync.Once
	file_v1_events_proto_rawDescData []byte
)

func file_v1_events_proto_rawDescGZIP() []byte {
	file_v1_events_proto_rawDescOnce.Do(func() {
		file_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_events_proto_rawDesc), len(file_v1_events_proto_rawDesc)))
	})
	return file_v1_events_proto_rawDescData
}

var file_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1_events_proto_goTypes = []any{
	(LogStream)(0),                // 0: overseer.v1.LogStream
	(*Envelope)(nil),              // 1: overseer.v1.Envelope
	(*RunStarted)(nil),            // 2: overseer.v1.RunStarted
	(*RunCompleted)(nil),          // 3: overseer.v1.RunCompleted
	(*RunFailed)(nil),             // 4: overseer.v1.RunFailed
	(*StepEntered)(nil),           // 5: overseer.v1.StepEntered
	(*StepOutcome)(nil),           // 6: overseer.v1.StepOutcome
	(*StepTransition)(nil),        // 7: overseer.v1.StepTransition
	(*StepLog)(nil),               // 8: overseer.v1.StepLog
	(*AdapterEvent)(nil),          // 9: overseer.v1.AdapterEvent
	(*OverseerHeartbeat)(nil),     // 10: overseer.v1.OverseerHeartbeat
	(*OverseerDisconnected)(nil),  // 11: overseer.v1.OverseerDisconnected
	(*StepResumed)(nil),           // 12: overseer.v1.StepResumed
	(*WatchReady)(nil),            // 13: overseer.v1.WatchReady
	(*VariableSet)(nil),           // 14: overseer.v1.VariableSet
	(*StepOutputCaptured)(nil),    // 15: overseer.v1.StepOutputCaptured
	(*WaitEntered)(nil),           // 16: overseer.v1.WaitEntered
	(*WaitResumed)(nil),           // 17: overseer.v1.WaitResumed
	(*ApprovalRequested)(nil),     // 18: overseer.v1.ApprovalRequested
	(*ApprovalDecision)(nil),      // 19: overseer.v1.ApprovalDecision
	(*BranchEvaluated)(nil),       // 20: overseer.v1.BranchEvaluated
	(*ForEachEntered)(nil),        // 21: overseer.v1.ForEachEntered
	(*ForEachIteration)(nil),      // 22: overseer.v1.ForEachIteration
	(*ForEachOutcome)(nil),        // 23: overseer.v1.ForEachOutcome
	(*ScopeIterCursorSet)(nil),    // 24: overseer.v1.ScopeIterCursorSet
	nil,                           // 25: overseer.v1.StepOutputCaptured.OutputsEntry
	nil,                           // 26: overseer.v1.WaitResumed.PayloadEntry
	nil,                           // 27: overseer.v1.ApprovalDecision.PayloadEntry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 29: google.protobuf.Struct
}
var file_v1_events_proto_depIdxs = []int32{
	28, // 0: overseer.v1.Envelope.ts:type_name -> google.protobuf.Timestamp
	2,  // 1: overseer.v1.Envelope.run_started:type_name -> overseer.v1.RunStarted
	3,  // 2: overseer.v1.Envelope.run_completed:type_name -> overseer.v1.RunCompleted
	4,  // 3: overseer.v1.Envelope.run_failed:type_name -> overseer.v1.RunFailed
	5,  // 4: overseer.v1.Envelope.step_entered:type_name -> overseer.v1.StepEntered
	6,  // 5: overseer.v1.Envelope.step_outcome:type_name -> overseer.v1.StepOutcome
	7,  // 6: overseer.v1.Envelope.step_transition:type_name -> overseer.v1.StepTransition
	8,  // 7: overseer.v1.Envelope.step_log:type_name -> overseer.v1.StepLog
	9,  // 8: overseer.v1.Envelope.adapter_event:type_name -> overseer.v1.AdapterEvent
	10, // 9: overseer.v1.Envelope.overseer_heartbeat:type_name -> overseer.v1.OverseerHeartbeat
	11, // 10: overseer.v1.Envelope.overseer_disconnected:type_name -> overseer.v1.OverseerDisconnected
	12, // 11: overseer.v1.Envelope.step_resumed:type_name -> overseer.v1.StepResumed
	14, // 12: overseer.v1.Envelope.variable_set:type_name -> overseer.v1.VariableSet
	15, // 13: overseer.v1.Envelope.step_output_captured:type_name -> overseer.v1.StepOutputCaptured
	16, // 14: overseer.v1.Envelope.wait_entered:type_name -> overseer.v1.WaitEntered
	17, // 15: overseer.v1.Envelope.wait_resumed:type_name -> overseer.v1.WaitResumed
	18, // 16: overseer.v1.Envelope.approval_requested:type_name -> overseer.v1.ApprovalRequested
	19, // 17: overseer.v1.Envelope.approval_decision:type_name -> overseer.v1.ApprovalDecision
	20, // 18: overseer.v1.Envelope.branch_evaluated:type_name -> overseer.v1.BranchEvaluated
	21, // 19: overseer.v1.Envelope.for_each_entered:type_name -> overseer.v1.ForEachEntered
	22, // 20: overseer.v1.Envelope.for_each_iteration:type_name -> overseer.v1.ForEachIteration
	23, // 21: overseer.v1.Envelope.for_each_outcome:type_name -> overseer.v1.ForEachOutcome
	24, // 22: overseer.v1.Envelope.scope_iter_cursor_set:type_name -> overseer.v1.ScopeIterCursorSet
	13, // 23: overseer.v1.Envelope.watch_ready:type_name -> overseer.v1.WatchReady
	0,  // 24: overseer.v1.StepLog.stream:type_name -> overseer.v1.LogStream
	29, // 25: overseer.v1.AdapterEvent.data:type_name -> google.protobuf.Struct
	25, // 26: overseer.v1.StepOutputCaptured.outputs:type_name -> overseer.v1.StepOutputCaptured.OutputsEntry
	26, // 27: overseer.v1.WaitResumed.payload:type_name -> overseer.v1.WaitResumed.PayloadEntry
	27, // 28: overseer.v1.ApprovalDecision.payload:type_name -> overseer.v1.ApprovalDecision.PayloadEntry
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_v1_events_proto_init() }
func file_v1_events_proto_init() {
	if File_v1_events_proto != nil {
		return
	}
	file_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_RunStarted)(nil),
		(*Envelope_RunCompleted)(nil),
		(*Envelope_RunFailed)(nil),
		(*Envelope_StepEntered)(nil),
		(*Envelope_StepOutcome)(nil),
		(*Envelope_StepTransition)(nil),
		(*Envelope_StepLog)(nil),
		(*Envelope_AdapterEvent)(nil),
		(*Envelope_OverseerHeartbeat)(nil),
		(*Envelope_OverseerDisconnected)(nil),
		(*Envelope_StepResumed)(nil),
		(*Envelope_VariableSet)(nil),
		(*Envelope_StepOutputCaptured)(nil),
		(*Envelope_WaitEntered)(nil),
		(*Envelope_WaitResumed)(nil),
		(*Envelope_ApprovalRequested)(nil),
		(*Envelope_ApprovalDecision)(nil),
		(*Envelope_BranchEvaluated)(nil),
		(*Envelope_ForEachEntered)(nil),
		(*Envelope_ForEachIteration)(nil),
		(*Envelope_ForEachOutcome)(nil),
		(*Envelope_ScopeIterCursorSet)(nil),
		(*Envelope_WatchReady)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_events_proto_rawDesc), len(file_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_events_proto_goTypes,
		DependencyIndexes: file_v1_events_proto_depIdxs,
		EnumInfos:         file_v1_events_proto_enumTypes,
		MessageInfos:      file_v1_events_proto_msgTypes,
	}.Build()
	File_v1_events_proto = out.File
	file_v1_events_proto_goTypes = nil
	file_v1_events_proto_depIdxs = nil
}
